### ISSUE TITLE
Dynare 4.3.3 won't compile

### ISSUE THREAD

**Issue by mboisson** [DynareTeam/dynare#1005]
I am trying to compile Dynare 4.3.3 for a user (he needs this specific version). I get the following error : 
DynareBison.yy:45:36: error: ‘const struct Dynare::parser::stack_symbol_type’ has no member named ‘begin’
         (Current).begin = (Rhs)[1].begin;               \
                                    ^
DynareBison.cc:619:7: note: in expansion of macro ‘YYLLOC_DEFAULT’
       YYLLOC_DEFAULT (yylhs.location, slice, yylen);
       ^
DynareBison.yy:46:36: error: ‘const struct Dynare::parser::stack_symbol_type’ has no member named ‘end’
         (Current).end   = (Rhs)[N].end;                 \
                                    ^
DynareBison.cc:619:7: note: in expansion of macro ‘YYLLOC_DEFAULT’
       YYLLOC_DEFAULT (yylhs.location, slice, yylen);
       ^
DynareBison.yy:50:52: error: ‘const struct Dynare::parser::stack_symbol_type’ has no member named ‘end’
         (Current).begin = (Current).end = (Rhs)[0].end; \
                                                    ^
DynareBison.cc:619:7: note: in expansion of macro ‘YYLLOC_DEFAULT’
       YYLLOC_DEFAULT (yylhs.location, slice, yylen);
       ^
DynareBison.yy:45:36: error: ‘struct Dynare::parser::stack_symbol_type’ has no member named ‘begin’
         (Current).begin = (Rhs)[1].begin;               \
                                    ^
DynareBison.cc:5399:7: note: in expansion of macro ‘YYLLOC_DEFAULT’
       YYLLOC_DEFAULT (error_token.location, yyerror_range, 2);
       ^
DynareBison.yy:46:36: error: ‘struct Dynare::parser::stack_symbol_type’ has no member named ‘end’
         (Current).end   = (Rhs)[N].end;                 \
                                    ^
DynareBison.cc:5399:7: note: in expansion of macro ‘YYLLOC_DEFAULT’
       YYLLOC_DEFAULT (error_token.location, yyerror_range, 2);
       ^
DynareBison.yy:50:52: error: ‘struct Dynare::parser::stack_symbol_type’ has no member named ‘end’
         (Current).begin = (Current).end = (Rhs)[0].end; \
                                                    ^
DynareBison.cc:5399:7: note: in expansion of macro ‘YYLLOC_DEFAULT’
       YYLLOC_DEFAULT (error_token.location, yyerror_range, 2);

Any idea how to solve this ?

**Comment by JohannesPfeifer** [comment]
I am not sure we should provide support for back-versions of Dynare. Obviously, many bugs have been fixed in recent versions. Keeping old versions up to date with newer software seems like a neverending issue. For example, older versions won't work with newer Matlab versions due to changes in Matlab's random number generator. Similarly, you point out the autoreconf incompatibility in #1006 . Thus, I would rather provide support for migrating old mod-files to more recent version of Dynare.

**Comment by mboisson** [comment]
Hi,
So, should I send the user who is telling me that his results are different with 4.4.3 than 4.4.3 (and therefore wanted to stick with the same version) to contact you to figure out why the results are different ?

**Comment by JohannesPfeifer** [comment]
@mboisson If Dynare 4.4.3 returns something substantially different from 4.3.3. my prior is that there is something wrong with the older version that affects his results. Sticking with 4.3.3 is not advised unless there is a really good reason for doing so. The other possibility is that a new bug was introduced, but again, understanding the source of the difference is crucial. I can help to investigate. As I run Windows, using older versions is easy.
