### ISSUE TITLE
Add bandpass filter

### ISSUE THREAD

**Issue by JohannesPfeifer** [DynareTeam/dynare#1011]
Adding a bandpass-filter as in Christiano/Motto/Rostagno seems straightforward. 

One issue is ```options_.hp_ngrid``` which specifies the number of points for the Inverse Fourier Transformation. With a different filter, this option would not be specific to the HP filter anymore. I would suggest renaming it to ```ifft_points``` and deleting the old option. Obviously, this would break backward compatibility.

@houtanb Could you please give me an option of ```stoch_simul``` named ```bandpass_filter``` It should be mutually exclusive with ```hp_filter```. If specified as 
```
stoch_simul(bandpass_filter)
```
it should map into ```options_.bandpass.indicator=1```. If specified as 
```
stoch_simul(bandpass_filter=[lowerbound upperbound])
```
it should map into 
```
options_.bandpass.indicator=1
options_.bandpass.passband=[lowerbound upperbound]
```
Default values are
```
options_.bandpass.indicator=0;
options_.bandpass.passband=[6 32];
```

**Comment by houtanb** [comment]
@JohannesPfeifer for the bounds, I can do something like:
```
options_.bandpass.periodicity = [32 6];
```
Is this ok?

**Comment by JohannesPfeifer** [comment]
Yes, but please map into ```[6 32]```

**Comment by JohannesPfeifer** [comment]
@houtanb While I am doing requests with respect to filterin: Could you please also do ```one_sided_hp_filter=x```
mirroring the hp_filter option and mapping into
```options_.one_sided_hp_filter=x```
with the default being 1600?

**Comment by houtanb** [comment]
@JohannesPfeifer I thing there's a type in your last message

**Comment by houtanb** [comment]
@JohannesPfeifer there is no mapping as far as the periodicity vector goes. The vector will be printed in the order the user entered it as the option

**Comment by JohannesPfeifer** [comment]
@houtanb Right. That's perfect. I updated the post. Could you then name it ```passband``` instead of ```periodicity```? I can deal with the initialization in ```global_initialization```

**Comment by houtanb** [comment]
ok. @JohannesPfeifer there is still a problem with your comment about the ```one_sided_hp_filter```

**Comment by JohannesPfeifer** [comment]
@houtanb Sorry, but I don't see what you mean.

**Comment by houtanb** [comment]
what should it map into?

**Comment by houtanb** [comment]
forget it. I had to reload the page

**Comment by JohannesPfeifer** [comment]
Strange. On my screen it clearly shows
```
options_.one_sided_hp_filter=x
```
