### ISSUE TITLE
Add one-sided HP filter

### ISSUE THREAD

**Issue by JohannesPfeifer** [DynareTeam/dynare#1012]
#1011 already implemented the interface. Before adding the function, we need to decide whether to simply add it as a function that operates on regular double data like the ```sample_hp_filter``` or whether we want to make it a function on dseries objects as the ```baxter_king_filter.m``` of the dseries submodule.

**Comment by MichelJuillard** [comment]
Proposed decision: do both

**Comment by JohannesPfeifer** [comment]
#1083 now includes it as a regular function. We can still port it to a dseries object of desired.
