### ISSUE TITLE
Fix saving of posterior standard deviations

### ISSUE THREAD

**Issue by JohannesPfeifer** [DynareTeam/dynare#1013]
See also http://www.dynare.org/phpBB3/viewtopic.php?f=1&t=7130
When running the MCMC, the ```oo_.posterior_std``` and ```oo_.posterior_mode``` fields are based on the posterior mode, not the MCMC. But the manual says they should only be there if ```mh_replic>0``` but we always write them. 
In contrast, ```oo_.posterior_variance``` is based on the MCMC. However, this field is not documented in the manual at all. 

It is also confusing that the MCMC writes only a variance and ML/mode-finder only a standard deviation.

We must decide on a consistent treatment and fix the manual accordingly. 
My proposal is: We change the current ```oo_.posterior_std``` to ```oo_.posterior_std_at_mode``` to make the meaning explicit and let the MCMC now also write ```oo_.posterior_std```. This would be closest to what the manual states as all fields then would have the intended meaning while only adding additional fields. If need be, this would also allow going back to the 4.4 "convention" using the ```convert_dyn_45_to_44``` utility.

**Comment by MichelJuillard** [comment]
Maybe, we should have a first level of name that makes clear the algorithm used for the computation (optimization, MCMC).

**Comment by JohannesPfeifer** [comment]
@MichelJuillard I am not entirely convinced of adding another layer. We already have fields like
```oo_.posterior_hpdsup.measurement_errors_corr.gdp_conso```. It would also change the storage of all posterior moments. I can also do that, but is seems to be a bit of an overkill.

The only ambiguous field seems to be ```oo_.posterior_std```. Thus, I would prefer to just rename it and leave the other fields untouched.

But I can also do your suggestion.

**Comment by MichelJuillard** [comment]
Let's do it your way. We can re-organize later
