### ISSUE TITLE
Check correctness of DSGE-VAR Wiki

### ISSUE THREAD

**Issue by JohannesPfeifer** [DynareTeam/dynare#1021]
According to Del Negro/Schorfheide (2004), the variance priors and posteriors have degrees of freedom correction with number of estimated parameters in the VAR equation, i.e. variables times lags plus a constant:
```
m*p+1
```
However, http://www.dynare.org/DynareWiki/DsgeVar does not feature a constant in the description, but still uses the same initial improper prior with ```m+1``` as if a constant would be used (below eqation (21) in DNS (2004)).  

Similarly, equations P2 and Q2 of the Wiki use a correction of ```-mp-m=-m*(p+1)``` suggesting a constant for every variable in each equation. 

While the condition for ```lambda*T<m(p+1)``` coincides with the one below equation (21) in DNS (2004), there is no formal derivation of this condition in DNS . The Wiki motivates this statement by alluding to the fact that we could not use OLS to estimate the equation if ```T<m(p+1)```. But this again looks strange as the number of parameters estimated is just ```m*p+1```.

**Comment by JohannesPfeifer** [comment]
Addendum: the condition ```lambda*T<m(p+1)``` for a valid prior sees to come from the Wishart distribution where in Appendix A1 without this condition the Gamma function would be evaluated at a negative number. I don't see the immediate relation to the number of observations/degrees of freedom used for the likelihood.

**Comment by houtanb** [comment]
@JohannesPfeifer We use the github issues for code-related work only, not as a general to-do list. I think it would be better to send this to the dev list.
