### ISSUE TITLE
Save posterior moments even when moments are constant

### ISSUE THREAD

**Issue by JohannesPfeifer** [DynareTeam/dynare#1024]
In ```covariance_mc_analysis.m``` and the like we test whether the moments are constant and, if yes, we store NaN. I don't see the logic of this. All moments are still well-defined (although identical). I would propose to get rid of this check and always store the computed moments.

**Comment by JohannesPfeifer** [comment]
@houtanb Does this mean it is OK to do this or do we still need a decision?

**Comment by MichelJuillard** [comment]
Proposed decision: make the change proposed by @JohannesPfeifer

**Comment by stepan-a** [comment]
I do not understand the problem raised by @JohannesPfeifer (also see #1086). If the posterior distribution is degenerated, what should we report for the deciles, intervals or densities? I agree that there is no logic in reporting NaNs, but this has the merit to warn the user (even the most inattentive one) than something goes wrong.

**Comment by MichelJuillard** [comment]
@stepan-a I would report
- identical deciles
- 0 width intervals
- collapsed densities, maybe NaN if there is no better way

**Comment by JohannesPfeifer** [comment]
@stepan-a Even if you have a degenerate point density, the quantiles are well-defined as we are talking about a discrete distribution over draws. They are just identical, which is what we report now. Reporting NaN seems wrong to me as the percentile over the draws seems to be well defined.
@MichelJuillard That is what happens now. The deciles and HPDIs will be identical as the xth percentile of draws will have exactly this same value.

**Comment by JohannesPfeifer** [comment]
@MichelJuillard What I forgot: the density estimate will also automatically return NaN when all values are the same.

**Comment by stepan-a** [comment]
@JohannesPfeifer I understand that we can compute these moments. My only concern is that this would be more misleading than returning NaNs (even the posterior mean is wrong). Users need to understand that they do not have any sensible result in this case. I think that if we do as you suggest, Dynare should at least issue a warning saying that something is wrong with the MCMC.

**Comment by JohannesPfeifer** [comment]
@stepan-a Why is this misleading and why is the posterior mean wrong? There are numerous cases where the posterior object can be constant without the MCMC being the culprit. For example, whenever there is an identity in the model, those two variables will have correlation 1 and there will be no variation even if the MCMC did work perfectly. Why should we report NaN here?
I see the problem that we cannot distinguish the source of constancy.

**Comment by stepan-a** [comment]
@JohannesPfeifer, I misunderstood the object of your PR. Your concern is only about the posterior distribution of the second order moments... Looking too quickly I understood that this was also about the posterior distribution of the estimated parameters. Sorry for the noise. I run the testsuite right now and push on master if the PR does not produce errors.
