### ISSUE TITLE
typo in dsge_likelihood.m

### ISSUE THREAD

**Issue by tholden** [DynareTeam/dynare#1033]
Lines 366 and 480 of dsge_likelihood.m are as follows:
```
switch DynareOptions.lik_init
    ...
    case options_.lik_init == 5            % Old diffuse Kalman filter only for the non stationary variables
```
I presume the `options_.lik_init == ` should not be there? `options_` is no longer even defined in DsgeLikelihood.m, so if none of the previous cases have been matched, a MATLAB error will be generated when MATLAB attempts to access a field of the non-existent structure.

**Comment by JohannesPfeifer** [comment]
@tholden This is a duplicate of #992

**Comment by tholden** [comment]
Apologies.
