### ISSUE TITLE
check_matlab_path.m fails if there are files with single letter file names

### ISSUE THREAD

**Issue by tholden** [DynareTeam/dynare#1040]
Line 131 is as follows:
```
if isequal(dd(f).name(end-1:end),'.m')
```
If the file name is length 1, then end-1 evaluates to a 0, causing an error. A fix is included in this commit: https://github.com/tholden/dynare/commit/99742309d2fe3468bcdc7074a0120be00222912b
in which that line is changed to:
```
if strcmpi(dd(f).name(max(1,end-1):end),'.m')
```

**Comment by houtanb** [comment]
@tholden two things:

* For us to merge your commit, you need to create a pull request
* You rightly point out that we ignore ```.M``` files which were supported until R2011b. Thanks for noticing this
* I think the ```max``` confuses the issue, as we're trying to choose only ```.m``` files here. Why not use
```
[junk, name, ext] = fileparts(dd(f).name)
if isequal(ext, '.m') || isequal(ext, '.M')
```
* Finally, it seems like the  ```if``` body can be simplified to ```flist{end+1} = name;```, though this may need to be tested (I don't immediately see why it was ```[dd(f).name]``` but perhaps there was a good reason for using the brackets)

**Comment by houtanb** [comment]
Actually, it seems like we can avoid looping through the files, as long as we can find the analogous Windows command to the following (I guess it's something using ```dir```):
```
[junk, mfiles] = system('ls -m *.m');
flist = textscan(mfiles, '%s', 'delimiter', ',' );
flist = flist{:};
[junk, directories] = system('ls -dm */');
dlist = textscan(directories, '%s', 'delimiter', ',' );
dlist = dlist{:};
```
Then just loop through the directories adding their ```.m``` files to ```flist```

**NB**: This is just an idea and would have to be tested....

**Comment by tholden** [comment]
I'll leave this to you if that's OK. I have a lot of changes in my version of Dynare, so creating a pull request would be more hassle than it's worth for a 1 line change. (And I'm desperately trying to hit a deadline right now.)

**Comment by JohannesPfeifer** [comment]
@houtanb Using the ```dir``` command in Windows seems impractical. How about something along the line
```
function flist = getallroutinenames(p, excludedsubfolders)
    if nargin<2
        excludedsubfolders = {};
    end
    flist={};
    %get m-files in this directory
    dd = dir([p,filesep '*.m']);
    temp=struct2cell(dd);
    flist=[flist temp(1,:)];
    %deal with subdirectories
    dlist=getalldirectories(p,excludedsubfolders); %first call with excluded directories
    for ii=1:length(dlist)
        flist=[flist getallroutinenames([ p filesep dlist{ii}])]; %recursive calls without subfolders
    end
    

function dlist = getalldirectories(p,excluded_directories)
    if nargin<2
        excluded_directories = {};
    end
    dd = dir(p);
    dir_result=struct2cell(dd);
    directory_indicator=cell2mat(dir_result(4,:));
    dlist = dir_result(1,directory_indicator==1 & ~strcmp('.',dir_result(1,:)) & ~strcmp('..',dir_result(1,:)) & ~ismember(dir_result(1,:),excluded_directories));
```

**Comment by houtanb** [comment]
@JohannesPfeifer your solution looks pretty good. If you have the time, feel free to implement it, test it, and create a pull request. If not, let me know and I'll do it sometime soon.

**Comment by stepan-a** [comment]
I imagine we should also fix the routine ```get_directory_description```, which lists all the m files under a folder, in ```m-unit-tests``` submodule.

**Comment by JohannesPfeifer** [comment]
@houtanb I tried it according to my best knowledg and it worked. But I have no clear grasp how to trigger the different cases where the function is supposed to operate. That makes it hard for me to rigorously test it. Maybe @stepan-a can have a look

**Comment by houtanb** [comment]
@JohannesPfeifer to make the function work, I think you need to open matlab, then type:
```
addpath /path/to/dyanre/master/matlab
addpath /path/to/somewhere/else
```
