### ISSUE TITLE
Save planner objective after running discretionary_policy

### ISSUE THREAD

**Issue by JohannesPfeifer** [DynareTeam/dynare#1041]
For some reason ```discretionary_policy.m``` has the commented line 
```
%oo_ = evaluate_planner_objective(oo_.dr,M_,oo_,options_);
```
Is there a reason we do not simply add
```
oo_.planner_objective_value = evaluate_planner_objective(M_,options_,oo_);
```
to the function to actually save the objective function value as for Ramey?

**Comment by MichelJuillard** [comment]
It should work but it would be nice to have an example where we know the right answer

**Comment by JohannesPfeifer** [comment]
@MichelJuillard I wonder what could go wrong? We use the same function for Ramsey to evaluate the objective. If the value would be wrong, the whole ```discretionary_policy``` command would return wrong results. Or what am I missing? But I agree that we should have a unit test for correctness.
