### ISSUE TITLE
Make Ramsey and discretionary_policy mutually exclusive via preprocessor

### ISSUE THREAD

**Issue by JohannesPfeifer** [DynareTeam/dynare#1047]
Follows discussion on mailing list on 31/08/2015.

**Comment by houtanb** [comment]
@JohannesPfeifer are ```ramsey_model``` and ```ramsey_policy``` mutually exclusive as well?

**Comment by MichelJuillard** [comment]
No they are more like synonymous

On September 3, 2015 4:38:57 PM CEST, Houtan Bastani <notifications@github.com> wrote:
>@JohannesPfeifer are ```ramsey_model``` and ```ramsey_policy```
>mutually exclusive as well?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/DynareTeam/dynare/issues/1047#issuecomment-137469102

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by houtanb** [comment]
So then ```discretionary_policy``` is mutually exclusive to both ```ramsey_model``` and ```ramsey_policy```?
