### ISSUE TITLE
argument steadystate_check_flag is ignored in evaluate_steady_state

### ISSUE THREAD

**Issue by MichelJuillard** [DynareTeam/dynare#1054]

**Comment by JohannesPfeifer** [comment]
@MichelJuillard Do you have an example of this? Or more information?

**Comment by JohannesPfeifer** [comment]
@MichelJuillard I guess this should have a bug label. What exactly is the issue here?

**Comment by stepan-a** [comment]
Michel encountered an example where (for a model with unit root) ```nocheck``` option is not honoured.
