### ISSUE TITLE
Rethink default clear all to improve compatibility with Matlab 2015b

### ISSUE THREAD

**Issue by JohannesPfeifer** [DynareTeam/dynare#1057]
With Matlab 2015b the default ```clear all``` statement interferes with the new just-in-time compiler, resulting in many warnings and poor performance. 
We may want to get rid of this clear all.

**Comment by MichelJuillard** [comment]
If we don't replace the initial ``clear all``` with something equivalent better suited for R2015b, we will need to change all ```if exist()``` constructs in the code as their logic rest on starting Dynare with an empty work space.
We should also watch for syntax updating objects assuming that they didn't exist upon starting Dynare. I'm thinking in particular to structures: Even if ```a``` doesn't exist, it is legal to create ```a````with
```
a.b = 1;
```
 but then, we are not sure that ```a``` is empty.
We will need to always initialize:
```
a = struct();
a.b = 1;
```

**Comment by JohannesPfeifer** [comment]
@MichelJuillard Why do we use a ```clear all```? 
Why not 

``` clear('M_','oo_','options_','ys0_','ex0_','estimation_info') ```

That is, we could just selectively delete all global variables that are defined a few lines later. That should solve the issue and preserve compatibility.

**Comment by stepan-a** [comment]
I agree with @JohannesPfeifer. We only need to clear the global variables, with:
```matlab
clear global
```
or we can use the ```clearvars``` command.

**Comment by MichelJuillard** [comment]
I'm not sure that this list of global variables is exhaustive. Needs to be checked. We probably need to do something about persistent variables as well. Normally, they should be properly initialized, but a second security is probably helpful

**Comment by JohannesPfeifer** [comment]
```clearvars``` seems to be the best option, but it is not available in Octave.

**Comment by stepan-a** [comment]
We can still use ```clear all```for Octave (and/or old versions of matlab, ```clearvars``` was introduced in Matlab 2008)

**Comment by stepan-a** [comment]
I think, but need to check, that there is also a ```clear persistent```...

**Comment by JohannesPfeifer** [comment]
Clearing persistent variables seems to be hard, see http://de.mathworks.com/matlabcentral/answers/16799-best-method-to-clear-persistent-variables

**Comment by stepan-a** [comment]
Doing timing with ```fs2000.mod``` using matlab R2015b I do not find significant differences when I try with/without options ```noclearall``` or ```onlyclearglobals```... So I wonder if we really care about JIT performance issues. The time spent in JIT compilation is not so important (even for larger models, as the preprocessor rewrites the dynamic and static routines for each dynare run,  there is not much difference to expect). But we need at least to deal with the warnings displayed by matlab (about the clearing of functions ```dynare.m```, ```fs2000.m```, ...). I do not know how to do that... I do not know if it is possible to clear all the functions/variables except a subset of functions (maybe with regular expressions). Or we can simply hide the warning.

**Comment by stepan-a** [comment]
The command ```grep -lR ^persistent *```in folder ```dynare/matlab``` returns the following list of matlab routines containing persistent variables:
```bash
discretionary_policy_1.m
dsge_var_likelihood.m
dyn_first_order_solver.m
dyn_waitbar.m
ep_residuals.m
evaluate_likelihood.m
evaluate_smoother.m
gsa/prior_draw_gsa.m
identification_analysis.m
kalman/likelihood/computeDLIK.m
kalman/likelihood/univariate_computeDLIK.m
metropolis_draw.m
missing/corrcoef/flag_implicit_skip_nan.m
moment_function.m
non_linear_dsge_likelihood.m
optimization/mr_hessian.m
parallel/masterParallel.m
particles/src/auxiliary_initialization.m
particles/src/auxiliary_particle_filter.m
particles/src/conditional_filter_proposal.m
particles/src/conditional_particle_filter.m
particles/src/gaussian_filter.m
particles/src/gaussian_filter_bank.m
particles/src/gaussian_mixture_filter.m
particles/src/gaussian_mixture_filter_bank.m
particles/src/online_auxiliary_filter.m
particles/src/sequential_importance_particle_filter.m
particles/src/solve_model_for_online_filter.m
perfect-foresight-models/perfect_foresight_simulation.m
prior_draw.m
priordens.m
smm_objective.m
```
For Matlab > R2015a I propose to replace the ```clear all``` statement by ```clearvars``` and  apply ```clear``` to the functions listed above. I will write a matlab function to do that. Ideally I would like to obtain the information returned by Grep using pure matlab code

**Comment by MichelJuillard** [comment]
OK for me

**Comment by stepan-a** [comment]
Done in commits e52ce43569398c9ea347458b51700020e0f9a412 and 18a5eea7e05cdf701a0e1a8fb0ba916f50e914a3. Note that I did not check on Windows (for which I use ```findstr``` as a replacement for ```grep```). Also the testsuite does not test this because we use matlab R2014b on karaba.

**Comment by JohannesPfeifer** [comment]
I don't know about Linux, but on Windows the ```findstr``` operation takes 2 minutes on my machine. That is prohibitive.

**Comment by MichelJuillard** [comment]
I didn't understand that you were greping on each Dynare run. I would integrate that in the package building procedure, making automatically a list of files containing persisent and writing them in a file that is static in a given distribution.

**Comment by stepan-a** [comment]
That is weird... In my virtualbox ```findstr``` is much faster. Besides, I do not grep on each Dynare run. I use grep the first time and I save a mat file containing the list of files where ```persistent``` variables are used. Then, on each run I test if the file exist and check that this file is newer than all the files in the matlab folder (and subfolders). If some of the routines are modified or added after the creation of the mat file, or if the mat file does not exist, I (re)grep the matlab folder.  This is the expected behavior, if there is no bug in the implementation. I will check that and also the timing on windows.

Another approach is to distribute a function that returns a hard coded list of functions, as Michel suggests, but this is not safe if a user changes some routines (adding persistent variables)... But we can decide we do not care about this kind of situation.

**Comment by MichelJuillard** [comment]
I prefer the static file. Users using persistent variables in their own files have better to know the dangers of this construct. I don't think that we should worry about them.

**Comment by stepan-a** [comment]
Okay, I'll do that with a script to update the static file.
