### ISSUE TITLE
Skip dynare initialization when run with noclearall when dynare has previously run

### ISSUE THREAD

**Issue by tholden** [DynareTeam/dynare#1066]
The below is a feature request which seems particularly pertinent in light of https://github.com/DynareTeam/dynare/issues/1057 :

In code that calls dynare repeatedly with noclearall, the time spent in Dynare's initialization can be a non-trivial contribution.

Can we set a global flag when Dynare is initialized (e.g. paths set, mex files found, etc.), and skip as much as possible on subsequent runs?

**Comment by JohannesPfeifer** [comment]
@tholden Where would you ever need this? You are not supposed to run Dynare repeatedly, but rather loop over the respective command without taking derivatives etc again. Which application do you have in mind that repeatedly requires new preprocessing?

**Comment by tholden** [comment]
Well dynareOBC does it for one. ( https://github.com/tholden/dynareOBC ) First dynare call just runs the preprocessor, the output is processed by dynareOBC, then a second dynare call just gets the steady-state, further processing is done on the mod file in light of the steady-state, then a final dynare call does the actual work. Doing this without the repeated calls would have required me to make substantial changes to the dynare preprocessor, which would have made dynareOBC a replacement, rather than an add on for Dynare, and would have made it much harder to maintain.

But more standard examples are easy to come up with too. What about looping over all of the models in the Volker Wieland's model database? Seems like quite a plausible use case.

**Comment by stepan-a** [comment]
I think I do not understand your problem. Most of the time is spent, but obviously it depends on the size of the model, in the parsing of the model (when we compute the derivatives and write the dynamic and static files)... Not in checking the availability of the various mex files (and setting the paths).  In the situations you are referring to, I understand that the model changes so you need to parse the model(s) each time.

It should be possible to save the configuration settings on the disk and avoid the need to reset the paths for each run, but I believe that this would be prone to a lot of bugs (what if a user works with different versions of matlab, or with matlab and octave, ...)

I will close this  issue unless you come up with a case where the time spent in the initialization of dynare is significant.

**Comment by JohannesPfeifer** [comment]
@stepan-a call to ```dynare_config``` adds about 1 second to each run on my machine. An option like ```noconfig``` might be a way out so that Dynare only needs to be called once at the start and then one can use e.g.
```dynare mymodfile noclearall nonconfig```
in subsequent runs.

**Comment by MichelJuillard** [comment]
I think calls to addpath are expensive. It would be more efficient to accumulate the different paths in a string and call addpath only once at the end of the configuration. Maybe it would be enough and without an extra option

**Comment by stepan-a** [comment]
Okay. One second is not a problem for me, but I will do what Michel suggests.

**Comment by stepan-a** [comment]
Done in d80f6d9a996a5b00fd449b221da17edb34b9bf1b, where I removed almost all the expensive calls to ```addpath``` command.
