### ISSUE TITLE
initial estimation checks

### ISSUE THREAD

**Issue by rattoma** [DynareTeam/dynare#1071]
The first checks in `initial_estimation_checks.m` are not robust to the case where for example we use mixed frequency data.
Assume we have annual data in time interval 1995-2000 and quarterly data in 2001-2015, I would define the annual variable and the quarterly variable as BOTH observed, but with missing values mutually exclusive, i.e. in 1995-2000 Q data will be NaN, while in 2001-2015 the annual data will have been set to NaN.
This means it is not sufficient to check the # of observables declared, but we need to check the max number of non missing data values in each time point, and confront this to the number of non zero shocks declared.

**Comment by JohannesPfeifer** [comment]
@rattoma Do you want to do this or shall I do it?

**Comment by rattoma** [comment]
Hi Johannes,
you have been very quick in making a pukll request on this. Thank you!!
best
Marco
