### ISSUE TITLE
test suite timing: when a test is run more than once on a given day, keep the last run

### ISSUE THREAD

**Issue by houtanb** [DynareTeam/dynare#1074]

**Comment by stepan-a** [comment]
@houtanb  Why do you want to do that? If each run corresponds to a different commit we should keep all the results.

**Comment by houtanb** [comment]
@stepan-a it's for the timing that takes dates along the x-axis without the time. This may not be necessary in bokeh and we could potentially keep the timing of those intermediary tests as well

**Comment by houtanb** [comment]
This is no longer necessary. Bokeh will handle plotting multiple points on the same date
