### ISSUE TITLE
Add preprocessor interface for prior_posterior_function

### ISSUE THREAD

**Issue by JohannesPfeifer** [DynareTeam/dynare#1076]
See original PR https://github.com/DynareTeam/dynare/pull/871

**Comment by houtanb** [comment]
@JohannesPfeifer is there a reason to not save the output of ```execute_prior_posterior_function``` in ```oo_```? Why do we need the separate output variable?

**Comment by JohannesPfeifer** [comment]
@houtanb No particular reason. We can save it into ```oo_``` and adjust the documentation accordingly.

**Comment by houtanb** [comment]
@JohannesPfeifer please check the doc and ```execute_prior_posterior_function``` as I changed them a bit.

Also, @JohannesPfeifer, can we change the option ```prior_posterior_sampling_draws``` to just ```sampling_draws```?

Finally, @JohannesPfeifer, it might be neater to create two commands: ```prior_function``` and ```posterior_function```. If not, to have either ```prior``` or ```posterior``` be the default for the current function

**Comment by JohannesPfeifer** [comment]
@houtanb i will check them later today. But all your suggested changes are good ideas

**Comment by houtanb** [comment]
@JohannesPfeifer any update here? Do you have a preference for two commands or one command and a default?

**Comment by JohannesPfeifer** [comment]
@houtanb I still have to check it out, but I would prefer two commands. That makes the setup on the user interface side cleaner without requiring changes in the Matlab implementation
