### ISSUE TITLE
Integrate doubling algorithm into lyapunov_symm

### ISSUE THREAD

**Issue by JohannesPfeifer** [DynareTeam/dynare#1077]
Following #988 and the discussions at the 2015 Dynare conference, we should integrate `disclyap_fast.m` into `lyapunov_symm` to have one solver only. The question is whether we want to integrate this as a call to `disclyap_fast.m`as an external function or whether to make `disclyap_fast.m` a nested function within  `lyapunov_symm`. I would prefer the latter, because it makes the function with the doubling algorithm reusable as a standalone in the way Herbst (2015) and Schmitt-Grohé/Uribe already use it.

When doing this, we also need to discuss the option handling as we currently do not pass the doubling tolerance to `lyapunov_symm`. Currently, we pass `lyapunov_fixed_point_tol`. I would propose to use this input argument as the tolerance criterion if the doubling algorithm is selected.

**Comment by MichelJuillard** [comment]
@JohannesPfeifer I would prefer to have one master function lyapunov_solver.m calling different algorithms implemented in their own *.m file

**Comment by JohannesPfeifer** [comment]
@MichelJuillard do you really want a new function? lyapunov_symm.m already is a master function calling different (external) algorithms.

**Comment by MichelJuillard** [comment]
@JohannesPfeifer I would do one master file that only check for and call the different methods and one file per method. Maybe there is some code common to each method that could go in the top file

**Comment by JohannesPfeifer** [comment]
Closed by manually merging #1354
