### ISSUE TITLE
Allow changing planner_discount in mod-file (preprocessor restriction)

### ISSUE THREAD

**Issue by JohannesPfeifer** [DynareTeam/dynare#1092]
See the discussion on the mailing list on 31/08/2015. This problem crashes the ```Gali_discretion.mod``` unit test. My proposal is:
Treat the planner_discount option like any other option (or parameter for that matter) and allow resetting it via the same statement later on. If a warning is needed, I would provide a warning that the planner_discount has been updated. But I don't really see the need for this warning. Changing parameters is common.

**Comment by houtanb** [comment]
Discussion begins here: http://www.dynare.org/pipermail/dev/2015-August/004193.html

**Comment by MichelJuillard** [comment]
I tend to agree with @JohannesPfeifer and think that we should treat optimal_policy_discount_factor as any other parameter. It just happens that the option of the optimal policy commands can set or reset its value.
We need to change the handling of the planner_discount option so as to check whether optimal_policy_discount_factor exits. If it does, set its value, if it doesn't, add this parameter and set its value
