### ISSUE TITLE
Check setting of bayestopt_ in set_prior.m

### ISSUE THREAD

**Issue by JohannesPfeifer** [DynareTeam/dynare#1094]
In master, ```ls2003.mod``` crashes, because ```set_prior.m``` is called, which overwrites ```bayestopt_``` globally. The main culprit is the bottom line:
```
% Put bayestopt_ in matlab's workspace
assignin('base','bayestopt_',bayestopt_);
```
I don't understand why we have ```set_prior.m``` returning ```bayestopt_``` as a function output and simultaneously setting it as a global variable. I would propose getting rid of the above statement.

**Comment by rattoma** [comment]
Indeed I am getting crazy trying to fix that right now ... getting rid would be best for me
