### ISSUE TITLE
Add the possibility to solve underdetermined models

### ISSUE THREAD

**Issue by sebastien-villemot** [DynareTeam/dynare#111]
When the Blanchard-Kahn conditions are not satisfied because the model is underdetermined, it is possible to select a solution among the infinity of solutions, provided we impose more restrictions.

We can implement the solution of Lubik and Schorfheide, “Testing for Indeterminacy:An Application to U.S. Monetary Policy” (AER, 2004), see http://ideas.repec.org/p/jhu/papers/480.html

**Comment by JohannesPfeifer** [comment]
People can easily do this with http://www.sciencedirect.com/science/article/pii/S0165188915000317
