### ISSUE TITLE
is tests/reporting/example1.mod syntax up to date? Is the test necessary?

### ISSUE THREAD

**Issue by houtanb** [DynareTeam/dynare#1111]

**Comment by houtanb** [comment]
@MichelJuillard , the syntax in this `.mod` file seems ok. What's more, I included it because it's a good example of using the macroprocessor with `dates`, `dseries`, and `reporting` in a `.mod` file as opposed to in a `.m` file. Note that, for example, the dates are typed in directly as opposed to being encloded in `dates('')`.

That said, it's true that it doesn't test anything new (other than the substitution of `dates('')` by the preprocessor. If you're ok with it, I can move this to the `examples` folder, replacing the `example1.mod` there.

**Comment by MichelJuillard** [comment]
Thanks @houtanb. I would move it to example but call it *example1_reporting.mod*. I think it is good to have a very simple example to do one very basic thing and nothing else.
