### ISSUE TITLE
Make Dynare compatible with Octave 4.2

### ISSUE THREAD

**Issue by JohannesPfeifer** [DynareTeam/dynare#1113]
Requires among other things dealing with the mex-files, see http://www.dynare.org/phpBB3/viewtopic.php?f=1&t=7570

**Comment by SamuelDelpeuch** [comment]
Hi !
Is it possible to make Dynare compatible with Ocatve 4.0 by dealing with the mex-files ? Or not, as written [http://www.dynare.org/phpBB3/viewtopic.php?f=1&t=7570](url) ? Do I need to remove Octave4.0 and get an older version to make it work ?

Thanks

**Comment by MichelJuillard** [comment]
Octave for Windows is discussed at http://wiki.octave.org/Octave_for_Microsoft_Windows#Octave-4.0.2
Official 32 bit builds are available at https://ftp.gnu.org/gnu/octave/windows/ 
unofficai binary for 64 bits are available at http://www.tatsuromatsuoka.com/octave/Eng/Win/
They are mingw based. We should find in the distributions the libraries necessary to make Dynare mex files.

**Comment by JohannesPfeifer** [comment]
Under Windows, everything seems to be working properly. Closing the ticket
