### ISSUE TITLE
Fix compilation flags in the build system

### ISSUE THREAD

**Issue by stepan-a** [DynareTeam/dynare#1121]
Compilation flags (```CFLAGS``` and ```CXXFLAGS```) specified with the ```configure``` script are not passed correctly when building the mex files (the preprocessor and dynare++ honour the flags). So the mex files are always compiled with debug symbols and it is not possible to use more aggressive optimizations (ie ```-O3```).

**Comment by houtanb** [comment]
@stepan-a have you tried using `MATLAB_CFLAGS` and `MATLAB_CXXFLAGS`?

**Comment by houtanb** [comment]
@stepan-a The mex files are compiled with the flags specified in `m4/ax_mexopts` which come from the Matlab distribution itself (see `mexopts.sh`). From what I understand, it's not a good idea to change these options as our mex files are compiled against the Matlab mex libraries.

**Comment by stepan-a** [comment]
@houtanb I just want to remove the debug symbols and raise the optimization level, this cannot be a problem for Matlab. Besides, we already change the default options when we pass the flag for openmp (which works as expected).

**Comment by houtanb** [comment]
I decided to add the `MATLAB_MEX_*` options **after** the related `MATLAB_*` option as `gcc` (is supposed to) choose the option that comes last in the command line when two or more conflicting options are encountered. Furthermore, it was messy to overwrite the `MATLAB_*` option as you would then need to add in necessary flags (e.g. `-I`, `-L`).
