### ISSUE TITLE
Extended Path disagreeing with OccBin and DynareOBC on linear models

### ISSUE THREAD

**Issue by tholden** [DynareTeam/dynare#1128]
DynareOBC contains tests which solve the same otherwise linear model with the Extended Path, OccBin, and with DynareOBC. OccBin and DynareOBC agree (up to the order of 10^(-8)), but the extended path is way off (e.g. responses 10 times larger).

(It's just possible that there's something up with my version of Dynare, but the fact that running `git diff upstream/master -- matlab/ep/` produces no output suggests that this probably isn't the problem at least.)

The tests are in this folder: https://github.com/tholden/dynareOBC/tree/master/Tests/ComparisonOfPerfectForesightSolutionsForLinearModels

You could just compare OccBin vs ExtendedPath by commenting out the appropriate lines of RunAllAndCompare.m, saving you the trouble of setting up DynareOBC.

**Comment by stepan-a** [comment]
Thanks for reporting this @tholden.  I will try to run your tests this week-end. I do also observe unexplained significant differences in volatility when I compare extended path with PEA (using an RBC model). So there is probably something to fix on our side.
