### ISSUE TITLE
Metropolis: add adaptive hybrid MCMC

### ISSUE THREAD

**Issue by sebastien-villemot** [DynareTeam/dynare#113]
See Ingvar Strid & Paolo Giordani & Robert Kohn “Adaptive hybrid MCMC for
DSGE models” (2010) presented at the Dynare Conference 2010.

**Comment by JohannesPfeifer** [comment]
I don't see the resources to do this and would recommend closing the ticket

**Comment by MichelJuillard** [comment]
OK
