### ISSUE TITLE
auxiliary variables in steady state and static model

### ISSUE THREAD

**Issue by MichelJuillard** [DynareTeam/dynare#1133]
Currently, in static model and set_auxiliary_variables.m, auxiliary variables may appear in the RHS of equations. This is problematic for two reasons:
 1. assignments may not be recurice in set_auxiliary_variables.m which leads to errors
 2. <fname>_static.m may not be solved independently from set_auxiliary_variables.m

In the static deterministic model, any auxiliary variable, except Lagrange multipliers for Ramsey policy, can be replaced with an expression using only original variables.

In the preprocessor, I want to rewrite <fname>_static.m  and <fname>_set_auxiliary_variables.m along these lines.

I expect this changes to solve #1119 and #633

**Comment by JohannesPfeifer** [comment]
This has been closed by #1150

**Comment by houtanb** [comment]
For future notice, the changes for this issue began with 5199638b3a23fa226bbad5e03e7bea68f5bdaaf6
