### ISSUE TITLE
derivation with respect to the parameters

### ISSUE THREAD

**Issue by MichelJuillard** [DynareTeam/dynare#1150]
When modifying <fname>_static.m in order to address problems with auxiliary variables (see #1133), I realized that the creation of <fname>_params_derivs.m and the code for analytical derivatives of the likelihood function assume that the static model is the static version of the <fname>_dynamic, equation by equation.
This is not obvious in the preprocessor where the static model is stored and handled in a different tree and it stops me to find an efficient solution to the computation of the steady state of auxiliary variables.
For this reason, I will introduce two files for the computation of the derivatives with respect to the parameters: <fname>_params_derivs_static and <fname>_derivs_dynamic
I will also change all calling sequences throughout the code

**Comment by MichelJuillard** [comment]
@rattoma could you please confirm that it is a bug not to have any entry for row 3 of rp in ./tests/fs2000/fs2000_analytic_derivation_params_deriv.m ?

**Comment by JohannesPfeifer** [comment]
@MichelJuillard I think the row of zeros is actually correct. Judging from the _static_model-file, the third equation

```-P/(c(+1)*P(+1)*m)+bet*P(+1)*(alp*exp(-alp*(gam+log(e(+1))))*k^(alp-1)*n(+1)^(1-alp)+(1-del)*exp(-(gam+log(e(+1)))))/(c(+2)*P(+2)*m(+1))=0; ```

becomes two equations by introducing an auxiliary variable ``` AUX_ENDO_LEAD_65 ```, where equations (3) and (15), respectively, are (of course all time indices must be dropped):

```
-P/(c(+1)*P(+1)*m)+AUX_ENDO_LEAD_65=0;
AUX_ENDO_LEAD_65=bet*P(+1)*(alp*exp(-alp*(gam+log(e(+1))))*k^(alp-1)*n(+1)^(1-alp)+(1-del)*exp(-(gam+log(e(+1)))))/(c(+2)*P(+2)*m(+1));
```

As you can see, there is no parameter appearing in the first equation, resulting in a row of zeros when taking the derivative.

**Comment by MichelJuillard** [comment]
Thanks @JohannesPfeifer
