### ISSUE TITLE
Investigate crash of Octave under Windows

### ISSUE THREAD

**Issue by JohannesPfeifer** [DynareTeam/dynare#1154]
There are two problems with the following mod-file under Octave

```
var ygap pinf i  u p a r_nat;
varexo eu ea;
parameters csigma cbeta crhou ckappa cweightygap crpinf cry clambda cepsilon ctheta cphi crhoa calfa;

csigma = 1.0;
cbeta = 0.99;
crhou = 0.8           ; 
cweightygap = .1;
crpinf = 1.5;
cry = 0.125;
cepsilon = 6;
ctheta = 2/3;
calfa = 0.33;
cphi = 1;
clambda = (1-ctheta)*(1-ctheta*cbeta)/ctheta *(1-calfa)/(1-calfa+calfa*cepsilon);
ckappa = clambda*(csigma+(cphi+calfa)/(1-calfa));
calphax = ckappa/cepsilon;
crhoa =0.9;

model(linear); 
ygap = ygap(+1) - (1/csigma)*(i-pinf(+1) - r_nat);
pinf = cbeta*pinf(+1) + ckappa*ygap + u;
u = crhou*u(-1) + eu;
p=p(-1)+pinf;

// the exogenous processes for productivity
a = crhoa*a(-1) + ea;
// the process for the natural rate can be derived from the flexible economy solution
r_nat = csigma*(1+cphi)/((1-calfa)*csigma+cphi+calfa)*(crhoa-1)*a;
end; 

shocks;
var eu; stderr 1;
var ea; stderr 1;
end;

// ramsey
planner_objective(ckappa/cepsilon*ygap^2+pinf^2);
ramsey_policy(planner_discount=0.99,order=1,instruments=(i),irf=12);


```

First of all, when no mex-files are present, `mjdgges.m` returns very different results than Matlab or the mex-file. While Octave then returns a rank failure, Matlab finds a small, but OK condition number and continues.

Second, when using the mex-files, Dynare crashes Octave 3.8.2 when computing theoretical moments. The culprit is the call to `ordschur.oct` in `lyap_symm`. The attached files allow to reproduce the error:
[crash_octave.zip](https://github.com/DynareTeam/dynare/files/193860/crash_octave.zip)
My guess is that the problem stems from `p`, which has a unit root and therefore non-finite second moments. This seems to be incorrectly handled.

**Comment by MichelJuillard** [comment]
This example runs fine in Linux with Octave 4.01. As far as Windows is concerned I suggest to focus on Octave 4 and not to try to fix problems with Octave 3.8

**Comment by JohannesPfeifer** [comment]
@MichelJuillard That would be fine with me. But we do not have mex-files for Octave 4.01 yet, so I cannot check whether the file runs. Does the file crash older Octave versions on Linux?

**Comment by JohannesPfeifer** [comment]
@MichelJuillard And did you check whether ```ordeig.mex``` correctly works?

**Comment by MichelJuillard** [comment]
@JohannesPfeifer I don't have older versions of Octave and can't look for them in the near future. Any way, we don't plan to support but the latest Octave version.

The *.mod file ran as in Matlab until the end, so I guess that ordschur rand OK, but I didn't test it specially.

**Comment by JohannesPfeifer** [comment]
@MichelJuillard That's fine. I was only interested because it might make debugging easier in case the problem persists under Windows with Octave 4.01.

**Comment by stepan-a** [comment]
The second problem does not pop up with Octave 4.2.1 (I did not try with 4.2.0), but we still have the rank failure error if we do not use the mex file.

**Comment by stepan-a** [comment]
... And I do not see how we could fix the condition number issue in Octave's implementation of `linsolve`.

**Comment by JohannesPfeifer** [comment]
@stepan-a Is this a bug in Octave?

**Comment by stepan-a** [comment]
@JohannesPfeifer Sorry I closed the issue inadvertently. I do not know if this is a bug or a change of behaviour in Octave. Digging further, it seems that the problem comes from the call to `qz`. If I remove the part specific to Octave in `mjdgges.m` your mod file runs smoothly and I obtain the same results with matlab or with the mex file (I checked with other mod files). But in this case the generalized eigenvalues are real. If the problem has complex generalized eigenvalues the output of check is obviously different.

**Comment by JohannesPfeifer** [comment]
@stepan-a I filed a bug report with Octave: https://savannah.gnu.org/bugs/index.php?50846

**Comment by stepan-a** [comment]
@JohannesPfeifer I have found a fix. Now I am able to run your example, and obtain correct results. I will push the fix this week-end. Basically I removed all the lines specific to Octave in `mjdgges.m`, as I said earlier, but I force the complex QZ factorization by converting `e` and `d` into complex matrices. Without this transformation the generalized eigenvalues returned by Octave are plain wrong.

**Comment by stepan-a** [comment]
@JohannesPfeifer ad21612967f41a60be01994d7423ca3893e11dc6 fixes the issue on Linux. Can you try on Windows ?

**Comment by JohannesPfeifer** [comment]
@stepan-a Yes, that did the trick. Should we add the call to `mjdgges.m` with the `e` and `d` of this mod-file as a unit test for this function?

**Comment by stepan-a** [comment]
@JohannesPfeifer Okay. I can add a unit test, to test the number of stable eigenvalues and the rank condition. I don't think that it would be wise to build a test on the values of the eigenvalues (which can be very imprecise when they are far from one). I close this issue and open another for the unit test (assigned to me).
