### ISSUE TITLE
Fix selected_variables_only option

### ISSUE THREAD

**Issue by JohannesPfeifer** [DynareTeam/dynare#1161]
In Dynare 4.4.3, we have in ```dynare_estimation_1 ```
```
    for i=bayestopt_.smoother_saved_var_list'
        i1 = dr.order_var(bayestopt_.smoother_var_list(i));
        eval(['oo_.SmoothedVariables.' deblank(M_.endo_names(i1,:)) ' = ' ...
                            'atT(i,:)'';']);
```
But ```bayestopt_.smoother_saved_var_list ``` only saves the index of the variable in ``` bayestopt_.smoother_var_list ```, not in the decision rules themselves. Therefore, we have to select ```atT(bayestopt_.smoother_var_list(i),:) ``` instead of ```atT(i,:) ``` if ```bayestopt_.smoother_var_list ``` is not equal to ```bayestopt_.smoother_saved_var_list ```, which happens with ```selected_variables_only ``` 
In master the same problem has been ported to ```write_smoother_results ```

@MichelJuillard @stepan-a Should we try to fix this or should we get rid of the ```selected_variables_only ``` option?

**Comment by MichelJuillard** [comment]
The ability of selecting variables is important for large models. We want to keep the feature and fix it

**Comment by JohannesPfeifer** [comment]
@MichelJuillard But are large models ever estimated with ML? Regardless, I think I have fixed the issue in the above mentioned commit, but I still have to test it more.

**Comment by MichelJuillard** [comment]
@JohannesPfeifer some parameters of a large model can be estimated, computing posterior mode and even posterior distribution with MH. SmoothedVariables and forecast are routinely computed for large calibrated models.

**Comment by JohannesPfeifer** [comment]
@MichelJuillard Ok. I missed the calibrated smoother part. MH is not affected by the ```selected_variables_only ``` option.

**Comment by MichelJuillard** [comment]
Computing the posterior distribution of smoothed variables (and friends) can generate memory problems for large models. It is very important to be able to limit the number of variables for which we compute and store the smoothed values.

**Comment by JohannesPfeifer** [comment]
@MichelJuillard To clarify. The manual says for ```selected_variables_only ```:
```
Only run the classical smoother on the variables listed just after the estimation
command. This option is incompatible with requesting classical frequentist forecasts
and will be overridden in this case. When using Bayesian estimation, the
smoother is by default only run on the declared endogenous variables.
```

**Comment by JohannesPfeifer** [comment]
There seems to be a second bug. In ```DsgeSmoother```, we select the observables via a matrix ```Z``` that relies on ```bayestopt_.mf = bayestopt_.smoother_mf ```
But ```bayestopt_.smoother_mf ``` only stores the indices of the observed and requested variables within ```bayestopt_.smoother_var_list ```, not within the actual state vector. Thus, it should be 
```bayestopt_.mf = bayestopt_.smoother_var_list(bayestopt_.smoother_mf) ```
as otherwise the selected observables change when the ```selected_variables_only ``` option is used
