### ISSUE TITLE
stochastic_solvers calls transition_matrix without passing M_

### ISSUE THREAD

**Issue by tholden** [DynareTeam/dynare#1165]
transition_matrix optionally takes M_ as an additional argument. If it doesn't get the extra argument, then it uses the global M_.
Given that stochastic_solvers takes M_ as an additional argument, it should also pass this to transition_matrix.
Without this, user code that calls Dynare internals in parallel can be messed up.

**Comment by MichelJuillard** [comment]
calls to transition_matrix have been replaced by calls to kalman_transition_matrix that doesn't use global variables in e8c430a9232a4732c9dfd04fd47bed92c7ecdeaf
