### ISSUE TITLE
Investigate crash in sim1_linear.m

### ISSUE THREAD

**Issue by JohannesPfeifer** [DynareTeam/dynare#1176]
The following mod-file crashes Dynare in master
```
var pi y  pi_annual;
varexo x;

parameters kappa beta sigma lambda rho phi_pi phi_y;
kappa=.025;
beta=.995;
sigma=1;
lambda=1;
rho=.8;
phi_pi=1.5;
phi_y=.5;


model(linear);
pi =(kappa/(1+beta*lambda))*(-1/sigma*x+1/kappa*pi(+1)-beta/kappa*pi(+2)+1/sigma*beta*pi(+1))+(beta/(1+beta*lambda))*pi(+1)+(lambda/(1+beta*lambda))*pi(-1);
x=sigma*(y(+1)-y)+pi(+1);
pi_annual=4*pi;
end;


shocks;
var x;
periods 1:1;
values -0.005;
end;

simul(periods=1);
```
Setting periods bigger than 1 solves the issue.

**Comment by stepan-a** [comment]
@JohannesPfeifer But why one would want to simulate a perfect foresight model with only one period? I suppose we should not allow ```periods=1```.

**Comment by JohannesPfeifer** [comment]
@stepan-a It is a limit case taken from a recent JME paper. The goal is to solve for the endogenous variables in this one period, given the exogenous variable as well as terminal and initial conditions. I don't think this question is ill-posed.

**Comment by stepan-a** [comment]
@JohannesPfeifer Is it reasonable to assume that the economy is back to steady state in one period? Can you post the reference of the paper? Do they try to compute the steady state conditional on a particular value of the exogenous variables?

**Comment by JohannesPfeifer** [comment]
@stepan-a The model is a New Keynesian model without endogenous states. In normal times, i.e. the initial and terminal periods, divine coincidence holds and everything is in steady state (x and all endogenous variables are 0). However, in period 1, the endogenous one, the central bank deviates from the Taylor rule and just exogenously sets the interest rate. The question is what happens to the inflation in the model during intermittent time periods. Of course, complications arise with when having a hybrid Phillips Curve as in the above mod-file, but this is not important for just wanting to solve for one period.

**Comment by stepan-a** [comment]
@JohannesPfeifer Okay. If there is no lag in the model, the variables return to the steady state in one period. In this case it makes sense to put ```periods=1```, because we would have exactly the same solution for any value of ```periods``` greater than one (the solution of the linear model is a multivariate  white noise). Otherwise, the response in period one would be influenced by the fact that the economy is forced to return to the steady state in one period. I do not see how we would then interpret the results. Did you check if dynare fails with ```periods=1``` when the linear model has lo lags?

**Comment by JohannesPfeifer** [comment]
@stepan-a Without lags, it works with ```periods=1 ```, which suggests we simply need a more informative error message. But I still don't understand where the crash comes from. What distinguishes  ```periods=1 ``` from  ```periods=2 ```

**Comment by stepan-a** [comment]
@JohannesPfeifer Thanks. I need to run the example, but I cannot do it this week...

**Comment by JohannesPfeifer** [comment]
@stepan-a No hurry, please just set the bug label and a milestone so wo do not forget it.

**Comment by stepan-a** [comment]
@JohannesPfeifer I only add the enhancement label, because it's not clear to me if this issue is really a bug...

**Comment by JohannesPfeifer** [comment]
@stepan-a If it crashes without a proper exception handling, it should be classified as a bug.

**Comment by stepan-a** [comment]
Looking at other parts of the code, I have the impression that the same
issue will pop up with other solvers (for nonlinear or linearized models). I am still not convinced that we should deal with this case (```periods=1```).

**Comment by MichelJuillard** [comment]
I would prefer that the code be robust to periods=1. But, it is not urgent to verify all solvers

**Comment by stepan-a** [comment]
@MichelJuillard How do you interpret the results in this case (if the model has lags)?

**Comment by JohannesPfeifer** [comment]
@stepan-a In models with lags most of the time it is unreasonable to assume one is back in steady state within 1 period. But the same can be true for models with large persistence for any specified `periods`. It is always the user's duty to assure he has chosen the number of periods sufficiently large. 1 should therefore be treated as any other natural number. There might be valid applications. However, what I do not know is whether one really needs to support various `stack_solve_algo` for this type of problem. One-period problems presumably are rather small-scale and should easily work with the default. In this case, we might simply trap the error and indicate the  `stack_solve_algo` that works

**Comment by stepan-a** [comment]
@JohannesPfeifer I think that it will be simpler to have a consistent behaviour across the different implementations. I open an issue for that.
