### ISSUE TITLE
Implement interface for posterior sampling methods

### ISSUE THREAD

**Issue by JohannesPfeifer** [DynareTeam/dynare#1177]
Related to #1174 and #1065 

I would propose to use this occasion to further clean up the ```options_```-structure and create a field ```options_.posterior_sampler_options``` that stores as subfields the various options. 

The preprocessor should have an option ```posterior_sampling_method``` that accepts a quoted string that can be ```slice```, ```random_walk_metropolis_hastings```, ```independent_metropolis_hastings``` or ```tailored_random_block_metropolis_hastings```

It should map into ```options_.posterior_sampler_options.posterior_sampling_method``` with default 
```random_walk_metropolis_hastings```, which replaces the current ```options_.posterior_sampling_method```
In addition:

1. We need a subfields ```options_.posterior_sampler_options.tarb```, ```options_.posterior_sampler_options.rwmh```,```options_.posterior_sampler_options.slice```, 
    and ```options_.posterior_sampler_options.imh``` that store the default options for the respective sampler as we already do for different mode_computes.

2. We need the preprocessor to accept name/value pairs like in the already existing ```optim```-option in the form of ```posterior_sampler_options = (NAME, VALUE,...)```. 
    It should map into a string ```options_.posterior_sampler_options.sampling_opt```, which can then be read out using ```read_key_value_string``` as we already do in ```dynare_minimize_objective```.

3. The already existing but undocumented options ```options_.proposal_distribution``` and ```options_.student_degrees_of_freedom``` should now become sampler-specific subfields of the fields introduced in  1.

**Comment by rattoma** [comment]
@JohannesPfeifer thanks a lot for this. If I understand correctly, `options_.posterior_sampler_options.sampling_opt` should be dealt with in `check_posterior_sampler_options.m` with `read_key_value_string`, so to fill the appropriate subfields in 1. 

This looks a good solution to me. 

One further note aside. As you may have noted, I also factorized a few more implicit options that were hard coded in previous rwmh etc., namely (e.g. for RWMH):
``
    posterior_sampler_options.parallel_bar_refresh_rate=50;
    posterior_sampler_options.serial_bar_refresh_rate=3;
    posterior_sampler_options.parallel_bar_title='MH';
    posterior_sampler_options.serial_bar_title='Metropolis-Hastings';
``
in my view these refresh rates/titles can be kept hard-coded as sampler specific fixed options [essentially the depend on the cost the the individual sampler iteration], without allowing  users setting them in `estimation`.

I need to provide a list of options for slice.

**Comment by JohannesPfeifer** [comment]
A separate function like ```check_posterior_sampler_options``` seems to be the right place, although I would probably name it ```set_posterior_sampler_options```. I would also not allow users to reset the implicit options for the bar graphs, but make them sampler-specific.
@rattoma A list of options for slice should be easily derivable from ```check_posterior_sampler_options```. If you comment the options, documenting them for the manual should be easy. I can do this after merging the slice pull request when moving the setting of TaRB options to the ```check_posterior_sampler_options``` file.
If @stepan-a agrees, @houtanb could start with the implementation.

**Comment by rattoma** [comment]
@JohannesPfeifer. thank you. I applied and pushed on my slice branch your patch regarding TaRB.
I will add comments to  `check_posterior_sampler_options` and commit/push them to my personal slice branch.

**Comment by rattoma** [comment]
@JohannesPfeifer I just pushed comments for slice options

**Comment by stepan-a** [comment]
@houtanb Can you look into this, please?

**Comment by rattoma** [comment]
@JohannesPfeifer: working on provisions for preprocessor extentesion done by @houtanb, I have an issue: 

when using `set_posterior_sampler_options` / `check_posterior_sampler_options` we get the default options in subfields `options_.posterior_sampler_options.tarb` etc...
the current implementation of `posterior_sampler` reads options from a structure `posterior_sampler_options` without subfields.
To avoid to have some options to be read in `options_.posterior_sampler_options` and others in subfields of it, I would package all options in a local [not global] `posterior_sampler_options` that will be prepared by `check_posterior_sampler_options` in `dynare_estimation_init` and passed to `posterior_sampler`. This packaging will combine default options  + user defined ones.
Was this also your idea ?

**Comment by JohannesPfeifer** [comment]
@rattoma I did not think that far actually. This is a very elegant solution. I would make that structure local to the functions that use it, but make it global in '''dynare_estimation_1.m''' like the other structures so users can latter access and check it.

**Comment by rattoma** [comment]
@JohannesPfeifer what about using `estimation_info` for the global storage of these options, or defining another `options_` field like `posterior_sampler_opts` or `sampling_options`?
I am not sure whether to put everything in `posterior_sampler_options` which would then mix the method specific default subfield and the merged wrapped set of options ...
what do you think?

**Comment by rattoma** [comment]
perhaps we could use a wrapped field `options_.posterior_sampler_options.sampling_options`

**Comment by JohannesPfeifer** [comment]
@rattoma I would go for the wrapped field in your last post as it keeps all info in one place

**Comment by rattoma** [comment]
@JohannesPfeifer @houtanb et al: am I right that `use_mh_covariance_matrix` is an undocumented option of dynare, which is not recognized by the pre-processor?

**Comment by houtanb** [comment]
@rattoma you are correct

**Comment by rattoma** [comment]
@JohannesPfeifer I pushed on my personal slice branch provisions for reworked poserior sampler options + patches on tabular output and IFAC documentation

**Comment by JohannesPfeifer** [comment]
Closed by #1188
