### ISSUE TITLE
Fix cross-compilation of Dynare++ for Windows

### ISSUE THREAD

**Issue by JohannesPfeifer** [DynareTeam/dynare#1179]
With the unstable version under Windows 10 I get an error that `libquadmath-0.dll` is missing, while Dynare 4.4.3 still works.

**Comment by tholden** [comment]
This is closely related to the issue I submitted here, then retracted: https://github.com/DynareTeam/dynare/issues/1203
You may fix it by copying https://github.com/tholden/dynare/blob/master/mex/matlab/win64-7.8-9.0/libquadmath-0.dll to the corresponding folder.

**Comment by houtanb** [comment]
We should install the `fortran` package from `mingw` and statically link `libquadmath-0.a` from there. However, I don't see how `mingw` was installed on `karaba` and only see the library files in `/usr/local/lib/` without the corollary binary files....

**Comment by MichelJuillard** [comment]
@houtanb the cross-compiler is a Debian package

**Comment by houtanb** [comment]
@MichelJuillard it does not seem to be the case because the libraries are in `/usr/local`. They seem to have been installed from the `.zip` file that is in the same directory. Furthermore `which mingw-get` yields nothing.

**Comment by stepan-a** [comment]
Moved to issue [#3](https://github.com/DynareTeam/dynare-build/issues/3) in [dynare-build](https://github.com/DynareTeam/dynare-build) project.
