### ISSUE TITLE
Fix compatibility with matlab 2016a in installer and mex-folder

### ISSUE THREAD

**Issue by stepan-a** [DynareTeam/dynare#1183]
I had to revert commit 6072aa0b462484da990ffa00ee39fb141fa9513f (which is PR #1144 by @JohannesPfeifer) because the snapshot build failed this evening. The generated mex files are not saved in the expected directory. They are saved in ```mex/matlab/win64-7.8-8.6``` instead of ```mex/matlab/win64-7.8-9.0```. I did not find where the name of this directory is controlled. @houtanb can you fix this?

**Comment by houtanb** [comment]
@stepan-a this is done by the script that runs the snapshots. I'll take care of it.

**Comment by stepan-a** [comment]
This is what I thought, but I didn't find the line where this is done in the main script...

**Comment by houtanb** [comment]
It's in `/usr/local/bin/make-dynare-win-unstable`

**Comment by stepan-a** [comment]
Thanks @houtanb! I will change this when porting the build of the snapshot elsewhere.
