### ISSUE TITLE
Crash in preprocessor in unstable branch

### ISSUE THREAD

**Issue by rattoma** [DynareTeam/dynare#1184]
I get a crash in the preprocessor in the unstable branch, since I rebased my local unstable branch onto the recent commits [pervious preprocessor versions I used date back October 2015 ...] when dealing with our Global Multicountry model. 

I get the error both in Windows and MacOS.

In MacOS I get the following message:
``
dynare_m(554,0x7fff7411b300) malloc: 
``
``
*** error for object 0x7fda6a60ccd0: pointer being freed was not allocated
``
``
*** set a breakpoint in malloc_error_break to debug
``

apparently what triggers the error is the use of `trend_var` and `deflator` instructions.
When I filter out detrending, pre-processing completes.

I can share a replication package privately.

with older versions of the unstable preprocessor everything went fine.

**Comment by houtanb** [comment]
Yes, please tell me how to get the files necessary to replicate the problem. @MichelJuillard made some changes recently, so we need to work out all bugs before the release.

**Comment by MichelJuillard** [comment]
Hi Marco,

can you send me the replication case please?

Best

Michel

Marco Ratto writes:

> I get a crash in the preprocessor in the unstable branch, since I rebased my local unstable branch onto the recent commits [pervious preprocessor versions I used date back October 2015 ...] when dealing with our Global Multicountry model. 
>
> I get the error both in Windows and MacOS.
>
> In MacOS I get the following message:
> ``
> dynare_m(554,0x7fff7411b300) malloc: 
> ``
> ``
> *** error for object 0x7fda6a60ccd0: pointer being freed was not allocated
> ``
> ``
> *** set a breakpoint in malloc_error_break to debug
> ``
>
> apparently what triggers the error is the use of `trend_var` and `deflator` instructions.
> When I filter out detrending, pre-processing completes.
>
> I can share a replication package privately.
>
> with older versions of the unstable preprocessor everything went fine.
>
>
> ---
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/DynareTeam/dynare/issues/1184


-- 
Michel Juillard

**Comment by rattoma** [comment]
I am sending an email

**Comment by JohannesPfeifer** [comment]
@rattoma Do you have a minimal working example to use as a unit test? It seems we currently don't have any test to trigger this issue.

**Comment by rattoma** [comment]
@JohannesPfeifer I'll try to set up something for a unit test.
