### ISSUE TITLE
allow to skip 2nd order param derivs

### ISSUE THREAD

**Issue by rattoma** [DynareTeam/dynare#1187]
For large models, computing the analytic Hessian just produces a too big `_params_derivs.m` file which is untractable.
For running identification or only computing scores, 2nd order derivs would be useless. 
@houtanb  Would it be possible to tell the pre-processor to only compute 1st order derivatives, i.e. stop writing the `param_derivs` file when it reaches
`if nargout >= 3 ...`
?
2nd order terms could be just defined as empty, and routines (`dsge_likelihood`) possibly asking for 2nd order ones will trap this and just stop.

**Comment by houtanb** [comment]
@rattoma yes. Can you send me a `.mod` file that's giving you problems so I can test the changes I make?

**Comment by rattoma** [comment]
@houtanb I'll do it

**Comment by rattoma** [comment]
@houtanb I just sent you a private email

**Comment by rattoma** [comment]
@houtanb thank you so much! 
The solution you propose is that, when running identification, only 1st derivs are computed, while when analytic_derivation is triggered in estimation, all derivs up to 2nd order are still provided. 
This should fix the main issues I normally face. I still need to test this, but I am wandering whether it would also be useful/possible to allow a bit more control on this, by adding a dynare option like 

`dynare <mod-file> no_2nd_order_params_derivs`   

but I am not sure how much work would this imply.

**Comment by houtanb** [comment]
Sure @rattoma I can do that. Do you want this to be the default for identification or do you want users to have to pass the option to dynare?

**Comment by houtanb** [comment]
@rattoma I made it the default for identification such that with identification you cannot obtain the 2nd derivative of the jacobian or the derivative of the hessian wrt the params. If you would like this default to be changed, please let me know.

**Comment by rattoma** [comment]
this looks okay, unless with testing I step into some error/problem. thanks a lot!

**Comment by rattoma** [comment]
@houtan thinking more carefully about the issue I think it would be better to keep the default with 1st and 2nd order derivs even for identification, otherwise there would not be an option to get it. Hence, let's skip 2nd order only when explicitly required by the user with `no_2nd_order_params_derivs` [computing the Hessian might be useful in any case, there are papers around that use the Hessian to assess some weak identification issues]

**Comment by rattoma** [comment]
@houtan sorry for bothering again on preprocessor issues around identification.
Would it be possible to add the following options for identification [currently they are set automatically in identification to default but cannot be forced to different values by the user]
`analytic_derivation`
`analytic_derivation_mode`
Moreover, concerning params derivs, the most flexible option would be, if possible, to set the explicitly the order, with an option:
`params_derivs_order = [0, 1 or 2]`
0 = no params derivs from preprocessor
1 = 1st order params derivs
2 = 1st and 2nd order params derivs
and eliminating `no_2nd_order_params_derivs`. apologies for re-iterating on this.

**Comment by houtanb** [comment]
@rattoma so you want to have this option to `identification`. For `estimation` no option?

**Comment by houtanb** [comment]
@rattoma what are valid values for `analytic_derivation_mode`? Integers? Positive Integers? Positive Integers and Zero?

**Comment by rattoma** [comment]
@houtanb integers [can be negative and positive]. Since identification can also be triggered via sensitivity, I think we should add this to sensitivity as well. many thanks

**Comment by rattoma** [comment]
On the error in testsuite, I messed up things...
On the testsuite error of tonight: it seems that `analytic_derivation` in `estimation` does no longer trigger `params_derivs` in preprocessor. This should not change w.r.t. the past.
The option
`params_derivs_order=INTEGER`
should be a pre-processor option, just extending the previous `no_2nd_order_params_derivs`
i.e.
`dynare <mod-file> params_derivs_order=0|1|2`

The point for identification/sensitivity is that it was automatically set with identification without having the option to skip it, e.g. when the model is too big.
