### ISSUE TITLE
Make preprocessor recognize state variables introduced by optimal policy

### ISSUE THREAD

**Issue by JohannesPfeifer** [DynareTeam/dynare#1193]
In the mod-file

```
var pai, c, n, r, a;
varexo u;
parameters beta, rho, epsilon, omega, phi, gamma;

beta=0.99;
gamma=3;
omega=17;
epsilon=8;
phi=1;
rho=0.95;

model;
a = rho*a(-1)+u;
1/c = beta*r/(c(+1)*pai(+1));
pai*(pai-1)/c = beta*pai(+1)*(pai(+1)-1)/c(+1)+epsilon*phi*n^(gamma+1)/omega -exp(a)*n*(epsilon-1)/(omega*c);
exp(a)*n = c+(omega/2)*(pai-1)^2;
end;

initval;
r=1;
end;

histval;
a(0)=1;
r(0)=1;
end;

steady_state_model;
a = 0;
pai = beta*r;
c = find_c(0.96,pai,beta,epsilon,phi,gamma,omega);
n = c+(omega/2)*(pai-1)^2;
end;

shocks;
var u; stderr 0.008;
var u;
periods 1;
values 1;
end;
options_.dr_display_tol=0;
planner_objective(ln(c)-phi*((n^(1+gamma))/(1+gamma)));
ramsey_policy(planner_discount=0.99,order=1,instruments=(r));
```

`r` becomes a state variable during Ramsey computations (albeit with 0 coefficients). As a state, one should be able to set its lagged value using `histval`. But this is not possible, as the preprocessor does not recognize `r` as a state.

**Comment by stepan-a** [comment]
@houtanb, If you cannot do this quick (I have no idea of size of the patch) I propose to postpone this to the next version of Dynare. Please set a milestone in consequence.

**Comment by houtanb** [comment]
This is a bit of a patch because the error is encountered during parsing, which is out of the ordinary. So the change will be larger than usual. If I can get to it before the release, I'll do it. Otherwise, will wait.

**Comment by houtanb** [comment]
@JohannesPfeifer in this, should we only be able to set the histval for `r` at period `0`? i.e., `r(-1)` and `r(1)` would still yield errors?

**Comment by houtanb** [comment]
@JohannesPfeifer do you think this should be cherry-picked to the `4.5` branch or should we leave it on `master` to be released with `4.6`

**Comment by JohannesPfeifer** [comment]
I would classify this as a bug (as you did) and cherry-pick it.

**Comment by houtanb** [comment]
@JohannesPfeifer will do. However, even though it passed the test suite, it would reassure me, if you have the time, if you could check it to make sure it functions as expected (both when it should pass through and when it should end with an error)

**Comment by JohannesPfeifer** [comment]
@houtanb If I use `r(-1)=1;` in the histval block (which should trigger an error as that variable does not appear with a lag), I get 
```
HISTVAL: internal error of Dynare, please contact the developers
```
