### ISSUE TITLE
Check mode-file related options of slice

### ISSUE THREAD

**Issue by JohannesPfeifer** [DynareTeam/dynare#1199]
As discussed with @rattoma it is not clear the preprocessor can handle the necessary inputs which must be a set of vectors or an array of strings. We might need to delete the mode option from the manual and provide an example of the mode_files option

**Comment by stepan-a** [comment]
@JohannesPfeifer Can you elaborate on this? What is needed exactly?

**Comment by JohannesPfeifer** [comment]
I think you can assign this ticket to @rattoma. He knows what to do. As far as I understand it, the ```mode``` option is supposed to take a sequence of vectors like ```[x1 x2 x2]``` as an input. But it is not sure the preprocessor can handle this within the key-value combinations. Similarly, ```mode_files``` takes a character or cell array (not sure what Marco intended) as the value in the key-value pair. Above all, we need a test case, which @rattoma wanted to provide.

**Comment by rattoma** [comment]
mode_files is set properly in my last commit
3e8dbcfc7e4fbb87115b0a016a6a42089cb4039e
we need to use one single file name, so one single mat file that contains all multiple modes, one per column.

**Comment by houtanb** [comment]
@JohannesPfeifer @rattoma Just FYI, the preprocessor can accept a vector of vectors. See the `restrictions` option to `markov_switching` and the `variance` option to the `prior` command on a vector of parameters.

**Comment by rattoma** [comment]
@houtan would it be possible then to use a syntax like
`mode_files=['file1' 'file2' 'file3']`
?

**Comment by houtanb** [comment]
@rattoma not yet, but I can add it.

**Comment by rattoma** [comment]
ok. in fact we are here in the key-value context, so we are getting in a situation like the following

`posterior_sampler_options=('mode_files',['fs2000_slice_mh_mode' 'file2'])`

which currently I can only handle as follows:

`posterior_sampler_options=('mode_files','file2')`

hence the individual file must contain all info about all modes. I think this should be enough, without having you to struggle for allowing key-value to get multiple strings [unless this would be very easy].

**Comment by houtanb** [comment]
@rattoma I am a bit confused when you say 

> I think this should be enough, without having you to struggle for allowing key-value to get multiple strings

Can you provide an example of what you mean by this?

**Comment by rattoma** [comment]
@houtan the current solution to the problem is solved by the following syntax that is handled by the preprocessor:
`posterior_sampler_options=('mode_files','file2')`
This allows to provide a matrix of modes in a binary file `file2.mat`. Given this fix, there is no need to change anything.
I am wandering, however, if it would be easy and make sense in general [not for this specific purpose only] to extend the key-value context, enabling users to provide lists of char. but I would not see this as a priority. many thanks.

[by the way, a question: is it already doable to give arrays of numbers/integers in key-value format?]

**Comment by houtanb** [comment]
@rattoma yes, it is currently possible to provide arrays of numbers/integers. See, for example, the `geweke_interval` option to `estimation`
