### ISSUE TITLE
Provide Windows cross compilation instructions

### ISSUE THREAD

**Issue by tholden** [DynareTeam/dynare#1202]
I know building on Windows is no-longer supported. Still, building for Windows ought to be supported.

Thus, it would be a great help if there were e.g. a script for cross compiling for Windows from Linux.

The dependencies make this rather painful.

**Comment by stepan-a** [comment]
Obviously, we have such a script... But, because of the dependencies, it is running on only one machine at CEPREMAP. I want to make the system more portable, but it's a lot of work... I do not plan to do that before next year.

**Comment by tholden** [comment]
Well, it would be a help if you could at least share that script...
