### ISSUE TITLE
In the latest unstable, sparse_hessian_times_B_kronecker_C.mexw64 has a dependency on libgomp-1.dll

### ISSUE THREAD

**Issue by tholden** [DynareTeam/dynare#1203]
I was getting errors about missing dependencies. Running Dependency Walker on it revealed libgomp-1.dll as the problem. Copying this across from MinGW fixed the issue.

**Comment by stepan-a** [comment]
Strange, I thought we were compiling the snapshot and the windows package without parallelization.

**Comment by tholden** [comment]
Actually, no. I think this was a problem on my end. Apologies. (I had this problem with my build, copied across your build DLLs, and still got the same error. But MATLAB must have still had the old DLLs in memory.)
