### ISSUE TITLE
qz_criterium in estimation

### ISSUE THREAD

**Issue by rattoma** [DynareTeam/dynare#1215]
I think it would be useful to allow option `qz_criterium` also in estimation, similarly to simulation. Would it be possible? Is there any strong reason for not allowing this?

**Comment by JohannesPfeifer** [comment]
We allow setting it implicitly via the `diffuse_filter` option. We can allow for setting it separately, but need to assure consistency.

**Comment by rattoma** [comment]
The point is that if  `qz_criterium` is set to 1-1.e-6 [e.g. from stoch_simul] and afterwards we set `diffuse_filter` in estimation, `qz_criterium` is not re-set because it is not empty [in `dynare_estimation_init`].
We could simply remove the `if isempty` there?

**Comment by JohannesPfeifer** [comment]
@rattoma How about https://github.com/JohannesPfeifer/dynare/commit/6537335a1807fbf962ff98fc247c3750525a3406
