### ISSUE TITLE
Tabular output of variance decomposition after Bayesian MH estimation

### ISSUE THREAD

**Issue by BenjaminBorn** [DynareTeam/dynare#1219]
Dear all,

Johannes asked me to open this as an issue. Would it be possible to provide the output from the conditional variance decomposition after Bayesian estimation in tabular form?

Thanks,
Benjamin

**Comment by JohannesPfeifer** [comment]
@BenjaminBorn https://github.com/DynareTeam/dynare/pull/1207 will implement this, including TeX output. There will be one table per forecast horizon as is already the case after `stoch_simul`

**Comment by houtanb** [comment]
Reopening as this was fixed in the PR after this issue was created
