### ISSUE TITLE
Lower and upper bounds on priors used for two purposes

### ISSUE THREAD

**Issue by sebastien-villemot** [DynareTeam/dynare#122]
The p3 and p4 parameters of estimated_params are currently used for two distinct purposes:
- specifying the domain of definition of the prior (uniform, generalized beta and gamma)
- restricting the optimization for the posterior mode on a sub-domain of the definition of the prior

This double usage of the same values is confusing, and makes some cases impossible to describe in a MOD file (example: restricting the optimization on a subdomain of the interval of a uniform).

The fix is probably to distinguish these two usages in the MOD file by introducing a new syntax for restricting the optimization, and reflecting that change in the M code.

**Comment by JohannesPfeifer** [comment]
@stepan-a It appears to me that this issue is superseded by #750 and can be closed.
