### ISSUE TITLE
Support mingw-compiler on Windows

### ISSUE THREAD

**Issue by JohannesPfeifer** [DynareTeam/dynare#1226]
Since Matlab2014a, the `mexopts.bat` cannot be used anymore to set the mex-compiler to `cygwin`, rendering it pretty much useless for most recent versions. However, Mathworks now has a MinGW-addon (http://de.mathworks.com/help/matlab/matlab_external/install-mingw-support-package.html) that  we should support.
For this, we need to 
1. Allow for a `mingw` command line flag
2. Adjust `dyn_mex` with the respective case distinction and necessary flags
3. Update http://www.dynare.org/DynareWiki/ConfigureMatlabWindowsForMexCompilation

**Comment by tholden** [comment]
A few notes copied from issue: https://github.com/DynareTeam/dynare/issues/1260
 * The MinGW toolchain seems to work fine with the cygwin command line option, as one would expect.
 * To me it would make more sense just to rename the cygwin option to gcc. The same compiler options ought to work across GCC on Cygwin and GCC via MinGW.
 * Giving up on support for pre-2014a versions seems a bit premature, as I'm continually surprised by people attempting to run DynareOBC on ancient versions. So it would be better to have one option that supported both.
 * The steps to install a compiler should be documented in Dynare, and people should be strongly encouraged to install one. The following is the text included in the DynareOBC readme: "A working compiler for MEX which is supported by MATLAB Coder, ideally supporting OpenMP. On Windows, a free compiler meeting these requirements is available from: https://www.visualstudio.com/en-us/news/vs2013-community-vs.aspx . Alternatively, on Windows, with MATLAB r2015b, another free compiler meeting these requirements (which uses much less disk space) is available by clicking on "Add-Ons" in the MATLAB toolbar, then searching for MinGW. Be sure to untick the "check for updated files" in the installer that opens."

**Comment by JohannesPfeifer** [comment]
@houtanb Could you please do the additional command line flag `mingw`, I will have a look at `dyn_mex`

**Comment by houtanb** [comment]
@JohannesPfeifer please tell me if there are any problems with my commit. I couldn't test it as I don't have a Windows machine

**Comment by JohannesPfeifer** [comment]
@houtanb Sure, but I will only have the cross-compiled preprocessor in tomorrow's snapshot.

**Comment by houtanb** [comment]
@JohannesPfeifer so what remains is that you test this with a snapshot starting tomorrow. Please post here if it works or not.

**Comment by JohannesPfeifer** [comment]
@houtanb Will do. We also should have a test working with the supported new functions like `normcdf` and `asinh`.

**Comment by houtanb** [comment]
@JohannesPfeifer agreed if we ever get the testsuite running on Windows

**Comment by JohannesPfeifer** [comment]
@houtanb I will do. But this was a rather general comment. I don't think we have any tests in the testsuite that use "exotic" functions allowed in mod-files (be it with `use_dll` or not)

**Comment by JohannesPfeifer** [comment]
The test is in #1319 and works on my machine with the fix in #1259
