### ISSUE TITLE
Remove onlyclearglobals option

### ISSUE THREAD

**Issue by JohannesPfeifer** [DynareTeam/dynare#1232]
It was introduced in master, but is now redundant with the `clear all` command being removed due to Matlab's JIT

**Comment by stepan-a** [comment]
@JohannesPfeifer We still use ```clear all```command for Octave and matlab's versions older than R2015b. So I would keep the option.

**Comment by JohannesPfeifer** [comment]
@stepan-a I missed that. I will update the manual and then close the ticket
