### ISSUE TITLE
Check whether fast_kalman_filter is compatible with non-stationary states

### ISSUE THREAD

**Issue by JohannesPfeifer** [DynareTeam/dynare#1234]
From the Herbst (2015)-paper:
`This seems like a difficult problem, because the factorization is not obvious, and, in our
experience, even finding α consistently can be hard. Fortunately, the problem becomes
much easier once it is known that the states are stationary.`
In a nonstationary model I get a complex likelihood.

**Comment by rattoma** [comment]
yes. it does not work: the covariance matrix of the states becomes non positive definite after the first diffuse step.
If we know that the model is stationary or if, in `lik_init=3`, the actual number of diffuse steps is zero [i.e. the model has unit roots but observables are stationary], then fast KF can be run

**Comment by JohannesPfeifer** [comment]
@rattoma So we need to implement a check for this and document it

**Comment by JohannesPfeifer** [comment]
@rattoma But how is it then compatible with `kalman_algo=3`, when it requires the `diffuse_filter` to not actually be used?

**Comment by rattoma** [comment]
I think that one can use option `lik_init=3`, then if observables are stationary the rank of Pinf of the initialized covariance of the diffuse filter is zero, so diffuse filter exits with zero iterations and the Kalman filter runs from the first observation.

**Comment by JohannesPfeifer** [comment]
@rattoma But how would you implement the check in this case?

**Comment by rattoma** [comment]
what about, simply:       
 `elseif DynareOptions.fast_kalman_filter && diffuse_periods==0 `

?

**Comment by JohannesPfeifer** [comment]
But that would be a check in `dsge_likelihood` and therefore dependent on the parameter vector drawn. But as this is a general issue, I would prefer a check in `dynare_estimation_init`

**Comment by rattoma** [comment]
Unless we call the likelihood in `dynare_estimation_init` the only place we can do it is then in:
`initial_estimation_checks`
where we evaluate the likelihood and then, in `dsge_likelihood`, we trap it as:
``
elseif DynareOptions.fast_kalman_filter 
   if diffuse_periods
          error('Fast Kalman filter only works with stationary models [lik_init=1] or stationary observables for non-stationary models [lik_init=3]')
   end
``
?

**Comment by JohannesPfeifer** [comment]
Ok. Thanks. I will try that.
