### ISSUE TITLE
user_has_matlab_license

### ISSUE THREAD

**Issue by rattoma** [DynareTeam/dynare#1240]
Dynare checks license but for onsite licenses, toolboxes could be licensed but not installed on the current machine. This would be visible with `ver`, even if I am not sure of the overall behavior of ver ...

**Comment by JohannesPfeifer** [comment]
@rattoma what exactly is the problem you encounter. `ver` checks whether a toolbox is installed, but not whether you have a license. The `license` command does the opposite, checking whether you have a license, but not whether it is installed AND not whether a license can be checked out. Therefore we might need to test for the union of both.

**Comment by rattoma** [comment]
@JohannesPfeifer: yes I think the union of both tests would be better. I have situations here where the licence is OK but the package is not installed, so `ver` + `license` might be a better option.

**Comment by JohannesPfeifer** [comment]
@rattoma Could you please try https://github.com/JohannesPfeifer/dynare/commits/license_test
