### ISSUE TITLE
Add preprocessor interface for setting perfect foresight tolerance

### ISSUE THREAD

**Issue by JohannesPfeifer** [DynareTeam/dynare#1249]
Currently, one must manually set ```options_.dynatol.f```. I would suggest to use the name `TolFun` for the option. 
While we are at it, I would also suggest to use an option `TolFun` for the `steady` command to set `options_.solve_tolf`

**Comment by houtanb** [comment]
@JohannesPfeifer is this analagous to the `tolf` option to `osr`? If so, should we use `tolf` instead of `tolfun`?

**Comment by JohannesPfeifer** [comment]
@houtanb Yes, why not. In the context of `optim` we use `TolFun`, but following the logic of `osr` makes more sense.

**Comment by houtanb** [comment]
@JohannesPfeifer can you add the doc?

**Comment by JohannesPfeifer** [comment]
@houtanb Sure

**Comment by JohannesPfeifer** [comment]
@houtanb Could you please also provide `tolx` for perfect foresight, mapping into `options_.dynatol.x`

**Comment by JohannesPfeifer** [comment]
@houtanb We should also remove `tolf` and `maxit` from the `osr` interface, because we now use the `optim`-framework to pass optimizer-specific options. This is also the reason you cannot find `tolf` in the manual anymore.

**Comment by houtanb** [comment]
`tolx` done in ed549d3ba7657c8a6e6e5afaad7288464a9da19f

**Comment by JohannesPfeifer** [comment]
@houtanb Thanks. So we need only to merge the documentation to close this ticket in #1256
