### ISSUE TITLE
normcdf is not supported using MSVC for use_dll

### ISSUE THREAD

**Issue by tholden** [DynareTeam/dynare#1259]
normcdf has a one line implementation using standard library functions (included in MSVC), namely:

    double normcdf(double value)
    {
       return 0.5 * erfc(-value * M_SQRT1_2);
    }

It seems a little unnecessary for this not to be supported with MSVC.

**Comment by tholden** [comment]
Implementation taken from: https://stackoverflow.com/questions/2328258/cumulative-normal-distribution-function-in-c-c

**Comment by JohannesPfeifer** [comment]
@houtanb Could we get this into `4.5`? We already have a check for MSVC like
```
#ifdef _MSC_VER
# define nearbyint(x) (fabs((x)-floor(x)) < fabs((x)-ceil(x)) ? floor(x) : ceil(x))
#endif
```
in the `use_dll_static` and `use_dll_dynamic`-files so adding this might be not that much work.

**Comment by JohannesPfeifer** [comment]
@houtanb While we are at it, we should try to lift the restriction on `acosh, asinh, atanh`. MSVC is supporting them since `MSVC 2012`, i.e. `_MSC_VER` bigger than `1600`. See http://stackoverflow.com/questions/15539116/atanh-arc-hyperbolic-tangent-function-missing-in-ms-visual-c

**Comment by houtanb** [comment]
allowing `acosh, asinh, atanh, normcdf` with MSVC >= 11.0 in 4255be00b8a10226470c4cc1bc5a514ce37041bc

**Comment by houtanb** [comment]
@JohannesPfeifer @tholden I only find `erfc` support by `msvc` going back to 2012. Was this supported before?
https://msdn.microsoft.com/en-us/library/hh308292(v=vs.110).aspx

**Comment by JohannesPfeifer** [comment]
@houtanb It seems I was wrong. `erfc` was introduced in `MSVC` together with the other functions like `acosh`. So d7d2e4fde3e28cfb7fe0834f5bb1394617c3ea94 was wrong and should be reverted, while https://github.com/DynareTeam/dynare/commit/4255be00b8a10226470c4cc1bc5a514ce37041bc was ok.

**Comment by houtanb** [comment]
@JohannesPfeifer we can implement the solution [here](http://www.johndcook.com/blog/cpp_phi/) for MSVC < 2012

**Comment by JohannesPfeifer** [comment]
@houtanb We could. But given that MSVC 2015 is free and #1227 seems to mandate that version as well in master, we should probably not devote resources to this.

**Comment by JohannesPfeifer** [comment]
What is still missing to function correctly with `normcdf` is a
```
#ifdef _MSC_VER
#define _USE_MATH_DEFINES
#endif
```
Before
```
#include <math.h>
```
in the `_dynamics.c` and `_static.c` files to define the mathematical constants. See  https://msdn.microsoft.com/library/4hwaceh6.aspx
