### ISSUE TITLE
cygwin command line option should be renamed to gcc

### ISSUE THREAD

**Issue by tholden** [DynareTeam/dynare#1260]
MATLAB on Windows now supports the MinGW toolchain, and indeed adding it is just a few clicks via the "Add-Ins" button.
The MinGW toolchain seems to work fine with the cygwin command line option, as one would expect.
Renaming the command line option to GCC and documenting that it can use either Cygwin or MinGW installed via "Add-Ins" would seem to be sensible.

**Comment by JohannesPfeifer** [comment]
@tholden This seems to be a duplicate of #1226. Do you happen to know whether there are any special compiler flags that need to be passed? Or does the same configuration as for Cygwin in `dyn_mex.m` work?

**Comment by tholden** [comment]
The Cygwin compiler options seem to work fine. GCC is GCC.
I had misread that other issue previously, and would have commented there otherwise. Apologies.
I'm closing this, and adding a comment to the other issue.
