### ISSUE TITLE
bug in conditional forecast

### ISSUE THREAD

**Issue by rattoma** [DynareTeam/dynare#1276]
The conditional forecast is buggy. 

Namely there is some inconsistency in indexing between decision rule and declaration order. 

The way to fix it is to make sure that the pre-processor sets the vector of indices:
`constrained_vars_`
in decision rule order. 
In fact, `imcforecast` assumes that  `constrained_vars_` is in decision rule order
Moreover, one needs to fix `imcforecast` for the trend, since the latter is already defined in decision-rule ordering (so no need to use `inv_order_var`). I am going to make a pull request with the `imcforecast` fix, but I do not touch the pre-processor. If someone (@houtan?) could help with the latter.
Many thanks

**Comment by rattoma** [comment]
partial fix in #1277

**Comment by rattoma** [comment]
@houtanb In principle this could be fixed without touching the pre-processor, however I have a strange case where the preprocessor provides a non-sense index for the constrained variable, which does not match the true variable [and actually the index is even larger than the # of variables].
I am sending you the dynare files in a separate email.

**Comment by JohannesPfeifer** [comment]
@houtanb This is also present in 4.4.3, right? If yes, we should add it to the bug list. Do we know when exactly this problem occured and what it did?

**Comment by rattoma** [comment]
@houtanb. I have amended and merged my PR. I tested and in works. thanks a lot!

**Comment by houtanb** [comment]
@JohannesPfeifer this big has existed since the feature was introduced. See the`strvcat` line 231 of `preprocessor/Shocks.cc` in dbc9e0996d8b4ec08e9d2b0306683f73327fe6da. An indexing bug (adding `+1` to the index) was fixed in: 8dc1b9037d3b0c6988fa1cebc2644aea404982b1, but the index remained w.r.t. all variables, not just endogenous.

**Comment by houtanb** [comment]
It should be noted that this bug would only be apparent when there are endogenous variables declared after either exogenous or parameters. If all exogenous variables are declared at the top of the .mod file, the index would be correct since the change in 8dc1b90
