### ISSUE TITLE
Clarify and debug macro processor arithmetic in define statements.

### ISSUE THREAD

**Issue by JohannesPfeifer** [DynareTeam/dynare#1278]
Using 
```
@# define a=2
@# define b=3
@# define p= a/b
disp(@{p})
``` 
with ```savemacro=temp onlymacro``` results in 
```
@#line "junk2.mod" 1
disp(0)
```
which is not the expected outcome. 
```
@# define a=1
@# define b=2/3
@# define p= a/b
disp(@{p})
```
crashes the preprocessor on Windows

**Comment by MichelJuillard** [comment]
The macro processor knows only integers. See the first sentence of http://www.dynare.org/manual/index_33.html#Macro-expressions
We could add to the manual that the division is done with truncation and maybe catch better the division by zero and issue an error message

**Comment by JohannesPfeifer** [comment]
@MichelJuillard Then we should do this. The division by 0 should be handled properly. Can one rely on this truncation behavior? Because this is exactly what the user at http://www.dynare.org/phpBB3/viewtopic.php?f=1&t=9496&p=26546#p26546 is looking for

**Comment by MichelJuillard** [comment]
@JohannesPfeifer the user should use Matlab loops instead macro-processor loops. Computing artifical data is not a usage case for the macro-processor
In general one can rely on the truncated integer division, this a standard feature of integer arithmetic like in C or Fortran.

**Comment by houtanb** [comment]
The following modification will stop processing when integer division results in a non-integer value. @MichelJuillard @JohannesPfeifer is this what you want? We could also issue a warning and keep on processing.

```
       {
         TYPERR_CATCH($$ = *$1 / *$3, @$);
         if (((IntMV *)$1)->get_int_value() % ((IntMV *)$3)->get_int_value() != 0)
           driver.error(@$, "Integer division provides non-integer result");
       }
```

**Comment by MichelJuillard** [comment]
@houtanb, no I think that integer truncated division can be useful in some contexts. The only think to catch and trigger an error in the preprocessor is the division by zero
The integer truncated division needs to be documented in the manual
