### ISSUE TITLE
issue undeclared model variable errors at the end of model parsing

### ISSUE THREAD

**Issue by houtanb** [DynareTeam/dynare#1286]
Currently, when a variable is in an equation but not declared, the preprocessor issues an error and stops parsing. This is a problem during model development as a user can potentially need to run dynare several times before catching all undeclared variables. To fix this, `preprocessor/ParsingDriver.cc` needs to be modified to check the existence of variables at the end of the `model` block.

**Comment by stepan-a** [comment]
@houtanb Could you implement this in a separate branch?

**Comment by houtanb** [comment]
@MichelJuillard @stepan-a : NB that on line 365 of `preprocessor/ParsingDriver.cc`, when an unknown variable is encountered, it is declared as exogenous. It could have been declared as any type of variable. This is done so that we can continue parsing (and creating the model tree) while also keeping track of undeclared variables.

**Comment by houtanb** [comment]
NB: 67bac06 passed the test suite

**Comment by houtanb** [comment]
Branch updated. The test suite now passes 03a353856772eaa5e11372603cd59363fb3ff8a0

**Comment by houtanb** [comment]
@stepan-a, this is a reminder to merge this branch

**Comment by stepan-a** [comment]
@houtanb I have the impression that this branch needs more work before merge... In some trivial situations Dynare stops on the first error (for instance if a semicolon is missing in the model block).

**Comment by houtanb** [comment]
@stepan-a that's a syntax error and has nothing to do with this issue. This issue is only about undeclared variables used in the model block.

**Comment by houtanb** [comment]
Was closed by #1381
