### ISSUE TITLE
mex files not found by dynare_config

### ISSUE THREAD

**Issue by houtanb** [DynareTeam/dynare#1287]
In Matlab R2016b, `dynare_config` returns:

```
Configuring Dynare ...
[mex] Generalized QZ.
[mex] Sylvester equation solution.
[mex] Kronecker products.
[mex] Sparse kronecker products.
[mex] Local state space iteration (second order).
[mex] Bytecode evaluation.
[no]  k-order perturbation solver.
[mex] k-order solution simulation.
[no]  Quasi Monte-Carlo sequence (Sobol).
[mex] Markov Switching SBVAR.
```

Then, if you type `which k_order_perturbation; dynare_config` you get:

```
Configuring Dynare ...
[mex] Generalized QZ.
[mex] Sylvester equation solution.
[mex] Kronecker products.
[mex] Sparse kronecker products.
[mex] Local state space iteration (second order).
[mex] Bytecode evaluation.
[mex] k-order perturbation solver.
[mex] k-order solution simulation.
[mex] Quasi Monte-Carlo sequence (Sobol).
[mex] Markov Switching SBVAR.
```

Thanks to @JohannesPfeifer for pointing this out.

This problem exists on OS X, Windows, and Linux. Need to see with which version of Matlab this started

**Comment by JohannesPfeifer** [comment]
@houtanb The problem is present since Matlab R2016a, but not before.

**Comment by houtanb** [comment]
@JohannesPfeifer thank you

**Comment by houtanb** [comment]
The mex files are not found because the files `matlab/qmc_sequence.m` and `matlab/k_order_perturbation.m` are found when we try to see if the files `exist` in `dynare_config.m`. Removing these `.m` files and running `dynare_config` again makes Matlab find the mex files. This should not be the case as Matlab descends the search path looking for the file:

> MATLAB searches starting at the top of the search path, and moving down until a result is found or the last folder on the path is reached. If more than one name exists in a folder, MATLAB displays the first instance of name, according to the Function Precedence Order. Folders are an exception to the function precedence rules. They have precedence over all types except for variables.
http://www.mathworks.com/help/matlab/ref/exist.html

I will report it as a bug.

In the meantime, we can force `exist` to find the mexfiles by changing the `exist` statements in `dynare_config` to be:
`exist([mexpaths{:} 'k_order_perturbation'], 'file')`

**Comment by houtanb** [comment]
From Mathworks.....

> I'm sorry that I have been rather quiet of late. I have an update for you: The developers have identified the cause of the exist() problem and it is due to be fixed by changes to the dispatcher and path manager - these will be introduced in a future release but unfortunately I cannot go into specifics.

> As for why "which -all" was changing the behaviour of exist():

> On MATLAB start-up, MEX-files are not registered with the MATLAB dispatcher. When you try to launch a MEX-file or find it via "which -all", the MEX module is registered with the dispatcher so that it can recognise and know how to call MEX-files. When you call exist() before this, however, the module is not loaded and so it does not recognise them.

> Testing this out on Debian, I can try to force the MEX-module to be registered with the dispatcher before I call exist(): If I create a fake MEX file and try to run that at start-up, the ExistBug.Run() code that I sent you now passes:

> ```
~$ touch mymex.mexa64
~$ <matlabroot>/bin/matlab -nojvm
>> mymex()
>> ExistBug.Run()
```
> So in effect, which -all is not re-ordering the path, but it registers the required modules with the dispatcher for the files that it finds. Because this is not done with exist(), it only knows about .m files to start with. Consequently, the MEX-file is skipped over and exist returns 2.

And in a later email:

> The fix will be solved by changes to the dispatcher and path manager. These changes are part of a larger effort of re-architecting core MATLAB functionality and so it is very unlikely that this will be in R2017a. I cannot say exactly which release this will be incorporated into. Furthermore, I do not have an external bug report for you so that you can track it; it is tied to an enhancement that we do not make public.

**Comment by houtanb** [comment]
So, the solution is to add
```
which k_order_perturbation
which qmc_sequence
```
to `dynare_config.m`

**Comment by JohannesPfeifer** [comment]
@stepan-a You mentioned that you already have a fix that you could push.
