### ISSUE TITLE
bug with use_dll, k_order_perturbation

### ISSUE THREAD

**Issue by houtanb** [DynareTeam/dynare#1288]
The following tests fail:
```
|     * k_order_perturbation/fs2000k2_use_dll.mod
|     * k_order_perturbation/fs2000k_1_use_dll.mod
|     * k_order_perturbation/fs2000k3_use_dll.mod
```
with the error:`dynare:k_order_perturbation: Caught KordDynare exception: ../../../sources/k_order_perturbation/dynamic_dll.cc:70: Error when loading ./fs2000k2_use_dll_dynamic.mexa64 (can't locate the 'Dynamic' symbol)`

We first found this on Matlab R2016a, though it may have existed earlier. This bug exists on OS X, Linux and Windows with MinGW (thanks @JohannesPfeifer ). This does not exist on Windows with MSVC.

Can possibly fix with `extern "C"` or by creating C++ mex files. Should see in which version of Matlab this problem started and why.

**Comment by JohannesPfeifer** [comment]
@houtanb It also exists on R2015b. I cannot test earlier versions, because `gcc` is not available before that. Do we know whether the problem was introduced by R2014a moving away from `mexopts.bat`. See  https://github.com/DynareTeam/dynare/issues/1226

**Comment by houtanb** [comment]
I don't think so because this problem exists on Linux and OS X.

**Comment by houtanb** [comment]
The problem is that the `Dynamic` symbol is now hidden. The output of `nm` is:
```
$ nm fs2000k_1_use_dll_dynamic.mexa64 | grep -i dynamic
0000000000000a31 t Dynamic
0000000000205a90 d _DYNAMIC
```
In earlier versions of Matlab, the mex function would place `Dynamic` in the global namespace (i.e. it would have a `T` in the `nm` output as opposed to a `t`). The only functions in the global namespace now are mex* functions.

The first solution will be to find the correct flags to the `mex` calls in `/utilities/general/dyn_mex.m` and create a new else clause.

Another idea may be to compile a `.dll/.so/.dylib` directly for `k_order` that contains only the `*_dynamic` file and not the `mexFunction`

**Comment by houtanb** [comment]
@JohannesPfeifer this problem only exists on Linux and OS X starting in R2016b. Can you check how far back this problem goes on Windows?

**Comment by JohannesPfeifer** [comment]
@houtanb As mentioned above, it does at least exist in 2015b, which is the earliest `gcc` on Windows. If absolutely necessary I can check ealier versions with Cygwin

**Comment by houtanb** [comment]
@JohannesPfeifer perhaps it's not a problem for `cygwin` or `msvc` as no one has complained. Also, we don't have a case supporting `gcc` for windows in `matlab/utilities/general/dyn_mex.m`. We should fix that too.

Also, I should note for myself, that `isunix` is true under OS X, so the proper test for linux is `isunix && ~ismac`

**Comment by JohannesPfeifer** [comment]
@houtanb True. #1226 is concerned with gcc on Windows.

**Comment by houtanb** [comment]
Fixed on Linux. Still need to fix on macOS
