### ISSUE TITLE
Provide local nograph option to shock_decomposition

### ISSUE THREAD

**Issue by JohannesPfeifer** [DynareTeam/dynare#1290]
It should translate  `shock_decomposition(nograph)` to the last input of 
`shock_decomposition(M_,oo_,options_,varlist,nograph)`
with the default being 0. Alternatively, only if the `nograph` option is specified, we call `shock_decomposition` with a fifth input. Related to #1280

**Comment by rattoma** [comment]
Since I think there will be further local options, I would then add as fifth argument a structure:
`opts_decomp`
with default field
`opts_decomp.nograph=0`

**Comment by houtanb** [comment]
why not `options_.opts_decomp` and hence `options_.opts_decomp.nograph = 0;`?

**Comment by JohannesPfeifer** [comment]
`options_.shock_decomp` would be the best choice. Because `options` is not global, it will not affect subsequent calls to shock_decomp.
