### ISSUE TITLE
xlswrite and xlsopen on Octave no longer work on .xls files, only .xlsx files

### ISSUE THREAD

**Issue by houtanb** [DynareTeam/dynare#1293]
See: http://savannah.gnu.org/bugs/?44109

This causes `tests/data/mod1a.mod` to crash in the test suite on Octave

**Comment by MichelJuillard** [comment]
I don't see any workaround. This limitation of Octave should be indicated in the manual and maybe on the forum. For the test cases, we should use xlsx in stead of xls

**Comment by houtanb** [comment]
remaining to be done: replace `.xls` files in dseries unit tests with `.xlsx` files

**Comment by houtanb** [comment]
NB: Also removed the requirement to install the `java` package as it's no longer needed: http://wiki.octave.org/Java_package

**Comment by JohannesPfeifer** [comment]
@houtanb When you say "no longer", does that mean when you use Octave 4?

**Comment by houtanb** [comment]
@JohannesPfeifer yes. Are you saying this is not the case on Windows?

**Comment by JohannesPfeifer** [comment]
@houtanb I haven't checked this on Windows, but I also assume the same problem appears there. But because it sounded like an issue of lost backward compatibility, I curious which version of Octave introduced the break with previous behavior.

**Comment by houtanb** [comment]
@JohannesPfeifer the report is from 28 Jan 2015 which, judging by ftp://ftp.gnu.org/gnu/octave was in the lead up to the 4.0 release, so I'm guessing it was in the development 3.9 version.

As for backward compatibility, I don't know what we can do other than write in the manual that people will need to save their `.xls` files as `.xlsx` and, perhaps, issue an error to that effect if the user passes a `.xls` file under Octave.

**Comment by JohannesPfeifer** [comment]
@houtanb I think you can close this issue. @stepan-a fixed the unit tests via https://github.com/DynareTeam/dynare/commit/0b1b87316031550623d5deff88446dda8096acef and you did the manual
