### ISSUE TITLE
The plot of recursive forecasts is wrong when prefilter=1

### ISSUE THREAD

**Issue by felipeboralli** [DynareTeam/dynare#1299]
GNU Octave, version 3.8.1 "i686-w64-mingw32".
Dynare unstable (version 2016-08-23).

When the variables are prefiltered, the plot of recursive forecast is made mixing a filtered realized variable with a defiltered forecasted variable.
In the window below, this is very visible in the juros variable, but happens in all of them.

What I woud expect is all of them to be in the defiltered mode.

![1](https://cloud.githubusercontent.com/assets/22381123/19122621/aface774-8b01-11e6-9a6e-5bc81023bd68.png)

**Comment by JohannesPfeifer** [comment]
@felipeboralli Could you please send me the files to replicate the problem?

**Comment by felipeboralli** [comment]
@JohannesPfeifer I have sent them to your university email. Thanks

**Comment by JohannesPfeifer** [comment]
@felipeboralli The email never arrived. Maybe an issue with the spam filter, Could you try jpfeifer@gmx.de please.
