### ISSUE TITLE
calib_smoother doesn't recognize diffuse_filter

### ISSUE THREAD

**Issue by MichelJuillard** [DynareTeam/dynare#1302]
It should be possible to run the smoother with calibrated parameters for a model with non-stationary variables

**Comment by JohannesPfeifer** [comment]
This is solved in #1217

**Comment by JohannesPfeifer** [comment]
f553f89 to precise

**Comment by MichelJuillard** [comment]
Thanks @JohannesPfeifer I seemed to remember something like that but couldn't find it in the issues.
So I guess that it is better to search the repository than only the issues when looking for something
 
@stepan-a can we merge PR #1217 ?

**Comment by MichelJuillard** [comment]
In fact searching the repository is not practicable because we search the code as well.

**Comment by JohannesPfeifer** [comment]
I guess the easiest solution is to quickly deal with outstanding pull requests. This will steamline our workflow a lot.
