### ISSUE TITLE
Provide 32 and 64 bit Octave mex-files

### ISSUE THREAD

**Issue by JohannesPfeifer** [DynareTeam/dynare#1307]
As indicated at http://savannah.gnu.org/bugs/index.php?49289, there will be a 64 bit version of Octave 4.2, which then also will allow to use the 64bit Dynare preprocessor (see #1306). This will hopefully also solve #1304. But this means we need to provide 64bit mex-files as well as the 32bit ones do not run.

**Comment by stepan-a** [comment]
I close and open an issue in the [dynare-build](https://github.com/DynareTeam/dynare-build) project.
