### ISSUE TITLE
Investigate problem with schur_state_space_transformation

### ISSUE THREAD

**Issue by JohannesPfeifer** [DynareTeam/dynare#1312]
There is a problem with the initialization of the diffuse filter and smoother via `schur_statespace_transformation.m`. The mod-file `Local_trend_3.mod` (sent via email on 11/10/16) by a user contains three independent local trend models as in Durbin/Koopman (2012). Because the three processes are independent, all Kalman filter matrices should be block recursive. When using the Harvey initialization of the covariance `Pinf`, this is exactly what happens and results make sense. But when using the diffuse filter, in `dsge_likelihood.m` after

```
[Ztmp,Ttmp,Rtmp,QT,Pstar,Pinf]=schur_statespace_transformation(Z,T,R,Q,DynareOptions.qz_criterium,[1:length(T)]);
    Pinf = QT*Pinf*QT';
    Pstar = QT*Pstar*QT';
```

`Pinf` is not block diagonal anymore. Rather, there significant off-diagonal entries. This introduces a correlation between the independent local trend models that is very visible in the last graph. All observed trending variables are perfectly matched by the smoother, but the different trends interact in a way that is incompatible with the initial structure. Thus, there seems to be a problem with `schur_statespace_transformation.m`. Either there is a bug or there are numerical problems. 

Weirdly, the same problem is not present when I run just two local trend models (`Local_trend_2.mod`). Here, `Pinf` is again block-recursive. So something happens when going from two to three local trend models.

**Comment by JohannesPfeifer** [comment]
@MichelJuillard writes
> The  Schur transformation modifies the state space so as to separate
> trends from stationary variables. The trends in the transformed model
> are not necessarily the original trends in the model. It is sufficient
> if they span the same space.
> 
> This seems fine for dsge_likelihood. But, for DsgeSmoother, it seems
> that we are missing a last step where we should transform back the
> smoothed variables computed with the transformed model into the smoothed
> variables of the original model. We need to multiply with the projector
> of the transposed of the projector of the Schur decomposition (this
> needs to be checked)
>

**Comment by JohannesPfeifer** [comment]
@MichelJuillard Do we have a a reference for what we are going there? I don't feel comfortable with that part of the code, so someone else would need to do this ticket.

**Comment by rattoma** [comment]
@JohannesPfeifer @MichelJuillard I can look into this, but not very quickly

**Comment by JohannesPfeifer** [comment]
@MichelJuillard Did you fix this with your recent commits 2f9dc092855bbdb0b3fdd970b6ab551842c5080a and 897af97bff5b0c6e1a486b773c411b9ed5ebe2ca ? Because the mod-file in question seems to be working now.

**Comment by MichelJuillard** [comment]
Yes @JohannesPfeifer , that was the idea. I think it is fixed. I still want to add a test case inspired by the *.mod file and refactor the code

**Comment by JohannesPfeifer** [comment]
@MichelJuillard Perfect. Thanks. But then you should assign yourself the ticket.

**Comment by JohannesPfeifer** [comment]
Closed by https://github.com/DynareTeam/dynare/commit/80eeee697d13936d2cc6b4a550cf64b20b6e08d8
