### ISSUE TITLE
Find out why pr#1323 fails with older versions of matlab

### ISSUE THREAD

**Issue by stepan-a** [DynareTeam/dynare#1328]
See the mod file [here](https://gist.github.com/stepan-a/260eabd535efa7c38d1197cad04a581a) and discussion [here](https://github.com/DynareTeam/dynare/pull/1323).

**Comment by JohannesPfeifer** [comment]
@stepan-a I cannot replicate the issue on any Matlab version on Windows. It works with 2011a and 2016b. It also works on Sedna with R2015a.

**Comment by houtanb** [comment]
See the discusion in #1323

**Comment by houtanb** [comment]
@stepan-a says there was a mistake in the gist he posted, but that he ran the same test as that which was committed and that there was a numeric bug on Debian Stretch Matlab R2015a or R2015b

**Comment by houtanb** [comment]
NB: Works on OS X Matlab R2015b and R2016b

**Comment by houtanb** [comment]
I could not verify this bug on Debian Stretch with Matlab R2015b. Adding @stepan-a as owner so he can try to reproduce it.

**Comment by stepan-a** [comment]
I am not able to reproduce my own problem... I close.
