### ISSUE TITLE
Decide on how to deal with mh_recover on Octave

### ISSUE THREAD

**Issue by JohannesPfeifer** [DynareTeam/dynare#1332]
Various unit test fail on Octave, because the `mh_recover` option does not work properly under Octave as there are differences in setting the random number generator. We can either
- disable the check in the unit test and accept that the behavior of `mh_recover` is different under Octave and Matlab (and then document this)
- or provide an error under Octave when someone tries to use this option

**Comment by JohannesPfeifer** [comment]
@houtanb Could you please add a decision label to this?

**Comment by JohannesPfeifer** [comment]
@stepan-a @MichelJuillard Any thoughts on this? I would probably go for documenting the different behavior under Octave and provide a warning.

**Comment by MichelJuillard** [comment]
I agree with the solution proposed by @JohannesPfeifer. We can revisit the issue later.

**Comment by stepan-a** [comment]
Do you mean that under Octave we do not know what is the seed when mh_recover is used? For me this would not be a big issue. We should just remove the test under Octave for this, and document the different behaviour in the manual. I don't think we should add a warning for this... Most users won't understand the issue, and this would probably create more trouble.
