### ISSUE TITLE
make stoch_simul more efficient: solve at `order=1` when `M_.hessian_eq_zero==1`

### ISSUE THREAD

**Issue by houtanb** [DynareTeam/dynare#1336]
To avoid the error in `matlab/stochastic_solvers.m` line 64, when `M_.hessian_eq_zero` is true solve at `order = 1` instead of `2` or `3`. 

Work to be done on a branch

**Comment by JohannesPfeifer** [comment]
@houtanb At some point, we decided not to go down this route, see https://github.com/DynareTeam/dynare/issues/72. Do we want to changes this?

**Comment by stepan-a** [comment]
@JohannesPfeifer I do not see the relation between #72 and this issue...

**Comment by stepan-a** [comment]
@JohannesPfeifer Sorry for the noise... Now I see. This issue is not about adding a new algorithm, so we do not change the decision in #72.

**Comment by stepan-a** [comment]
@houtanb in this issue we should only discuss the automatic extension of the model with dummy auxiliary variables (to add missing lags). The absence of nonlinearity is not the problem here.

**Comment by houtanb** [comment]
@JohannesPfeifer @stepan-a to clarify, this is a continuation of #1335. When a linear model is encountered with no lags, the error in `matlab/stochastic_solvers.m` line 64 is encountered when `order > 1`. For efficiency reasons, in this situation (and when there are lags for that matter), we can calculate the solution at order 1. To do this, we can just set `local_order = options_.order` at the top of `stochastic_sovers.m` and replace `options_.order` with `local_order` throughout the file (there are some other slight changes, and perhaps the error will still need to be issued when `options_.k_order_solver && options_.risky_steadystate` is true.

I will change the title to clarify.

Originally, @stepan-a and I had envisioned adding `junk=0.9*junk(-1);` directly to the model in the preprocessor (when there are no lags, no `var_exo_det` and the model is nonlinear, and `order` > 1). We decided against this because the user could have multiple `stoch_simul` commands, one at `order=1`, another with `order=2` and we thus wouldn't be able to decide whether or not to add the equation.

**Comment by MichelJuillard** [comment]
If a model has no lag, we need to treat differently the case where there is also no lead (a static model) and only leads (a purely forward model).
For these two cases, we could write efficient solution code. Then we could in addition write specialized code for the case where the model is linear.
As long as we don't have this code, we should simply indicate that the case is not supported.
