### ISSUE TITLE
bug in missing_DiffuseKalmanSmootherH3_Z.m?

### ISSUE THREAD

**Issue by MichelJuillard** [DynareTeam/dynare#1339]
@JohannesPfeifer I don't see how line 302 
```
                    Linf    = eye(mm) - Kinf(:,i,t)'/Finf(i,t);
```
can be correct. The term before - is a square matrix and the term after, a row vector

**Comment by JohannesPfeifer** [comment]
@MichelJuillard Good catch. Thanks a lot.
