### ISSUE TITLE
Investigate whether recent mex-changes broke backward compatibility with older Matlab versions

### ISSUE THREAD

**Issue by JohannesPfeifer** [DynareTeam/dynare#1344]
Giovanni Lombardo reports a compilation error under Ubuntu with Matlab 2010a:
``` 
error: unknown type name ‘char16_t’
typedef char16_t mxChar;
```
(see http://www.dynare.org/phpBB3/viewtopic.php?f=1&t=11556). 
The post at http://stackoverflow.com/questions/22367516/mex-compile-error-unknown-type-name-char16-t
suggests that one might need to add
`typedef uint16_t char16_t;`
before
`#include "mex.h"`

**Comment by MichelJuillard** [comment]
The discussion in the second link reported above shows clearly that the problem comes with the compiler used in Ubuntu 16.04 LTS. We have to see if we need to provide for this particular compiler or whether an update of the compiler can solve the problem

**Comment by JohannesPfeifer** [comment]
@MichelJuillard I use Ubuntu with a newer Matlab version and did not face any problems. That's why my guess was that it has to do with older Matlab versions.

**Comment by MichelJuillard** [comment]
I have R2015a. At the end of ./extern/include/tmwtypes.h, they do some test before referencing char16_t

@JohannesPfeifer we were already compiling with Debian in 2010 and we didn't have this problem. My guess is that some recent compilers don't support char16_t anymore. Matlab may have provided for this change in compilers but only in recent versions of Matlab

**Comment by JohannesPfeifer** [comment]
Giovanni reports that the solution was 
```replacing the Matlab headers (in external/include) of Matlab 2010, with newer versions```
http://www.dynare.org/phpBB3/viewtopic.php?f=1&t=11556
As this seems to be a rare problem among the user base, I am closing the ticket.
