### ISSUE TITLE
set number of threads per job in parallel execution

### ISSUE THREAD

**Issue by rattoma** [DynareTeam/dynare#1349]
Given the large number of CPU's being made available on desktop pc's,  the current node option `singleCompThread` looks rather limited.
I would propose the following changes to the parallel configuration:
- set the default for `singleCompThread` to 0;
- add a node option in dynare.ini `numberOfThreadsPerJob`, which allows to set the number of cpu's assigned to each job. So, for example, for a node with 8 CPU's and `numberOfThreadsPerJob=2`, the parallel engine will split the work into 4 parallel instances, each using 2 cpu's. 

would this be possible?

**Comment by houtanb** [comment]
@rattoma is the default for `numberOfThreadsPerJob` 1?

**Comment by houtanb** [comment]
@rattoma and I guess it should be translated to `NumberOfThreadsPerJob`?

**Comment by houtanb** [comment]
@rattoma I will leave the doc for you to do. I assumed the default to be 1. Close this ticket once you have updated the doc and if the default value is correct. Finally, your description of this

**Comment by rattoma** [comment]
yes, it should translate in a new field of

`options_.parallel.NumberOfThreadsPerJob`

and the default should be set to 1.
many thanks

**Comment by rattoma** [comment]
@houtanb thanks a lot for your commits. I will update the doc and also make provisions in the parallel routines for this.

**Comment by houtanb** [comment]
@rattoma sounds good
