### ISSUE TITLE
Allow adding auxiliary variables like Ramsey multipliers to var_list_ 

### ISSUE THREAD

**Issue by JohannesPfeifer** [DynareTeam/dynare#1355]
The auxiliary variables are endogenous variables like every other variable. A call like 
`ramsey_policy(instruments=(i),irf=13,planner_discount=betta,periods=200) x pi MULT_1;`
would be suficient to display IRFs for the multiplier 1. However, the preprocessor does not allow adding `MULT_1` to the variable list, because:
`Unknown symbol: MULT_1`
We should allow adding any variable present in `M_.endo_names` to the `var_list_`. @houtanb Could you do this, please?
Related to http://www.dynare.org/phpBB3/viewtopic.php?f=1&t=12117

**Comment by JohannesPfeifer** [comment]
@houtanb Does this only work with `ramsey_policy`? Or also with `stoch_simul` after `ramsey_model`?

**Comment by houtanb** [comment]
@JohannesPfeifer just `ramsey_policy`, as you said in the issue description.
