### ISSUE TITLE
complete implementation of "shock_decomposition"

### ISSUE THREAD

**Issue by sebastien-villemot** [DynareTeam/dynare#136]
add options for grouping shocks together and for choosing the set of parameters to be used

**Comment by MichelJuillard** [comment]
Added new block "shock_groups" and new option "use_shock_groups" in "shocks_decompostion" via commits #920d212d95f04027c815f233e97b2b71bbde47ee, #98b53553c6d49366a00e48c330e023a06c041e4d,
#800d79d6e530ac894a0e69fd05470852bfc3b490,
#de567377c3b11fc948e3e9b9e09796a2ff6b69f6.
