### ISSUE TITLE
Investigate issue with disp_dr>subst_auxvar (line 248)

### ISSUE THREAD

**Issue by JohannesPfeifer** [DynareTeam/dynare#1367]
When `M_.aux_vars(i).type = 0` (lead>1), a crash happens. But it is not clear in which case this happens as leads should not be present on the right-hand side of decision rules. See http://www.dynare.org/phpBB3/viewtopic.php?f=1&t=12593

**Comment by JohannesPfeifer** [comment]
#773 needs to be done to fix this, because otherwise the information to trace the auxililiary variables back to the original ones is missing (`M_.aux_vars.orig_index` is empty for `type=0`).

**Comment by MichelJuillard** [comment]
@JohannesPfeifer we need the mod file to be able to replicate the problem. This seems a very peculiar case involving local variables

**Comment by MichelJuillard** [comment]
Complicated nonlinear expression involving leads of different length can generate AUX_ENDO_LEAD variables with lags appearing among the state variables of the model. This could probably be avoided but would require another layer of complexity in the preprocessor. For the time being, when an AUX_ENDO_LEAD variable appears among the state variable, I suggest to use just that name and not to try to substitute it
