### ISSUE TITLE
Decide on whether evalute_smoother (and others) should set M_.params

### ISSUE THREAD

**Issue by JohannesPfeifer** [DynareTeam/dynare#1373]
This picks up the discussion in https://github.com/DynareTeam/dynare/pull/1372#issuecomment-271336355

I agree with @MichelJuillard that changing `M_.params` in various functions is a bad idea as it makes it hard to trace what was going on in the mod-file. At the same time, I agree with @rattoma that keeping `M_.params` unchanged when calling `evaluate_smoother` would imply a break with previous versions and therefore mean a loss in backward compatibility. I could live with that, but usually @MichelJuillard prefers to be cautious in the regard. If we want to preserve backward compatibility, we need to make sure that `shock_decomposition` returns `M_` from `evaluate_smoother` to the base workspace, which was broken by https://github.com/DynareTeam/dynare/commit/2f717b5adc5a87f663c5c080f2963d1f65d1933e

**Comment by MichelJuillard** [comment]
@JohannesPfeifer you right. This was an unfortunate design when we introduced option parameter_set without thinking about side effects from the global in the function. I think it is better to insure backward compatibility
