### ISSUE TITLE
Dynare should give warnings when priors are unbounded

### ISSUE THREAD

**Issue by tholden** [DynareTeam/dynare#1401]
It is generally a bad idea to have a prior with unbounded density, as even with reasonably tight identification, such a prior can easily swamp the likelihood. This is particularly problematic when the prior is unbounded at the edges of its support, as then the mode will be driven to the edge, causing further problems with Hessian computation.

At present in Dynare, it is a bit too easy to inadvertently specify such a prior, given the mean and std. dev. specification of the beta distribution. I would suggest that Dynare should give a warning when such are encountered.

For the beta distribution, the prior has bounded support providing alpha>=1 and beta>=1. This means that the variance of the prior must be less or equal to `min(m*(1-m)^2/(1+1-m), (1-m)*m^2/(1+m))`, where `m` is the mean of the distribution.

**Comment by stepan-a** [comment]
@tholden I am not convinced that a user who does not pay attention to the plots of the densities (which pop up at the beginning of the estimation) will give more attention to a warning... We also have the same issue with the gamma prior.

**Comment by JohannesPfeifer** [comment]
@stepan-a I am also not convinced, but I don't think it would hurt. We already provide a warning if the beta prior is bimodal. Providing an additional warning would be almost costless

**Comment by stepan-a** [comment]
Okay. I have to check for the Gamma distribution, I do not remember under which threshold for the variance we obtain an asymptote.

**Comment by JohannesPfeifer** [comment]
@stepan-a I am working on it right now

**Comment by JohannesPfeifer** [comment]
@stepan-a @tholden As we explicitly compute the relevant hyperparameters, the check is straightforward (and equals the conditions for the mode being at a corner in `compute_prior_mode.m`). 
For future reference, the conditions are spelled out at http://www.math.uah.edu/stat/special/Gamma.html and http://www.math.uah.edu/stat/special/Beta.html

**Comment by tholden** [comment]
@stepan-a This occurred to me after being passed a MOD file in which prior density plotting had been suppressed. It's hard to predict the eccentricities of users!
@JohannesPfeifer Thanks for implementing this so quickly!
