### ISSUE TITLE
Add an interface for setting initial condition of the Kalman filter

### ISSUE THREAD

**Issue by stepan-a** [DynareTeam/dynare#1409]
See discussion in #1395.

**Comment by JohannesPfeifer** [comment]
We need a `filter_initial_state` block that follows the syntax of the `observation_trends` which was
``` 
observation_trends;
P_obs (g_p);
Y_obs (g_y);
end;
``` 
The difference is that now we only allow setting state variables as in `histval`-blocks (same consistency checks apply). Within the bracket, we should allow for any valid expression of constants and parameters as for `observation_trends`. 

The biggest question is the structure for storing these expressions. I would go for a `N by 2` cell array in `M_.filter_initial_state`. I prefer this to putting it in  `options_` (although we already store the trend coefficients in `options_.trend_coeff`). The `N by 2` cell should contain the name of the state in the first column and the expression in the second. Along rows it should be in the same order as `M_.endo_histval`. This should also allow us to keep track of auxiliary variables introduced for lags>1. 

Checks on whether the expression provided works belong into `initial_estimation_checks`

**Comment by houtanb** [comment]
@stepan-a can this be done for 4.5 or should we wait for 4.6?

**Comment by JohannesPfeifer** [comment]
@houtanb @stepan-a I don't think it's realistic to have this fully implemented for 4.5. Nevertheless, I would like to continue to work on this once the preprocessor part is done.

**Comment by houtanb** [comment]
@JohannesPfeifer ok, I'll do the preprocessor part this week

**Comment by houtanb** [comment]
@JohannesPfeifer in `histval` blocks we do not have consistency checks regarding the type of variable set. The only checks we do are made when `all_values_passed` has been set. In this case, we ensure that all endogenous and exogenous variables have been assigned in `histval`...

**Comment by JohannesPfeifer** [comment]
@houtanb When you run
```
// Tests the histval block in deterministic setup
// In particular test if it works on endos and exos substituted by an aux var

var c k z;
varexo x;

parameters alph gam delt bet aa;
alph=0.5;
gam=0.5;
delt=0.02;
bet=0.05;
aa=0.5;


model;
c + k - aa*x*k(-1)^alph - (1-delt)*k(-1);
z = 0.9*z(-2);
c^(-gam) - (1+bet)^(-1)*(aa*alph*x(-1)*k^(alph-1) + 1 - delt)*c(+1)^(-gam);
end;

initval;
x = 1;
k = ((delt+bet)/(1.0*aa*alph))^(1/(alph-1));
c = aa*k^alph-delt*k;
z = 0;
end;

steady;

check;

histval;
k(0) = 0.6;
x(0) = 0.9;
z(-1) = 0.1;
c(0) = 0;
end;

simul(periods=200);
```
you will get 
```
ERROR: histval_det.mod: line 36, cols 1-9: histval: variable c does not appear in the model with the lag -1 (see the reference manual for the timing convention in 'histval')
```
So there must be a check.

**Comment by houtanb** [comment]
@JohannesPfeifer you are right. The check was just not where I expected it to be. Thanks

**Comment by JohannesPfeifer** [comment]
@houtanb Sorry, I totally forgot about this. We of course need to pass lags as well in `filter_init_state`. So an example of the syntax presumably should be something like
``` 
filter_init_state;
y(0) = (beta*gamma);
x(-1) = (0.1);
end;
```

**Comment by stepan-a** [comment]
@houtanb, this will have to wait 4.6. Please, if you do something do it in a separate branch.

**Comment by houtanb** [comment]
@JohannesPfeifer we allow both endogenous and exogenous variables in `filter_initial_state`? If so, then do you want separate Matlab matrices to store them, as with `histval`? Also, I guess you want the lag in the first column and the expression in the second, is this correct?

**Comment by JohannesPfeifer** [comment]
@houtanb I don't think we need to take care of exogenous variables here. The initial state is about predetermined variables, i.e. the ones decided one period in advance. The exogenous variables are states, but are decided at time t and are therefore not taken as fixed by the Kalman filter. Lags of exogenous variables are a different matter. But for stochastic problems (at least as far as I can see) the preprocessor translates the problem into a one lag problem using auxiliary variables. Thus, in the end we only allow setting endogenous variables. 
For that reason, I would suggest to put the name as it appears in `M_.endo_names` in the first column and the expression in the second. That would allow mapping the expression to the position in `M_.endo_names` and therefore in declaration order.

**Comment by houtanb** [comment]
@JohannesPfeifer and the lag information?

**Comment by JohannesPfeifer** [comment]
@houtanb Do you think we need it? I thought everything is the first lag due to auxiliary variables. A name like `AUX_EXO_LAG_14_2` in the first column should convey all information and one can look up the associated lag in `M_.aux_vars.orig_lead_lag`

**Comment by houtanb** [comment]
@JohannesPfeifer the change is on the `filter_initial_state` branch. Please tell me if there are any problems.

**Comment by houtanb** [comment]
@JohannesPfeifer have you been able to look at this? If it's ok I'll close the ticket.

**Comment by JohannesPfeifer** [comment]
@houtanb I will try to look into it soon. Would it be possible to get a Windows snapshot of this branch? That would make my life easier.

**Comment by houtanb** [comment]
@JohannesPfeifer technically yes. @stepan-a has created a cross-compiler here: https://gitlab.com/DynareTeam/dynare-build though I'm not sure if we all have access to the necessary libraries. I'll try that after lunch.

**Comment by houtanb** [comment]
@JohannesPfeifer I don't have the rights on one of the needed repositories to create a snapshot. Wi will have to wait for @stepan-a (who is on vacation) to do this....

**Comment by JohannesPfeifer** [comment]
@houtanb Two things:
1. Was it a deliberate choice to put `filter_initial_state` into `options_` instead of `M_`?
2. It seems expressions are evaluated by the preprocessor instead of saving the expression as text. If I put
```
filter_initial_state;
k(0)= (((1-1/exp(gam)*bet*(1-del)) / (alp*1/exp(gam)^alp*bet) )^(1/(alp-1)))*(( (((((1-1/exp(gam)*bet*(1-del)) / (alp*1/exp(gam)^alp*bet) )^(1/(alp-1)))*1/exp(gam))^alp - (1-1/exp(gam)*(1-del))*(((1-1/exp(gam)*bet*(1-del)) / (alp*1/exp(gam)^alp*bet) )^(1/(alp-1))))/mst )^(-1))/(psi*mst^2/( (1-alp)*(1-psi)*bet*1/exp(gam)^alp*(((1-1/exp(gam)*bet*(1-del)) / (alp*1/exp(gam)^alp*bet) )^(1/(alp-1)))^alp )+(( (((((1-1/exp(gam)*bet*(1-del)) / (alp*1/exp(gam)^alp*bet) )^(1/(alp-1)))*1/exp(gam))^alp - (1-1/exp(gam)*(1-del))*(((1-1/exp(gam)*bet*(1-del)) / (alp*1/exp(gam)^alp*bet) )^(1/(alp-1))))/mst)^(-1)));
end;
```
into `fs2000.mod`, the second column contains a number (5.801) instead of the whole RHS as text.

**Comment by houtanb** [comment]
@JohannesPfeifer 1 is fixed in 0ed5ab5bfe88be8e4eb7f0600a17fe165fadf072. For 2, do you want it to be exactly as you have written there or do you want the variable names to be replaced with their associated arrays and indices? i.e.
```
'(((1-1/exp(gam)*bet*(1-del)) / (alp*1/exp(gam)^alp*bet) )^(1/(alp-1)))*(( (((((1-1/exp(gam)*bet*(1-del)) / (alp*1/exp(gam)^alp*bet) )^(1/(alp-1)))*1/exp(gam))^alp - (1-1/exp(gam)*(1-del))*(((1-1/exp(gam)*bet*(1-del)) / (alp*1/exp(gam)^alp*bet) )^(1/(alp-1))))/mst )^(-1))/(psi*mst^2/( (1-alp)*(1-psi)*bet*1/exp(gam)^alp*(((1-1/exp(gam)*bet*(1-del)) / (alp*1/exp(gam)^alp*bet) )^(1/(alp-1)))^alp )+(( (((((1-1/exp(gam)*bet*(1-del)) / (alp*1/exp(gam)^alp*bet) )^(1/(alp-1)))*1/exp(gam))^alp - (1-1/exp(gam)*(1-del))*(((1-1/exp(gam)*bet*(1-del)) / (alp*1/exp(gam)^alp*bet) )^(1/(alp-1))))/mst)^(-1)))'
```
or
```
'((1-1/exp(M_.params(3))*M_.params(2)*(1-M_.params(7)))/(M_.params(2)*M_.params(1)/exp(M_.params(3))^M_.params(1)))^(1/(M_.params(1)-1))*(((((1-1/exp(M_.params(3))*M_.params(2)*(1-M_.params(7)))/(M_.params(2)*M_.params(1)/exp(M_.params(3))^M_.params(1)))^(1/(M_.params(1)-1))/exp(M_.params(3)))^M_.params(1)-((1-1/exp(M_.params(3))*M_.params(2)*(1-M_.params(7)))/(M_.params(2)*M_.params(1)/exp(M_.params(3))^M_.params(1)))^(1/(M_.params(1)-1))*(1-1/exp(M_.params(3))*(1-M_.params(7))))/M_.params(4))^(-1)/((((((1-1/exp(M_.params(3))*M_.params(2)*(1-M_.params(7)))/(M_.params(2)*M_.params(1)/exp(M_.params(3))^M_.params(1)))^(1/(M_.params(1)-1))/exp(M_.params(3)))^M_.params(1)-((1-1/exp(M_.params(3))*M_.params(2)*(1-M_.params(7)))/(M_.params(2)*M_.params(1)/exp(M_.params(3))^M_.params(1)))^(1/(M_.params(1)-1))*(1-1/exp(M_.params(3))*(1-M_.params(7))))/M_.params(4))^(-1)+M_.params(6)*M_.params(4)^2/(M_.params(2)*(1-M_.params(1))*(1-M_.params(6))/exp(M_.params(3))^M_.params(1)*(((1-1/exp(M_.params(3))*M_.params(2)*(1-M_.params(7)))/(M_.params(2)*M_.params(1)/exp(M_.params(3))^M_.params(1)))^(1/(M_.params(1)-1)))^M_.params(1)))'
```

**Comment by JohannesPfeifer** [comment]
If you could do the replacement from parameter names to `M_.params()` that would be great. Note that variable names should not be allowed

**Comment by houtanb** [comment]
@JohannesPfeifer done in 642f8c86c179a02ea9fe3e48c79b20e67a576793

**Comment by JohannesPfeifer** [comment]
@houtanb Thanks. It looks good to me now.
