### ISSUE TITLE
Make master mex-files compatible with Matlab R2017a and adjust installer for Windows

### ISSUE THREAD

**Issue by JohannesPfeifer** [DynareTeam/dynare#1410]
Following the discussion in #1225, Matlab R2017a seems to require a change in mex-file compilation. 
This also implies that the commit https://github.com/DynareTeam/dynare/commit/4f3b35acbaaa23ad81d5200f68eacbbd9c9b98b6 is not correct, because we need a different set of 64bit mex-files going forward, starting with version `9.2`.

**Comment by JohannesPfeifer** [comment]
A user at http://www.dynare.org/phpBB3/viewtopic.php?f=1&t=14705 reports that Windows does not seem to be affected after all. So we should put this on hold until we get access to R2017a ourselves.

**Comment by stepan-a** [comment]
I have just tried successfully all the mod files in the example folder with the last snapshot under windows 7 with R2017a...

**Comment by JohannesPfeifer** [comment]
Then only macOS is affected. Closing the ticket.
