### ISSUE TITLE
Port write_equation_tags to write_latex_static_model and write_latex_original_model

### ISSUE THREAD

**Issue by JohannesPfeifer** [DynareTeam/dynare#1431]
See https://github.com/DynareTeam/dynare/commit/14f4544a29eac182ff1f5840e5f9cc78b9efa7e0#commitcomment-21632978

**Comment by JohannesPfeifer** [comment]
@stepan-a Can you please reopen this ticket. The commit message to #1441 was wrong and this ticket was inadvertently closed.

**Comment by stepan-a** [comment]
@JohannesPfeifer Done.
