### ISSUE TITLE
Speed of Kalman filter in unstable vs 4.4.3

### ISSUE THREAD

**Issue by JohannesPfeifer** [DynareTeam/dynare#1437]
Joris reports at http://www.dynare.org/phpBB3/viewtopic.php?f=1&t=6373&start=15#p37426 that  4.4.3 runs Bayesian estimation a lot faster than the current master. Profiling `fs2000.mod`, the culprit seems to be https://github.com/DynareTeam/dynare/pull/1088/commits/05fc096569e15e89d8d13b08799321c0313b168d where we made the Kalman filter more robust against ill-conditioned matrices. This seems to have considerable computational costs, because the function is called so often. I wonder if switching to the univariate filter if problems appear is not the better default.

**Comment by stepan-a** [comment]
@JohannesPfeifer The univariate filter is very slow... But we already have an option to prevent Dynare from switching to the univariate filter automatically. I wonder if the solution is not to have the patch proposed by @rattoma as an option (the drawback is that it would make the code even more obscure). I need to do the timing myself, I am a bit surprised by the difference you report on the forum.

**Comment by JohannesPfeifer** [comment]
@stepan-a Does this mean you could confirm the speed loss?

**Comment by stepan-a** [comment]
@JohannesPfeifer Yes, the speed loss was as you reported. The commit fixes this issue. The master branch is now faster than 4.4.3 (because we evaluate less often the objective function). The default behaviour, w.r.t. the potentially badly scaled prediction error covariance matrix, is the same as in 4.4.3.

**Comment by rattoma** [comment]
@JohannesPfeifer @stepan-a thank you. this is very helpful
