### ISSUE TITLE
Fix bytecode memory problem introduced in #1420

### ISSUE THREAD

**Issue by JohannesPfeifer** [DynareTeam/dynare#1439]
#1420 changed the memory allocation. Since then `ramst_normcdf_and_friends_static` fails with
```
Fatal error in bytecode: mxMalloc: out of memory 352 bytes required at line 1915 in function Init_GE (file ../../../sources/bytecode/SparseMatrix.cc
```

**Comment by stepan-a** [comment]
@FerhatMihoubi This is the bug I mentioned by email a couple of weeks ago. Any ideas?

**Comment by JohannesPfeifer** [comment]
Closed via https://github.com/DynareTeam/dynare/pull/1465
