### ISSUE TITLE
Make dynare_version and ver_less_than work with Master

### ISSUE THREAD

**Issue by JohannesPfeifer** [DynareTeam/dynare#1454]
`dynare_version.m` on the unstable version returns strings like `master-2017-05-18-95da783`. This way of providing a version number is not compatible with our functions like `ver_greater_than`, which rely on purely numeric output. But MacroModelBase relies on `dynare_version.m`

**Comment by stepan-a** [comment]
I move the issue to DynareTeam/dynare-build#7.

**Comment by stepan-a** [comment]
@JohannesPfeifer I fixed the build system. Now `dynare_version()` returns `4.6-unstable-GIT_SHA` in the snapshot version, `4.5.0` in the stable version, and `4.5.x-beta~y-GIT_SHA` for the beta releases of the stable version.

**Comment by JohannesPfeifer** [comment]
@stepan-a Perfect. Works like a charm.
