### ISSUE TITLE
Error when installing Dynare in Ubuntu 16.04

### ISSUE THREAD

**Issue by raspatan** [DynareTeam/dynare#1455]
I couldn't install Dynare 4.3.3 on Ubuntu 16.04. I am using Matlab 2017a. [Here](https://paste.ubuntu.com/24632092/) is the full log file with the error. This is the last bit of the code:

```
install: cannot stat '/usr/src/matlab/dynare-matlab/mex/matlab/*': No such file or directory
dpkg: error processing package dynare-matlab (--configure):
 subprocess installed post-installation script returned error exit status 1
Setting up libapache-poi-java (3.10.1-2) ...
Setting up octave-control (3.0.0-1) ...
Setting up octave-io (2.4.0-1) ...
Setting up octave-struct (1.0.11-1) ...
Setting up octave-optim (1.4.1-2) ...
Setting up octave-statistics (1.2.4-1) ...
Setting up liboctave-dev (4.0.0-3ubuntu9.1) ...
Setting up matlab2tikz (0.4.7-1) ...
Processing triggers for libc-bin (2.23-0ubuntu7) ...
Processing triggers for ca-certificates (20160104ubuntu1) ...
Updating certificates in /etc/ssl/certs...
0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...

done.
done.
Errors were encountered while processing:
 dynare-matlab
E: Sub-process /usr/bin/dpkg returned an error code (1)

```

There is a bug open in launchpad [here](https://bugs.launchpad.net/ubuntu/+source/dynare/+bug/1580761).

**Comment by houtanb** [comment]
I think you mean Dynare `4.4.3`. My first guess is that your Matlab is too recent for the dynare package as we have not updated the packages in the Dynare repository in a couple of years. See: http://www.dynare.org/DynareWiki/InstallOnDebianOrUbuntu

If you'd like to use Dynare with Matlab R2017a on Ubuntu, your best option is to compile it from source following the instructions here: https://github.com/DynareTeam/dynare#debian-or-ubuntu You can build the 4.5 branch as we are going to release Dynare 4.5 in the next few weeks.
