### ISSUE TITLE
Errors in code in mh_optimal_bandwidth.m 

### ISSUE THREAD

**Issue by spcatterall** [DynareTeam/dynare#1463]
It appears to me that there is an error in line 146 of mh_optimal_bandwidth.m:
    `g3 = abs(2*correction*k6(0)/(mu21*Itilda4*correction))^(1/9);`

This line should be identical to line 113:
     `g3 = abs(2*correction*k6(0)/(mu21*Itilda4*number_of_draws))^(1/9);`

Also, all references to 'n' in lines 135-152 should be replaced by 'number_of_draws'.
[I've recently written code in R which performs the same function as mh_optimal_bandwidth.m and I've read the paper underpinning these methods. I came across this matlab code during a google search.]

**Comment by stepan-a** [comment]
@spcatterall Thanks for spotting this. I don't think 146 and 113 should be the same, because just before (line 144) I redefine and normalize the correction with the number of observations. Maybe I should remove line line 144, the code would be easier to read.

**Comment by spcatterall** [comment]
@stepan-a Thanks for your reply. If my understanding of the code is correct, I still think that lines 146 and 113 should be the same. Line 113 forms part of the computations for the bandwidth=-1 option. In this case, the correction factor is computed earlier using the correction_for_repeated_draws function, and the correction factor is normalised at the end of this function (line 177). So, line 144 is just replicating the normalisation that takes place within the correction_for_repeated_draws function. So I suggest keeping line 144 so that the correction factors for the bandwidth=-1 and bandwidth=-2 options have consistent definitions.

**Comment by stepan-a** [comment]
@spcatterall Okay I understand now (I had to exhume the paper by Skold and Roberts). Thanks.
