### ISSUE TITLE
Compile fail w/ fix

### ISSUE THREAD

**Issue by cstackpole** [DynareTeam/dynare#1469]
Greetings,
Had issues compiling the last few daily's. Ended up with a bunch of errors about comparisons between signed and unsigned integers. @almightybeeij helped me figure out it was a missing include.

In preprocessor/ModelTree.cc there is a missing line.
`#include <boost/range/empty.hpp>`

Thanks!

**Comment by houtanb** [comment]
I don't have any problems compiling dynare and we build a snapshot every night on macOS and windows and compile regularly on Debian "Jessie," without any issues. What OS are you using and what version of boost do you have?

**Comment by cstackpole** [comment]
Greetings,
Thanks for the response. I know we are on an older distro, but it has support till 2020 and it will probably take us a few more years as we transition off of it. :-)

Here is what I have.

OS: Scientific Linux 6.9
GCC: 4.4.7
Matlab: 2017a
Boost: 1.41.0

Here is the error without that missing include:
`ModelTree.o `test -f 'ModelTree.cc' || echo './'`ModelTree.cc
ModelTree.cc: In member function ‘void ModelTree::computeNormalizedEquations(std::multimap<int, int, std::less<int>, std::allocator<std::pair<const int, int> > >&) const’:
ModelTree.cc:235: warning: comparison between signed and unsigned integer expressions
ModelTree.cc: In member function ‘void ModelTree::writeLatexModelFile(const std::string&, ExprNodeOutputType, bool) const’:
ModelTree.cc:1591: error: ‘empty’ was not declared in this scope
ModelTree.cc: In member function ‘void ModelTree::initializeVariablesAndEquations()’:
ModelTree.cc:1670: warning: comparison between signed and unsigned integer expressions
make[3]: *** [dynare_m-ModelTree.o] Error 1
make[3]: Leaving directory `/home/stack/matlab/tmp.dynare.bIK00m/preprocessor'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/home/stack/matlab/tmp.dynare.bIK00m/preprocessor'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/home/stack/matlab/tmp.dynare.bIK00m/preprocessor'
make: *** [all-recursive] Error 1
`

Thanks!

**Comment by houtanb** [comment]
@cstackpole Thanks for providing your compilation error. Your solution was not the correct one but it points to an error in the code. You can see the fix in 2cbb619

**Comment by cstackpole** [comment]
Thank you!
