### ISSUE TITLE
Allow calling calib_smoother with parameter_set option

### ISSUE THREAD

**Issue by JohannesPfeifer** [DynareTeam/dynare#1477]
Currently, the `calib_smoother` calls `evaluate_smoother` with the first input argument being `calibration`. We should allow for a `parameter_set`-like option to select the parameter set at which to compute the smoother. Default should be `calibration`.

Related to http://www.dynare.org/phpBB3/viewtopic.php?f=1&t=24518

**Comment by houtanb** [comment]
@JohannesPfeifer you just want to pass the `parameter_set` option to `calib_smoother`? It takes the following as arguments: `prior_mode`, `prior_mean`, `posterior_mode`, `posterior_mean`, `posterior_median`, `mle_mode`, `calibration`.

**Comment by JohannesPfeifer** [comment]
@houtanb Yes, exactly.
