### ISSUE TITLE
No rule to make target `../../../../dynare++/kord/faa_di_bruno.cpp', needed by `libdynare___a-faa_di_bruno.o'.  Stop.

### ISSUE THREAD

**Issue by barrymoo** [DynareTeam/dynare#1482]
## Details

OS: RHEL 7 (Kernel 3.10.0-514.6.1)
GCC Version: Red Hat 4.8.5-11
Attachments: `config.log` and `make.log`

## Configuration Script

``` bash
#!/usr/bin/env bash

module purge
module load boost/1.62.0 mkl/2017.1.132

autoreconf -si

MATLAB_VERSION=R2017a \
./configure \
    --with-matlab=/ihome/crc/install/matlab/R2017a \
    --disable-octave \
    --enable-openmp \
    --prefix=/ihome/crc/install/dynare/4.5.0

make &> make.log
```

## Error

``` bash
$ tail make.log 
	ln -s -f /ihome/crc/build/dyndare/dynare-4.5.0/mex/build/matlab/bytecode/$p $p; \
done
make[2]: Leaving directory `/ihome/crc/build/dyndare/dynare-4.5.0/mex/build/matlab/bytecode'
Making all in libdynare++
make[2]: Entering directory `/ihome/crc/build/dyndare/dynare-4.5.0/mex/build/matlab/libdynare++'
make[2]: *** No rule to make target `../../../../dynare++/kord/faa_di_bruno.cpp', needed by `libdynare___a-faa_di_bruno.o'.  Stop.
make[2]: Leaving directory `/ihome/crc/build/dyndare/dynare-4.5.0/mex/build/matlab/libdynare++'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/ihome/crc/build/dyndare/dynare-4.5.0/mex/build/matlab'
make: *** [all-recursive] Error 1
```

## Notes

I tried both the 4.5.0 release and the 4.6-unstable git repo. Any help is appreciated.

**Comment by barrymoo** [comment]
Attachements. Renamed to `make.txt` and `config.txt`.
[config.txt](https://github.com/DynareTeam/dynare/files/1166128/config.txt)
[make.txt](https://github.com/DynareTeam/dynare/files/1166129/make.txt)

**Comment by houtanb** [comment]
@barrymoo this question is better placed in the forum: https://forum.dynare.org

But, to answer your question, `make.txt` tells us the build fails when trying to build `libdynare++`. `config.txt` tells us that it will not build `dynare++` because you are missing one of the following libraries: `BLAS`, `LAPACK`, `MatIO`.

**Comment by barrymoo** [comment]
@houtanb Installing this for a colleague, I didn't know there was a forum. I made an assumption:

```
Dynare is now configured for building the following components...

Binaries (with "make"):
 Dynare preprocessor:                   yes
 Dynare++:                              no (missing one of: BLAS, LAPACK, MatIO)
```

would skip over Dynare++. I only need the Matlab components. It wasn't clear from the README that MatIO is actually a required dependency. Thanks.

**Comment by houtanb** [comment]
@barrymoo it's required to build one of the mex files that depends on dynare++. Our build system could be improved by allowing mex function builds to fail without stopping the rest of the build. However, the build system should not have built the mex functions when the requirements to build dynare++ were not present. Can you send me the config.log from `/mex/build/matlab`?

**Comment by barrymoo** [comment]
Attached (renamed to `config.txt`).

[config.txt](https://github.com/DynareTeam/dynare/files/1169962/config.txt)

**Comment by houtanb** [comment]
Thanks. It's as I suspected. You can either install MatIO, or delete `libdynare++ gensylv` from line 6 of `mex/build/matlab/Makefile.am` and rerun configure/make again.

I created an issue for this bug in #1483

**Comment by barrymoo** [comment]
@houtanb Hope it helps someone else. Thanks for the help.
