### ISSUE TITLE
Make variance decomposition of observables account for measurement error

### ISSUE THREAD

**Issue by JohannesPfeifer** [DynareTeam/dynare#1486]
Currently, we only decompose the variable after the measurement error has been taken out.

**Comment by JohannesPfeifer** [comment]
@houtanb Could you please block `ME` as a name for `varexo` in the preprocessor?

**Comment by houtanb** [comment]
@JohannesPfeifer at the moment the only variable names we restrict are those constructed by the preprocessor as auxiliary variables. Why do you need to restrict `ME` as an exogenous variable?

**Comment by JohannesPfeifer** [comment]
Because internally, I will use the string `ME` to denote sum of all measurement errors in the variance decomposition (think of blocking it like blocking `Sigma_e`)

**Comment by houtanb** [comment]
@JohannesPfeifer `sigma_e` is a command and is a valid exogenous variable name.

**Comment by JohannesPfeifer** [comment]
@houtanb You are right. We only have a warning in the manual not to use the variable name `Sigma_e` as it will lead to cryptic crashes. If you think it is a bad idea to block the name in the preprocessor, I can use the approach in https://github.com/DynareTeam/dynare/blob/master/matlab/load_m_file_data_legacy.m to use a random string internally.

**Comment by houtanb** [comment]
@JohannesPfeifer that sounds good to me. It's not that it's a difficult thing to do on the preprocessing side (it's quite easy), it just seems to me that the way you suggest, using a random variable name until you find one that's not an exogenous variable, is more user friendly.

**Comment by JohannesPfeifer** [comment]
@houtanb I had another look at the issue and think we should block the name `ME` in the preprocessor. The reason is that we would save the contribution of the measurement error in a field like `oo_.PosteriorTheoreticalMoments.dsge.ConditionalVarianceDecomposition.ME`. Here, we need to make sure that the `ME` field is not already taken. Using a random name in the code would not solve the problem.
