### ISSUE TITLE
Potentially make empirical moments independent of simul_replic

### ISSUE THREAD

**Issue by JohannesPfeifer** [DynareTeam/dynare#1487]
We currently rely on the last simulated series for computing moments. If `simul_replic` is increased, the moments will therefore change. I would propose to output the first instead of the last run in `simult.m`. That way, the results would always be the same. Of course, this would entail some loss of backward compatibility. I would accept this, because in principle any replication for the moments should do and the manual states that `simul_replic` is not used for moment computation. Related to https://forum.dynare.org/t/impact-of-simul-replic-option-on-empirical-moments/10553/4

**Comment by MichelJuillard** [comment]
@JohannesPfeifer OK for me

**Comment by stepan-a** [comment]
Reading the reference manual, I have the impression that the current behavior is a bug:
```txt
simul_replic = INTEGER

     Number of series to simulate when empirical moments are requested (i.e. periods > 0). 
     Note that if  this option is greater than 1, the additional series will not be used 
     for computing the empirical moments but will simply be saved in binary form 
     to the file FILENAME_simul. Default: 1.
```
That said, I never understood this option. Why do not we report the average of the moments? As a user this is what I would expect and need.

**Comment by JohannesPfeifer** [comment]
@stepan-a The reason is path dependence. In `4.2` we only had `options_.replic` for governing replications for IRFs. This option at the same time governed the number of simulations written to a binary file. The moments, however, were computed for the last simulation in `simult`. In https://github.com/DynareTeam/dynare/commit/8fe2eb23b9d31dda3bba8f81854be665c96a0681 we introduced a new option `simul_replic` to split the two functions, keeping the old behavior for the computation of moments in place.

**Comment by stepan-a** [comment]
I understand the origin of the option. My point, is that your proposal fixes a bug (if I interpret correctly the reference manual). The loss of backward compatibility cannot be an issue if we fix a bug. But I would prefer here to change the behaviour. Most of the users who set `simul_replic`, as in the forum topic you are referring to, expect or wish to compute the average of the moments.
