### ISSUE TITLE
Backward models with lagged exogenous variables

### ISSUE THREAD

**Issue by stepan-a** [DynareTeam/dynare#1501]
The Jacobian matrix of backward models with lagged exogenous variables is wrong, columns for the lagged exogenous variables are missing. It is unclear to me why we do not simply add auxiliary endogenous variables for the lagged exogenous variables (as in the case of backward/forward models). I suppose that the simplest fix is to add auxiliary variables (rather than augmenting the size of the Jacobian matrix).

An example is available [here](https://mnemosyne.adjemian.eu/snippets/1)

**Comment by stepan-a** [comment]
... But the cost of adding auxiliary variables (for large models or if we have a lot of lags) must be greater than the cost of having a Jacobian matrix with more columns. For instance if we have a shock in `t-50` we would have to add fifty auxiliary variables (rows and columns in the Jacobian matrix), while if we do not introduce these auxiliary endogenous variables we would just have to append one column to the Jacobian matrix. But I suppose that the latter approach involves more substantial changes in the preprocessor.

**Comment by JohannesPfeifer** [comment]
@stepan-a I think we have systematically moved to considering only one-lag problems for endogenous variables throughout the code. This makes particularly the Matlab code easier to deal with. I would advocate to go into the same direction for the exogenous variables. The only economic application for lagged exogenous variables that I know of is for news shocks and there you seldom have really large anticipation horizons.

**Comment by stepan-a** [comment]
@JohannesPfeifer I tend to agree with you.

Digging further around the example I posted, with @houtanb,  we probably found the problem. In the mod file I do not use any Dynare command indicating to the preprocessor that we are dealing with a stochastic model (`stochastic_simul`,  `estimation`, `osr`, ...), so that Dynare, by default, interprets the model as a perfect foresight model.

We have a different treatment for lead and lags in deterministic and stochastic models. In stochastic models the leaded (>=2) variables are not separable a priori (if they are nonlinearly combined), so that we are not allowed to create auxiliary variables for each leaded variable and must create auxiliary variables for nonlinear functions of leaded variables. While in a perfect foresight model we do not have this problem and can create auxiliary variables for each leaded variable. In the preprocessor this difference is controlled in `ModFile.cc` (beginning on line 396):
```c++
  if (mod_file_struct.stoch_simul_present
      || mod_file_struct.estimation_present
      || mod_file_struct.osr_present
      || mod_file_struct.ramsey_policy_present
      || mod_file_struct.discretionary_policy_present
      || mod_file_struct.calib_smoother_present)
    {
      // In stochastic models, create auxiliary vars for leads and lags greater than 2, on both endos and exos
      dynamic_model.substituteEndoLeadGreaterThanTwo(false);
      dynamic_model.substituteExoLead(false);
      dynamic_model.substituteEndoLagGreaterThanTwo(false);
      dynamic_model.substituteExoLag(false);
    }
  else
    {
      // In deterministic models, create auxiliary vars for leads and lags endogenous greater than 2, only on endos (useless on exos)
      dynamic_model.substituteEndoLeadGreaterThanTwo(true);
      dynamic_model.substituteEndoLagGreaterThanTwo(true);
    }
``` 
The problem here is that we do nothing for the exogenous variables in the `else` branch. That's why, in my example the Jacobian matrix is wrong. So it appears that the problem is more general than the one I had with my model (I should change the title of the issue). All the simulations of perfect foresight models (`simul`, `extended_path`, `perfect_foresight_solver`) with lead and lags on the exogenous variables are wrong. We should at least add
```c++
dynamic_model.substituteExoLead(true);
dynamic_model.substituteExoLag(true);
```
in the `else` branch (I wait the results of the testsuite to push the patch).

That said it is still unclear to me why we need to apply a different transformation for the deterministic and stochastic models. My understanding is that it would be correct to use the auxiliary variables created for a stochastic model (i.e. auxiliary variables for nonlinear functions of leaded variables) in a perfect foresight model (the reverse is not true). Having the same transformations would have at least three advantage:

- Simplification of the code in the preprocessor,
- Reduction of the number of auxiliary variables, and more importantly
- Use correct auxiliary variables for the stochastic extended path approach (which is currently wrong because we have the auxiliary variables of the deterministic models).

@MichelJuillard any ideas on this?

**Comment by stepan-a** [comment]
The understanding of my problem was wrong... Perfect foresight solutions are correct. My problem is just that by not using a Dynare command in a mod file, I obtain a dynamic file for perfect foresight models even if I intend to simulate a stochastic model.

Adding auxiliary variables for the exogenous variables would break some codes (when `initial_file` command is used).

For now the only workaround I see is to add a `stoch_simul` command after a `return` statement at the end of the file.

I still think that it would be simpler to have the same dynamic files for both types of models. But this is another issue to be discussed. Also in the current state the stochastic extended path simulations are probably wrong (because of the definition of the auxiliary variables for the expected terms).
