### ISSUE TITLE
Make log and ln operators in LaTeX code

### ISSUE THREAD

**Issue by JohannesPfeifer** [DynareTeam/dynare#1507]
When requesting LaTeX output, we should output `log` and `ln` as `\log` and `\ln` to make them operators that are correctly set typographically.

**Comment by houtanb** [comment]
@JohannesPfeifer in the preprocessor we don't output `ln` but rather `log`. I agree with the change above for `log10` to be `\log_{10}`. But for `log` should it just be `\log` or would you prefer `\ln`?

**Comment by JohannesPfeifer** [comment]
Having `\log` is fine.
