### ISSUE TITLE
Test matlab version in isfile routine

### ISSUE THREAD

**Issue by stepan-a** [DynareTeam/dynare#1545]
See [here](https://forum.dynare.org/t/getting-error-in-dynare-4-5-2/10896).

**Comment by JohannesPfeifer** [comment]
@stepan-a This is a duplicate of #1542

**Comment by stepan-a** [comment]
@JohannesPfeifer Thanks. I didn't see the PR. When you mentioned the issue I only fixed it for Octave and forgot older matlab versions... I merge. Unfortunatly I won't be able to publish 4.5.3 before November.

**Comment by JohannesPfeifer** [comment]
@stepan-a Ok. But this means `4.5.2`, which is the only version of the `4.5` branch correctly working with Windows does not support any Matlab version before `2016b`.

**Comment by stepan-a** [comment]
@JohannesPfeifer Yes. That is not acceptable... I had plan to work on other things, but I will release 4.5.3 later tonight. I cannot leave on vacation with this mess behind. 4.5.2 will become the shortest ever lived version of Dynare....

**Comment by JohannesPfeifer** [comment]
@stepan-a That is not true. 4.2.3 was the shortest–lived. It had wrong decision rules.

**Comment by stepan-a** [comment]
It was less than 24 hours? Too bad, I was comforting myself by thinking that I had broken a record...

**Comment by stepan-a** [comment]
@JohannesPfeifer  I have just checked there was more than one day between 4.2.3 and 4.2.4!
