### ISSUE TITLE
Pre-processor bug: plot_shock_decomposition

### ISSUE THREAD

**Issue by rattoma** [DynareTeam/dynare#1548]
The type option is not properly handled, since it always provides qoq field
`options_.plot_shock_decomp.type = 'qoq'; `

whatever this choice `qoq | yoy | aoa`

**Comment by rattoma** [comment]
thanks a lot. It should be also cherry picked to 4.5

**Comment by houtanb** [comment]
This was done in c6ee541f11a1177d86bdf58c5c31b1ec35c15191

**Comment by rattoma** [comment]
@houtanb thanks I overlooked this. 

Then , I have my usual question under these circumstances ...
Would it be possible to have a snapshot of the fixed preprocessor for 4.5.3 ... ???

**Comment by houtanb** [comment]
@rattoma for macOS? or for Windows?

**Comment by stepan-a** [comment]
@rattoma, @houtanb  I will do the windows snapshot with sources (so that Houtan can produce the snapshot for osx).

**Comment by stepan-a** [comment]
@rattoma The new windows binary is available here :

https://dynare.adjemian.eu/pre-release

in a zip archive or with a windows installer. The version name is `4.5.4-pre~1`.

**Comment by rattoma** [comment]
@stepan-a thanks a lot. very much appreciated

**Comment by rattoma** [comment]
@stepan-a apologize: apparently I cannot get to the page https://dynare.adjemian.eu/pre-release

**Comment by stepan-a** [comment]
@rattoma The provider I use for my server (ovh) was down this morning. It works now.
