### ISSUE TITLE
Support in-line comments in macroprocessor

### ISSUE THREAD

**Issue by tholden** [DynareTeam/dynare#1550]
This page: http://www.dynare.org/manual/Macro_002dprocessing-language.html#Macro_002dprocessing-language
contains an example in which a pre-processor definition is followed by a // comment. This generates an error in reality. Try e.g.
```
@#define x = 5              // Integer

parameters a;
a = 1;
```

This is something that should be supported though. The simplest solution would be for the pre-processor to remove all // comments in the generated -macroexp.mod.

**Comment by houtanb** [comment]
@tholden comments have never been supported in the macroprocessor. The comment in the example simply explains the type associated with the macro variable. Thus, this is not a bug, but an enhancement request.
