### ISSUE TITLE
Pre-processor should remove empty lines

### ISSUE THREAD

**Issue by tholden** [DynareTeam/dynare#1551]
When using complicated logic in the pre-processor language, one can often end up with files full of thousands of empty lines. This is both because empty lines are necessary to make pre-processor code readable, and because of the need to have empty lines at the end of .mod files that finish with e.g. an @#endfor .

It would be helpful if the pre-processor removed empty lines in the generated -macroexp.mod.

**Comment by houtanb** [comment]
Others may like the empty lines. You can do this yourself: https://stackoverflow.com/questions/14570489/how-to-remove-blank-lines-from-a-unix-file

**Comment by tholden** [comment]
I am quite capable of removing empty lines from a file myself. But I am producing a pre-processor based toolkit for others, and it is not reasonable to expect others to be able to do the same. People want to look at the -macroexp.mod file to get a feel for what's going on, without having to do a load of string processing on it first.

Were it not for this bug: https://github.com/DynareTeam/dynare/issues/706 I might agree with you. If it was really just a choice to include empty lines in your source files, then you get what you asked for. But that bug means it is not a choice. We have to insert empty lines at the end of MOD files. And for MOD files that are used as "functions" within inner loops, this results in obscene numbers of empty lines being generated.

To convince you that this is a real issue, have a look at this repository: https://github.com/tholden/DynareTransformationEngine . The "ExampleWithSpatialShocks.mod" file in that repo is a simplest possible spatial DSGE model, implemented using the "transformation engine". The original MOD file there is a modest 74 lines, including a few empty lines and comments (none of which are in pre-processor loops). The generated -macroexp.mod file has 1,173,373 lines (no typo, really over one million) of which only 8,282 are non-empty. I stress that none of the included files has a single empty line anywhere except at the end of the file.

Could we compromise and agree that the pre-processor should at least remove empty lines from the end of files? Or agree that https://github.com/DynareTeam/dynare/issues/706 should be reopened and fixed properly?

**Comment by JohannesPfeifer** [comment]
@houtanb I tend to agree with @tholden. I always found macro-processor generated mod-files very hard to read due to the excessive empty lines introduced. Particularly during debugging, I find it really annoying. Manually doing string processing seems like a bad solution, particularly as most users are on Windows, where the solution is less straightforward. 
How about having a command line option similar to `nolinemacro`, e.g. called `noemptylinemacro`, the gets rid of the empty lines on request?

**Comment by tholden** [comment]
Sounds like a good compromise.

**Comment by houtanb** [comment]
Because it is useful for @JohannesPfeifer, I will reopen the ticket. That said, it is extremely low priority as we have too much on our collective plate at the moment, and will not be finished in the foreseeable future. @tholden if you would like this to be done more quickly, I see two options:

1. You can do it yourself and submit a pull request. This way would probably be iterative with you making some changes, me telling you how to correct them until the commit was in good shape.

1. You or your institution could provide financing to the Dynare project to have this implemented. If you would like to discuss financing we can do that via email with @stepan-a

**Comment by tholden** [comment]
@houtanb I am sorry that the Dynare project is struggling with financing, it certainly deserves to be well financed by central banks and other policy institutions. But until your financing improves, it seems to me that encouraging contributors ought to be high on your collective priority list. I cannot say that these exchanges have particularly encouraged me.

I do not need to be told how that I could do it myself and submit a pull request. Indeed, I currently have a Dynare pull request sitting open, apparently doomed to oblivion. And, while once someone is a regular contributor, they might be prepared to keep editing a pull request until it passes muster, before they attain this level of dedication and competence, the likely effects are that it discourages the contributor and wastes everyone's time (both the original committer's, who will take far longer to make the changes, and the commentator who must detail them).

Another, superb pull request by someone else, adding support for MATLAB pools to Dynare's parallel engine has been sitting open so long that it is now essentially impossible to merge without completely rewriting the pull request. This too does not seem a great way to encourage contributors.

Furthermore, working on this particular issue is likely to be particularly time consuming for me, since it's still apparently very hard to get reliable builds on Windows (even cross compiling from Ubuntu on Win). And even if they work, such builds take forever. Given that the vast majority of your user base are on Windows, it is surprising to me that an MSVC toolchain hasn't made it onto the priority list, to increase the accessibility of contributions.

The result of the difficulty (and unpleasantness) of contributing is that I'm driven to make most of my contributions somewhere else. I maintain a Dynare fork that is used by many others. And my DynareOBC toolkit contains many changes (e.g. to the treatment of MLVs) that could as well have been added to core Dynare, only at greater cost to me. Maintaining DynareOBC is already a massive undertaking that I do for the good of my users, rather than thanks to any specific funding, so I'm not sure playing the "contribute more" card is particularly fair. However, I am always very grateful when I get bug reports or improvement suggestions for DynareOBC. Without exception DynareOBC has improved as a result.

**Comment by tholden** [comment]
Fair enough!
