### ISSUE TITLE
Silent crash when calculating steady state variables of basic economic model

### ISSUE THREAD

**Issue by wtpfede** [DynareTeam/dynare#1567]
Hi all,

I'm using Dynarec to reimplement a basic Ramsey model from Ohanian and Cole (1999)

The code is as follows:

```
varexo e; %e are tfp shocks
var y, c, n, k, x, z, i;
parameters theta, beta, rho, delta, gamma, biga;

theta=0.33;
beta=.96;
delta = 0.10;
rho=0.9;
gamma = 0.019;
biga = 0.78;

model;

(1/c) = beta*(1/c(+1))*( 1- delta+ z(+1)*(x(+1)*n(+1))^(1-theta)* theta*(k(+1))^(theta-1)) ;
biga/(1-n)=(1/c)*((1-theta)*z*(k^theta)*(x*n)^(-theta)*x) ;
z=(1-rho)+rho*z(-1)+e ;
i=z*y-c;
k(+1)=i+(1-delta)*k ;
y=(k^theta)*(x*n)^(1-theta) ;
x=(1+gamma)*x(-1) ; 

end;

initval; 
y = 0.184068;
c = 0.127782;
n = 1/3;
k = 0.0562866;
x = 1;
z = 0.1;
i = 0.0562866;
end;

check; 
steady;
```

Unfortunately, Dynarec crashes silently.

All of the parameters and the equations have been double checked by our team, and the numerical values come straight from the original paper.
We are on Octave 4.2.1 and Dynare 4.5.3.

If anyone has any pointers or could confirm this as a bug, this would be extremely helpful.

**Comment by JohannesPfeifer** [comment]
@wtpfede I can confirm the problem on Octave and will investigate it. That being said, your mod-file is wrong. 
```
x=(1+gamma)*x(-1) ;
```
has steady state `x=0`. But 
```
biga/(1-n)=(1/c)*((1-theta)*z*(k^theta)*(x*n)^(-theta)*x) ;
```
does not work with `x=0`

**Comment by wtpfede** [comment]
Hi Johannes, thanks for your reply.

You're right - indeed we identified this by manual calculation and solved by normalizing our other variables (dividing by X) and using the linearization trick, that is, for instance:
```
k_norm(t)=ln((k(t)/x(t))/k_mean(t))
```

Then indeed we can remove x from the system altogether, dynarec no longer crashes, and we get the expected results.

Still wondering what the bug was (and how to debug this kind of hard crashes - is a dynare log saved somewhere?), but for this particular implementation I'd say we're good.

Thanks for your reply @JohannesPfeifer !

**Comment by JohannesPfeifer** [comment]
@wtpfede I filed a bug report with Octave: https://savannah.gnu.org/bugs/index.php?52516

**Comment by wtpfede** [comment]
So it was actually a bug after all! Thanks @JohannesPfeifer for your help!

**Comment by JohannesPfeifer** [comment]
@wtpfede Yes, but it's a bug on the Octave side of things. So there is nothing in Dynare you can do to debug it (except for cross-checking with Matlab)

**Comment by JohannesPfeifer** [comment]
@stepan-a This ticket can be closed
