### ISSUE TITLE
macro-processor: allow for nested variables

### ISSUE THREAD

**Issue by JohannesPfeifer** [DynareTeam/dynare#1578]
1. Related to https://forum.dynare.org/t/total-number-of-periods-given-by-variable/11200/3

We should allow
```
@#define J=10
@#define K=1:@{J}
```
but currently the lexer gives an error when encountering the `@{J}` in the second line.

2. Related to this, according to the manual, we have at the command line
```-DMACRO_VARIABLE=MACRO_EXPRESSION```
But we do not really macro expressions as 
`dynare macro.mod -D=[1,2]`
fails.

3. I tried to get around this by using 
```
n_countries=2;
fid=fopen('n_countries_def.txt','w+');
fprintf(fid,'@#for co in 1:%u\n',n_countries)
fclose(fid)
```
to write a text file creating the first statement and then using 
```
@#include "n_countries_def.txt"
var C_@{co};
@#endfor
```
But this is also not allowed:
```
ERROR in macro-processor: n_countries_def.txt:1.15: @#for loop not matched by an @#endfor or file does not end with a new line (unexpected end of file)
```
because apparently the macro processor checks for completeness of the macro in each included file instead of the whole created file.

**Comment by feliperuiz01** [comment]
Hi @JohannesPfeifer,

I solved it. I followed your idea of writing a text file, but in it I instead defined a vector named countries, which I then used in the `for` loop:

```
n_countries=2;
fid=fopen('n_countries_def.txt','w+');
fprintf(fid,'@#define countries = 1:%d\n',n_countries)
fclose(fid)
```

And then, in the .mod file:

```
@#include "n_countries_def.txt"

@#for co in countries
var C_@{co}
@#endfor
```

It worked!
Thanks for helping me with this.

**Comment by houtanb** [comment]
@JohannesPfeifer what is wrong with simply doing:
```
@#define J=10
@#define K=1:J
```
The output of then running
```
@#for I in K
A@{I}
@#endfor
```
is
```
@#line "example1.mod" 17
                  A1

@#line "example1.mod" 17
                  A2

@#line "example1.mod" 17
                  A3

@#line "example1.mod" 17
                  A4

@#line "example1.mod" 17
                  A5

@#line "example1.mod" 17
                  A6

@#line "example1.mod" 17
                  A7

@#line "example1.mod" 17
                  A8

@#line "example1.mod" 17
                  A9

@#line "example1.mod" 17
                  A10
```
Is this not what you want?

**Comment by JohannesPfeifer** [comment]
@houtanb That is an elegant solution I did not think. That solves issue 1.) from above.

**Comment by houtanb** [comment]
@JohannesPfeifer regarding number 2) above, we do take in arrays. They are just stored as strings. Calling Dynare with `-DMYVEC=[1:3]` and having `@{MYVEC}` in the `.mod` file yields
```
[1:3]
```
The confusing thing is that
```
@#for I in MYVEC
A@{I}
@#endfor
```
yields the error `Argument of @#for loop must be an array expression`. This should be fixed so I'll change this to a bug instead of an enhancement.

**Comment by JohannesPfeifer** [comment]
Ok. Thanks

**Comment by houtanb** [comment]
@JohannesPfeifer The functionality you outlined in 3) above is correct. This is an error because you have interrupted the `@#for` macro statement. You can think of `@#include` working the way that `#include` works in C and hence cannot split statements between the included file and the including file.
