### ISSUE TITLE
Fix prior sampler

### ISSUE THREAD

**Issue by JohannesPfeifer** [DynareTeam/dynare#1607]
`prior simulate` in `cli/prior.m` calls
```
results = prior_sampler(0, Model, BayesOptions, options_, oo_, EstimatedParams);
``` 
where the 0 indicates that no decision rules need to be saved. The problem is that this flag `drsave` is then used to call `resol` with
```
    work = ~drsave;
    [dr,INFO,M_,options_,oo_] = resol(work,M_,options_,oo_);
``` 
so that `resol` only computes eigenvalue, but not BK conditions etc. As a result, the reported simulations will never fail the BK conditions. See https://forum.dynare.org/t/determinacy-prior-simulate-puzzle/11681

**Comment by stepan-a** [comment]
Closed by fa67aeb7a6c55697fc990db8275e35b492396bb6 and merged in 4.5 branch. The problem was in the routine computing the first order reduced form (argument `task` was not correctly interpreted) rather than in the prior sampler routine.
