### ISSUE TITLE
Build failed in Arch Linux

### ISSUE THREAD

**Issue by angelosalton** [DynareTeam/dynare#1612]
Tried to build from 4.5.4 sources (against Octave 4.4.0), with the following error:

```
In file included from ../../../../contrib/ms-sbvar/utilities_dw/include/dw_std.h:23,
                 from ../../../../contrib/ms-sbvar/switch_dw/switching/dw_switch.c:25:
../../../sources/ms-sbvar/modify_for_mex.h:39:12: fatal error: octave/config.h: File or folder not found
 #  include <octave/config.h>
            ^~~~~~~~~~~~~~~~~
compilation terminated.
```
I'm pretty sure all necessary dependencies are met. I wonder if a header file for Octave is missing.

**Comment by svillemot** [comment]
Hi @angelosalton,

We have not yet verified the compatibility of Dynare with Octave 4.4 (we only tested Octave 4.2 so far).

We'll get back to you once we've done the necessary tests.

**Comment by angelosalton** [comment]
Thanks for the help! I will downgrade Octave on my machine.
