### ISSUE TITLE
Identification display bug

### ISSUE THREAD

**Issue by wmutschl** [DynareTeam/dynare#1614]
Hi @rattoma , I just noticed a bug in the identification toolbox when only checking for unidentified parameters without any other parameters, as Dynare prints that all parameters are identified even though the figures etc do not suggest so. This is probably just a small bug in the display function.

To replicate the bug (I use Dynare unstable from June, 3 and Matlab R2017b):
1) Open kim2.mod in the test files for identification
2) Change
>estimated_params;
alph ,uniform_pdf,0.6,0.04,0.5,0.7;
//betae ,uniform_pdf,0.99,0.004,0.98,1;
//delta ,uniform_pdf,0.0125,0.001,0.01,0.015;
phi ,uniform_pdf,0.5,0.2,0,10;
theta ,uniform_pdf,0.3,0.1,0,10;
dumpy ,uniform_pdf,0.5,0.2,0,10;
end;

to

> estimated_params;
//alph ,uniform_pdf,0.6,0.04,0.5,0.7;
//betae ,uniform_pdf,0.99,0.004,0.98,1;
//delta ,uniform_pdf,0.0125,0.001,0.01,0.015;
phi ,uniform_pdf,0.5,0.2,0,10;
theta ,uniform_pdf,0.3,0.1,0,10;
//dumpy ,uniform_pdf,0.5,0.2,0,10;
end;

That is, only include colinear parameters.

3) Run "dynare kim2" and the output is
>==== Identification analysis ====
Testing prior mean
Evaluating simulated moment uncertainty ... please wait
Doing 100 replicas of length 300 periods.
Simulated moment uncertainty ... done!  
All parameters are identified in the model (rank of H).
All parameters are identified by J moments (rank of J)
Press ENTER to print advanced diagnostics
Collinearity patterns with 1 parameter(s)
Parameter       [ Expl. params   ]       cosn
phi             [ theta          ]      1.0000000
theta           [ phi            ]      1.0000000
Press ENTER to plot advanced diagnostics
==== Identification analysis completed ====

which is contradicting. If one includes e.g. dumpy or alpha (or both or any other parameter) in the estimated_params section, dynare correctly displays you that [phi;theta] are colinear and not identified.

**Comment by rattoma** [comment]
@wmutschl many thanks. I will have a look
Marco

**Comment by JohannesPfeifer** [comment]
The problem is that the display-condition in `disp_identification` is on `if any(idemodel.ino)` only, meaning that only in the presence of separatey non-identified parameters the collinearity display is executed. My guess is that the condition must be on 

`if any(idemodel.ino) || any(any(idemodel.ind0==0)) || any(idemodel.jweak_pair)`

and similarly for 

`if any(idemoments.ino)`

**Comment by wmutschl** [comment]
That seems promising, however, one also has to change 
`if ~any(idemoments.ino) && ~any(any(idemoments.ind0==0))`
and similarly
`if ~any(idemodel.ino) && ~any(any(idemodel.ind0==0))`

Otherwise it displays that they are both identified and not

> WARNING !!!
> The rank of J (moments) is deficient!
>     [theta,phi] are PAIRWISE collinear (with tol = 1.e-10) !
> All parameters are identified by J moments (rank of J)

I think simply using else instead of these two conditions, fixes this.

**Comment by rattoma** [comment]
dear both, many thanks
