### ISSUE TITLE
Add a user friendly frontend to simult_

### ISSUE THREAD

**Issue by sebastien-villemot** [DynareTeam/dynare#236]
The idea is to give an user-friendly way to perform simulations of a model using custom series of shocks; this is a recurring request.

**Comment by JohannesPfeifer** [comment]
I would propose to close this issue as I don't think the value added has any relation to the costs. By now there are so many well-documented mod-files showing how to use the simult_-function that adding an interface is not necessary. I haven't seen requests for this in years. The great strength of the ```simult_```-function is its flexibility. This comes at the costs of requiring some programming knowledge, but I think we can expect this of more sophisticated users. Providing an interface allowing the same flexibility seems too much work for me.

**Comment by MichelJuillard** [comment]
OK for closing
