### ISSUE TITLE
UnivariateSpectralDensity.m must be implemented to preprocessor and documented.

### ISSUE THREAD

**Issue by sebastien-villemot** [DynareTeam/dynare#254]
The SpectralDensity option of stoch_simul is neither documented nor implemented in the preprocessor. 
It could be implemented as an option of stoch_simul().

Alternatively, we could use a preprocessor command along the lines

spectral_density_decomposition(plot=integer,cutoff=number,step_length= number);

which translates into

options_.SpectralDensity.trigger = 1;
options_.SpectralDensity.plot  = integer; 
options_.SpectralDensity.cutoff  = number; 
options_.SpectralDensity.sdl = number;

**Comment by JohannesPfeifer** [comment]
@houtanb Actually, we only need an option ```spectral_density``` to ```stoch_simul``` translating to
```options_.SpectralDensity.trigger = 1;```
I will do the rest.

**Comment by JohannesPfeifer** [comment]
@houtanb Could you please also give me an option of ```stoch_simul``` named ```bandpass_filter``` It should be mutually exclusive with ```hp_filter```. If specified as 
```
stoch_simul(bandpass_filter)
```
it should map into ```options_.bandpass.indicator=1```. If specified as 
```
stoch_simul(bandpass_filter=[lowerbound upperbound])
```
it should map into 
```
options_.bandpass.indicator=1
options_.bandpass.lowest_periodicity=lowerbound;
options_.bandpass.highest_periodicity=upperbound;
```
Default values are
```
options_.bandpass.indicator=0;
options_.bandpass.lowest_periodicity=32;
options_.bandpass.highest_periodicity=6;
```
