### ISSUE TITLE
Check for consistent use of dataset_.descriptive.mean vs. bayestopt_.mean_varobs in smoother and estimation

### ISSUE THREAD

**Issue by sebastien-villemot** [DynareTeam/dynare#255]
Currently, both structures are still present. prior_posterior_statistics.m sets 

bayestopt_.mean_varobs = dataset.descriptive.mean';

to have both. Thus, use should be made consistent and storage be confined to one structure. As the mean of the data belongs to the dataset and not the estimation, the dataset_ structure is better suited than bayestopt_.

**Comment by JohannesPfeifer** [comment]
#852 moves the setting of 
```bayestopt_.mean_varobs = dataset.descriptive.mean';```
to ```dynare_estimation_init.m``` as other routines also need this info, even if no MCMC is run.
