### ISSUE TITLE
Option to require that all endo/exo are initialized in initval

### ISSUE THREAD

**Issue by sebastien-villemot** [DynareTeam/dynare#261]
Implement a new option to initval command, "all_values_required". The preprocessor would stop and reports which endogenous or exogenous variable has not been explicitly initialized if any (instead of using a default zero value).

Request from the IMF for GIMF

**Comment by JohannesPfeifer** [comment]
@houtanb Could you implement this for `histval`. I can do the documentation

**Comment by houtanb** [comment]
@JohannesPfeifer should we not wait to finish #288?

**Comment by JohannesPfeifer** [comment]
@houtanb Maybe, but I don't see how the two tickets are related.
