### ISSUE TITLE
design an interface for assigning moment/irf contraints (e.g. sign constraints)

### ISSUE THREAD

**Issue by sebastien-villemot** [DynareTeam/dynare#267]
Currently there is no way of setting a set of constraints to irfs or moments of DSGE model to feed to some calibration procedure like Monte Carlo filtering in the sensitivity analysis toolbox.

Indeed the threshold_redform option in sensitivity analysis would only allow to set, e.g., the SAME sign constraint to a set of irfs, which is not very handy.

So, we may think to the following syntax for sign constraints in moments:

moment_calibration;
y, y(-1), +; [i.e. auto-correlation with 1 lag]
c, g(-3), +; [i.e. auto-correlation with generic lags]
i, g, -;  [i.e. cross-correlation, contemporaneous]
end;

for irfs [y c i are endogenous, em eg are exogenous shocks]:

irf_calibration;
y, em, -; 
c, eg, +;
i, eg, -;
end;

or the following for more detailed numeric boundaries, in principle mixed with simple sign constraints

moment_calibration;
y, y(-1), [0.5 1]; [auto-correlation with 1 lag]
c, g(-3), +; [auto-correlation with generic lags]
i, g, [-1, -0.5];  [cross-correlation, contemporaneous]
end;

irf_calibration;
y, em, [-0.01 0]; 
c, eg, [0 0.02];
i, eg, -;
end;

The sign constraint can also be defined using 
[0 inf] for +
[-inf 0] for -

**Comment by stepan-a** [comment]
@sebastien-villemot Do you remember why did you reopen this issue ?

**Comment by sebastien-villemot** [comment]
@stepan-a No, sorry. I guess some of the points listed in my message dated 2014-03-25 were not yet implemented.

**Comment by sebastien-villemot** [comment]
I think that @rattoma is the right person to decide whether this should be left open.

**Comment by rattoma** [comment]
@stepan-a @sebastien-villemot 
I did some check and indeed this issue can be closed, since also  #720 is fixed.
I would have a similar issue to open, for moment calibration, namely to allow setting calibration criteria for moments based on data. 

However, I guess it will be best to close this and open a dedicated one?

**Comment by JohannesPfeifer** [comment]
@houtanb Could you please close this ticket. #891 supersedes the last discussion
