### ISSUE TITLE
Determinant computation in marginal_density.m looks sub-optimal

### ISSUE THREAD

**Issue by sebastien-villemot** [DynareTeam/dynare#270]
In marginal_density.m, the determinant is computed (at three places) using the det() function. This function is known to be less precise than a Cholesky-based determinant computation when the determinant is close to zero.

Stéphane thinks that the Cholesky was used before, so we need to understand why this has changed, and therefore whether we can go back to the Cholesky.

Issue reported by Gilles Bélanger (Ministère des Finances du Québec)

**Comment by JohannesPfeifer** [comment]
http://de.mathworks.com/matlabcentral/answers/41080-compute-determinant-using-cholesky-decomposition suggests that there is no point in changing this. If agreed upon, we could close this issue.

**Comment by MichelJuillard** [comment]
I agree with closing the issue

**Comment by JohannesPfeifer** [comment]
@MichelJuillard Sorry, I missed the loop. I amended the PR along the suggested lines

**Comment by JohannesPfeifer** [comment]
@MichelJuillard We should then close this as well
