### ISSUE TITLE
make check: add timing information of tests

### ISSUE THREAD

**Issue by sebastien-villemot** [DynareTeam/dynare#298]
Add information to each .trs file about how long the test took to run

In the make check summary, list the 10 tests that took the longest

**Comment by JohannesPfeifer** [comment]
@houtanb Is that ticket done?

**Comment by houtanb** [comment]
@JohannesPfeifer almost. There are some things I want to check before I close the ticket and I want to redo the graphs

**Comment by houtanb** [comment]
Done in commits between DynareTeam/testsuite@a53bea9179ef0a524bf4aa8c89e75c49d9e5e633 and DynareTeam/testsuite@d2eb69493e07d5c04b5c437e3d424267fd01aca2
