### ISSUE TITLE
Add reset option to shocks-block

### ISSUE THREAD

**Issue by JohannesPfeifer** [DynareTeam/dynare#331]
Currently the only way to set a different covariance matrix of structural shocks and measurement errors is to manually set all elements that differ from the previous shocks-statement. It would be nice to have something like
```
shocks(reset);
var e; stderr 0.9;
end;
```
that sets all elements of the M_.Sigma_e and M_.H to 0 before filling it again with the entries of the shocks-block.

**Comment by JohannesPfeifer** [comment]
@houtanb Could you please also add this to your to-do list when you work on #720

**Comment by houtanb** [comment]
@JohannesPfeifer what is the difference between this option and the ```overwrite``` option?

**Comment by JohannesPfeifer** [comment]
Seems I have missed this option that's already there.
