### ISSUE TITLE
Clarify and potentially disentangle role played by conf_sig

### ISSUE THREAD

**Issue by JohannesPfeifer** [DynareTeam/dynare#338]
According to the manual, conf_sig by default is 0.9 for forecast, but after global_initialization, it is 0.6. conditional_forecast has an option with the same name and default 0.8 according to the manual.

**Comment by JohannesPfeifer** [comment]
This also affects the bvar-a-la-sims, see http://www.dynare.org/phpBB3/viewtopic.php?f=1&t=6939

**Comment by MichelJuillard** [comment]
Proposed decision: unify the default to 0.8 and correct the manual

**Comment by stepan-a** [comment]
We should have separate options (even if the default value is the same)
