### ISSUE TITLE
testsuite: modify prior for rho in fs2000XX.mod

### ISSUE THREAD

**Issue by MichelJuillard** [DynareTeam/dynare#357]
The current prior implies a vertical asymptot at 0. This becomes indeed the theoretical posterior mode. This unwanted result is now found in one case at least by mode_compute=5. More importantly, we warn users agains using such priors.

**Comment by JohannesPfeifer** [comment]
@MichelJuillard Do you remember where this problem is still present. It tried it with the ```fs2000.mod``` and the non-stationary version and the posterior is always more like 0.7. Also, I don't really understand the theoretical argument against such a type of prior.

**Comment by MichelJuillard** [comment]
All *.mod file in ./tests/fs2000 have a prior with an asymptote to zero for rho except fs2000a.mod I checked that fs2000_data.mod still return a value close to zero for posterior mode after posterior optimization.

One needs to have a lot of faith in the parameter being zero to use such a prior. In this particular example, this prior is powerful enough to move the posterior mode close to zero when the true value in the DGP was 0.7. In addition, for an autoregressive coefficient whith beta prior, if the asymptote is at 1.0, the implied unit root creates problem for mode optimizaton

**Comment by JohannesPfeifer** [comment]
I agree that this asymptote is not ideal, but it is the prior actually used by Schorfheide in his paper. Thus, I would be very reluctant to change it, particularly as his mode in the data is still above 0.85.
Using ```fs2000_data.mod``` I got
```
rho   0.129   0.7303  0.0577 beta  0.2230 
``` 
for the mode.

**Comment by MichelJuillard** [comment]
The difference on the mode is very odd. For the tests, the prior probably doesn't matter so you can keep it as it is. But, I still think that it is important to tell users to look at the prior plots and wonder if, when there is an asymptote, it really represents what they have in mind.

**Comment by stepan-a** [comment]
Note that we already depart from the JAE paper since we use a simulated dataset instead of the original data (@sebastien-villemot decided this move because there was no license in the datafile distributed on the JAE website).

**Comment by JohannesPfeifer** [comment]
@stepan-a Yes, but this is evident as the dataset is called ```fsdat_simul```. But the model including the estimated parameters is the same.
@MichelJuillard Sure, selecting priors is important, but I am not sure we are in a position to educate people about this. I tell my students to always look at the prior plots.

So what is our course of action on this topic? I would suggest adding a corresponding warning about the unusual prior to the fs2000 files in the examples folder.
