### ISSUE TITLE
Potentially make PosteriorIRF obey irf_shocks

### ISSUE THREAD

**Issue by JohannesPfeifer** [DynareTeam/dynare#364]
The ```irf_shocks ``` option of  estimation restricts the generation of IRFs in  ```PosteriorIRF_core1 ```, but has no effect on  ```PosteriorIRF_core2 ``` and  ```PosteriorIRF ```, which always iterate over ```M_.exo_nbr ```. While this does not affect the number of plots as only IRFs>10^(-6) are plotted and they were initialized to 0, there may be a computational gain in not computing posterior IRF moments for those shocks.

**Comment by JohannesPfeifer** [comment]
@houtanb Could you please lift this restriction in the preprocessor.

**Comment by houtanb** [comment]
@JohannesPfeifer is @stepan-a ok with lifting this restriction?

**Comment by JohannesPfeifer** [comment]
@stepan-a Any input here would be greatly appreciated.

**Comment by stepan-a** [comment]
Fixed in 61e6e80b5a92a0802c7049fb20e18dafc6be5730
