### ISSUE TITLE
Make estimation set the mode-file-option to empty unless specified otherwise

### ISSUE THREAD

**Issue by JohannesPfeifer** [DynareTeam/dynare#378]
If a mode-file has been specified once, it will always be reloaded in all subsequent calls to estimation, thereby overwriting the MCMC results set with set_all_parameters(xparam,estim_params_,M_) and will conflict with the estimation of other specifications where e.g. the parameters to be estimated have changed.

The check currently always is
``` isempty(options_.mode_file) ```

Also, setting mode_file=[] creates an error. Thus, the only way of deleting the mode-file options currently is manually setting options_.mode_file=[];

**Comment by MichelJuillard** [comment]
It needs to be made clear in th manual that mode_file is an option local to estimation statement as it departs from standard (and often unfortunate) behavior

**Comment by JohannesPfeifer** [comment]
@MichelJuillard I added documentation to the pull request.
