### ISSUE TITLE
Allow k-order and estimation DLL to use bytecode for the model evaluation

### ISSUE THREAD

**Issue by sebastien-villemot** [DynareTeam/dynare#38]
Currently, k-order DLL and estimation DLL only work with use_dll option.

This constraint could be easily relieved by calling the M-file of the model from within the DLL, using mexCallMATLAB().

For the bytecode, a similar trick could be done, provided that support is added for 2nd and 3rd order derivatives.

From the implementation side, the idea would be to create an super class of DynamicModelDll.

This change needs to be documented in the reference manual when implemented.

**Comment by stepan-a** [comment]
Not useful.
