### ISSUE TITLE
Check use and precedence of jscale and document it.

### ISSUE THREAD

**Issue by JohannesPfeifer** [DynareTeam/dynare#503]
The use of ``` bayestopt_.mh_jscale ``` and ``` bayestopt_.jscale ``` as well as ``` options_.mh_jscale ``` is confusing an potentially buggy (see also http://www.dynare.org/phpBB3/viewtopic.php?f=1&t=5072). In ``` dynare_estimation_1 ``` we use 
``` 
mh_scale_fname = [M_.fname '_optimal_mh_scale_parameter.mat'];
if exist(mh_scale_fname)
    if options_.mode_compute == 0
        tmp = load(mh_scale_fname,'Scale');
        bayestopt_.mh_jscale = tmp.Scale;
        clear tmp;
    else
        % remove the file if mode_compute ~= 0
        delete('mh_scale_fname')
    end
end
``` 
to read out the ``` mh_jscale ``` from a previous run of ``` mode_compute=6 ```. But this is after ``` dynare_estimation_init ``` where the ``` mh_jscale ``` seems to be translated into the ``` bayestopt_.jscale ``` actually used in estimation. Thus, it looks as if this statement does nothing.

**Comment by MichelJuillard** [comment]
@JohannesPfeifer, the above code is not in dynare_estimation_1.m anymore. What shall we do with this issue?

**Comment by JohannesPfeifer** [comment]
@MichelJuillard i still see it in lines 137 following so I think it is still current

**Comment by MichelJuillard** [comment]
@JohannesPfeifer @stepan-a : I pushed a branch optimal_jscale_parameter. Can you check it and tell me if it takes care of the issue?

**Comment by JohannesPfeifer** [comment]
@MichelJuillard Your branch looks good to me to solve the problem that the scale was never used. But we still have to take the fundamental decision about precedence of options. There are three ways a user can specify the jscale:
1. In the ```estimated_params```-block. This will always have precedence, which is good.
2. Using the ```mh_jscale``` option of ```estimation```
3. By automatically loading it from ```_optimal_mh_scale_parameter.mat``` if ```mode_compute=0```

We now have to figure out what to do if the user specifies ```mode_compute=0``` and sets ```mh_jscale```. The current behavior in your branch is that the jscale from the file will override ```mh_jscale``` set in the ```estimation```-command. If the user wants something different, he has to delete the ```mat-file```. I can live with this behavior, but we need to spell this out explicitly in the manual.

**Comment by MichelJuillard** [comment]
@JohannesPfeifer, you have a point. This is not optimal. A user may have computed the mode with mode_compute=6 and may want to run the Metropolis in another run while modifying mh_jscale.
It would be better for explicit options_.mh_jscale used in estimation() to have precedence over *_optimal_mh_scale_parameter. The latter being used only if there is no mh_jscale option in the estimation call.
Unfortunately, as options_.mh_jscale is initialized at 0.2, I don't see any way to recognize that options_.mh_jscale has been set in estimation().
Maybe we can change the initialization of options_.mh_jscale in a way transparent to the user by setting options_.mh_scale = NaN in global_initialization and giving it a default value in dynare_estimation_init.m as an alternative to *_optima_mh_scale_parameter.
@JohannesPfeifer @stepan-a what do you think?

**Comment by JohannesPfeifer** [comment]
How about a new option for explicitly loading the scale parameter from a file? As this option did never work, we have no backward compatibility to worry about. Moreover, at some point I would like to write a routine for tuning the scale parameters over the full parameter range instead of having a scalar. Here, such an option for loading a matrix might also be helpful.
If we go for a separate option, however, we should not automatically delete the ```_optimal_mh_scale_parameter.mat``` file in  ```dynare_estimation_init``` when ```options_.mode_compute > 0```. Rather, a routine updating this file should take care of it.

**Comment by stepan-a** [comment]
Okay I agree. @houtanb Can you add this option? The syntax would be ```mh_scale_file=FILENAME```, and the preprocessor should write a string in ```options_.metropolis.proposal.scale_file```.

**Comment by houtanb** [comment]
@stepan-a @JohannesPfeifer option added on `optimal_jscale_parameter` branch.

**Comment by JohannesPfeifer** [comment]
I think we have to rethink the field where we save this. How about subsuming this in '''posterior_sampler_options''' instead of having a separate preprocessor option. This would agree better with #1177

**Comment by houtanb** [comment]
@JohannesPfeifer ok, then I will simply revert it and close this ticket.

Is the `optimal_jscale_parameter` branch still of use? Should it be merged, deleted, or are you still going to work on it?

**Comment by JohannesPfeifer** [comment]
@houtanb I have to check out that branch. Just leave it for now and keep this open ticket assigned to me

**Comment by JohannesPfeifer** [comment]
@houtanb That also means the `optimal_jscale_parameter` branch can be deleted

**Comment by houtanb** [comment]
@JohannesPfeifer done.
