### ISSUE TITLE
Discuss and document the load_mh_file option

### ISSUE THREAD

**Issue by JohannesPfeifer** [DynareTeam/dynare#504]
The current behavior of the ``` load_mh_file ```-option with it recomputing the mode, the Hessian, and the scale-factor by default seems counterintuitive. Given the fixed seed, one should get the same results, but there is the risk of them changing between the reloaded chain and the new elements to be added and thus having a chain with difffering proposal densities. We should at least document this behavior and potentially reload the mode-file by default. See also http://www.dynare.org/phpBB3/viewtopic.php?f=1&t=5051

**Comment by JohannesPfeifer** [comment]
@houtanb Could you please add the decision label to this

**Comment by MichelJuillard** [comment]
Proposed decision: reload the mode as well

**Comment by JohannesPfeifer** [comment]
@MichelJuillard I agree. However things are more complicated than I thought. Your envisioned solution requires a mode-file to exist, which is not assured (particularly not when mode-finding overwrites the old model). I would propose to deal with this in 4.5 the following way:
1. From now on we save the proposal density information (scale factor, covariance matrix, starting values for the chains from ```metropolis_hastings_initialization```) into the ```mh_history``` file.
2. We save the last state of the RNG into the ```_mh*_blck*``` files to be able to continue (this also helps solving #912 )
3. When the ```load_mh_file``` option is used, we load both the proposal density information and the RNG seed to continue with the chain
