### ISSUE TITLE
Weibull prior distibution

### ISSUE THREAD

**Issue by MichelJuillard** [DynareTeam/dynare#520]
CMR 2013 are using a Weibull prior distribution. I suggest to add it to the list of prior used by Dynare

**Comment by JohannesPfeifer** [comment]
@stepan-a I had been assigned this ticket. Now we duplicated the work.

**Comment by stepan-a** [comment]
@JohannesPfeifer I am sorry for that. I knew that you had been working on this (Michel also worked on this issue) but I needed this urgently to play with CMR for another project (also I did not remember that someone was assigned).

**Comment by stepan-a** [comment]
I still have to add unit tests for the Weibull random number generator.

**Comment by JohannesPfeifer** [comment]
@stepan-a Do you still plan on adding a unit rest for the random number generator? We do not have this for any other distribution.

**Comment by stepan-a** [comment]
@JohannesPfeifer Sorry I forgot to close this ticket, this was done in e53f3a67fa8bbc615cf1c9fac90cdf3275d48e69.
