### ISSUE TITLE
Discuss allowed use of endogenous variables outside of model-block

### ISSUE THREAD

**Issue by JohannesPfeifer** [DynareTeam/dynare#534]
Consider the mod-file
```
var y, c, k, a, h, b;
varexo e, u;

parameters beta, rho, alpha, delta, theta, psi, tau test;

alpha = 0.36;
rho   = 0.95;
tau   = 0.025;
beta  = 0.99;
delta = 0.025;
psi   = 0;
theta = 2.95;

phi   = 0.1;
test=y*beta;

model;
c*theta*h^(1+psi)=(1-alpha)*y;
k = beta*(((exp(b)*c)/(exp(b(+1))*c(+1)))
    *(exp(b(+1))*alpha*y(+1)+(1-delta)*k));
y = exp(a)*(k(-1)^alpha)*(h^(1-alpha));
k = exp(b)*(y-c)+(1-delta)*k(-1);
a = rho*a(-1)+tau*b(-1) + e;
b = tau*a(-1)+rho*b(-1) + u;
end;

initval;
y = 1.08068253095672;
c = 0.80359242014163;
h = 0.29175631001732;
k = 11.08360443260358;
a = 0;
b = 0;
e = 0;
u = 0;
end;

shocks;
var e; stderr 0.009;
var u; stderr 0.009;
var e, u = phi*0.009*0.009;
end;

stoch_simul;
``` 
The definition
``` test=y*beta; ``` 
results in the preprocessor plugging in for the endogenous variable ```y``` with its yet uncomputed steady state, i.e. 0. Users thus can create a circular problem with the steady state of ``` y ``` depending on ``` test ``` with ``` test ``` depending on ``` y ``` - and would never notice the problem, because the definition does not result in an error. Would it be possible to block this behavior? If we want to allow users to access the steady state value of endogenous variables outside of the model-block, it should be through the ```steady_state```operator. 

Or do I miss something that makes this behavior desirable?

**Comment by MichelJuillard** [comment]
Proposed decision: leave it open until somebody comes up with a new suggestion

**Comment by JohannesPfeifer** [comment]
@MichelJuillard I don't see a workable solution that would not run into problems with backward compatibility. Maybe we should just drop the issue and close the ticket. I seem to be the only one who complained.

**Comment by MichelJuillard** [comment]
@JohannesPfeifer OK, I close the ticket. We need however to remember the issue if at some point we consider a bigger overhaul of the modeling language
