### ISSUE TITLE
Fix version compatibilty issues

### ISSUE THREAD

**Issue by stepan-a** [DynareTeam/dynare#546]
The organization of the (global) structure `oo_` saved on disk is not constant across dynare's versions. In some situations, for instance when we need to get informations about a previous estimation as in #544, this causes a crash because needed fields do not necessarily exist if `oo_` was generated by an older version of Dynare.

**Comment by houtanb** [comment]
Still to do: 3) from @stepan-a's last comment

**Comment by JohannesPfeifer** [comment]
#771 already introduced a conversion function ```convert_dyn_45_to_44```
