### ISSUE TITLE
Potentially change treatment of #-expressions in LaTeX - Code

### ISSUE THREAD

**Issue by JohannesPfeifer** [DynareTeam/dynare#563]
I have a mod-file where I use  `write_latex_dynamic_model;`
The file contains an expression

`#delta_2=delta_2divdelta_1*delta_1;`

We should try to add a way to define a LaTeX name for this expression. Moreover, I noticed that sometimes, the LaTeX-Code adds a time t-index to this expression although expressions cannot be lagged or leaded. This should also be removed if possible.

**Comment by JohannesPfeifer** [comment]
@houtanb Is there any chance of getting this feature soon? By having a command for defining expressions like variables we might also be able to use them in the `steady_state_model`-block to solve #709

**Comment by houtanb** [comment]
@JohannesPfeifer this won't solve #709, which requires more involved changes.
