### ISSUE TITLE
Fix bug in interaction of diffuse filter and stoch_simul

### ISSUE THREAD

**Issue by JohannesPfeifer** [DynareTeam/dynare#573]
See http://www.dynare.org/phpBB3/viewtopic.php?f=1&t=5248

**Comment by MichelJuillard** [comment]
The reason to remove unit_root_vars was that in non trivial models, it is difficult to know a priori which variables are nonstochastic and which ones are stochastic. Declaring nonstationary variables are not necessary for simulation of linear models. We later added the computation of theoretical moments with NaN for non stochastic variables automatically detected by Dynare.
In summary declaring nonstationary variables ask too much from the users and is not necessary.
Specifying steady(nocheck) is sufficient and clear enough once one has understood the problem.
On the other hand, seeing the example, I don't understand why we trigger an error in resid. Without nocheck, the steady state is always checked before local approximation, so I don't see any danger in removing the error from resid.
Proposed decision: remove error from resid
