### ISSUE TITLE
mssbvar: investigate bug with high number of perturbations

### ISSUE THREAD

**Issue by houtanb** [DynareTeam/dynare#586]
mod files with a high number of perturbations cause Matlab to crash after some processing.

see emails from Stephane on 24 Jan 2014 8:56 AM

**Comment by MichelJuillard** [comment]
@houtanb can you add an example triggering the crash?

**Comment by houtanb** [comment]
@MichelJuillard The file is on `sedna:/home/houtanb/mssbvar`. I started the test at `Fri Nov  6 11:56:04 CET 2015` with the `nolog` option to dynare, as the thought was that the log file was becoming too large. It takes several weeks to run

**Comment by houtanb** [comment]
Closing as I was not able to reproduce this error and no longer have the mod files to reproduce it
