### ISSUE TITLE
Fix translation of histval to one-lag problem

### ISSUE THREAD

**Issue by JohannesPfeifer** [DynareTeam/dynare#617]
For deterministic simulations with more than one lag, the translation to a problem with one lag for use in ```sim1``` does not work.

The mod-file 
```
var c k z_forward z_backward;
varexo x z_shock;

parameters alph gam delt bet aa;
alph=0.5;
gam=0.5;
delt=0.02;
bet=0.05;
aa=0.5;

model;
c + k - aa*x*k(-1)^alph - (1-delt)*k(-1); // Resource constraint
c^(-gam) - (1+bet)^(-1)*(aa*alph*x(+1)*k^(alph-1) + 1 - delt)*c(+1)^(-gam); // Euler equation
z_backward=0.1*1+0.3*z_backward(-1)+0.3*z_backward(-2)+0.3*z_backward(-3)+(x(-4)-1);
z_forward=0.1*1+0.45*z_forward(+1)+0.45*z_forward(+2)+(x(+4)-1);
end;

initval;
c = 1.2;
k = 12;
x = 1;
end;

histval;
x(-1)=1.30;
x(-2)=1.30;
end;

shocks;
var x;
periods 2;
values 0.9;
end;

simul(periods=200,maxit=100);
```
shows that the problem comes from ```M_.endo_histval```, which is set to
```
M_.endo_histval = zeros(M_.endo_nbr,M_.maximum_lag);
oo_.exo_simul( M_.maximum_lag + -2, 1 ) = 1.30;
oo_.exo_simul( M_.maximum_lag + -1, 1 ) = 1.30;
``` 
and thus has more than one initial period.

**Comment by sebastien-villemot** [comment]
I realize that the workaround implemented for this case no longer works. One now gets:
```
error: PERFECT_FORESIGHT_SOLVER: 'oo_.endo_simul' has wrong size. Did you run 'perfect_foresight_setup' ?
```

The problem appears for deterministic models with more lags on exogenous than on endogenous, when one uses `histval`. In that case, the matrix `oo_.endo_simul` is too small, because it does not have all the expected lags. The commit mentionned above in this bugreport was therefore probably not the right solution for the problem.

I think that the best solution is revert this commit, and adapt all the perfect foresight routines to be able to deal with a `oo_.endo_simul` which has `M_.maximum_lag` lags at the beginning (and not just 1 lag).

**Comment by sebastien-villemot** [comment]
Commit 4179e25e11f7b890c7d0ce30ead8d34d8d3483c3 is also linked to this issue.

**Comment by JohannesPfeifer** [comment]
@MichelJuillard Referring to your email from May 27, 2015, #986 shows that the mod-file is supposed to have a solution. The reason it does not solve is a variety of bugs. For example, in the current unstable, ```make_ex_``` is called and it has
```
if isempty(ex0_)
    oo_.exo_simul = repmat(oo_.exo_steady_state',M_.maximum_lag+options_.periods+M_.maximum_lead,1);
else
    oo_.exo_simul = [ repmat(ex0_',M_.maximum_lag,1) ; repmat(oo_.exo_steady_state',options_.periods+M_.maximum_lead,1) ];
end
```
But ```ex0_``` was not set by the preprocessor, but only 
```
oo_.exo_simul( M_.maximum_lag + -2, 1 ) = 1.30;
oo_.exo_simul( M_.maximum_lag + -1, 1 ) = 1.30;
```
Because of this, the historical values are lost. You can see this in the final ```oo_.exo_simul```.  There are other problems as well that show up in the unit tests.

**Comment by MichelJuillard** [comment]
Fixed in commit 7d11ed764263a71aec6efe76ad96e7d02f317610

**Comment by JohannesPfeifer** [comment]
@MichelJuillard What exactly is the role of ```ex0_``` and ```ys0_``` that are sometimes global? It seems we are replacing them all over the code. Shouldn't we completely phase them out?

**Comment by JohannesPfeifer** [comment]
@MichelJuillard Another thing: could it be that ```histvalf``` also needs to be adjusted before this ticket can be closed?

**Comment by MichelJuillard** [comment]
@JohannesPfeifer  `ex0_` and `ys0_` are storing initval when endval is present. They shouldn't appear
but in perfect_foresight_setup. Passing them somehow instead of having
them global would be better.

**Comment by MichelJuillard** [comment]
@JohannesPfeifer OK, we still need to check `histvalf` I reopen the issue until then.

**Comment by JohannesPfeifer** [comment]
I opened a new ticket, #1004, for the remaining issues as they touch upon separate issue.
