### ISSUE TITLE
Steady state of a Ramsey model is wrong in some cases

### ISSUE THREAD

**Issue by MichelJuillard** [DynareTeam/dynare#633]
If a Lagrange multiplier appears in the Ramsey model with a lead or a lag of more than one period, the steady state may be wrong.

**Comment by MichelJuillard** [comment]
Currently, the problem seems to be limited to expectation operator. We need to come up with a test case for this issue.

**Comment by JohannesPfeifer** [comment]
@MichelJuillard Could it be we have a test case in ```optimal_policy/Ramsey/ramsey_ex_aux.mod```? See #1119

**Comment by MichelJuillard** [comment]
YES! It is exactly it. I have started working of it but the solution is difficult.
