### ISSUE TITLE
Provide support for Cygwin 64-bit

### ISSUE THREAD

**Issue by sebastien-villemot** [DynareTeam/dynare#640]
Recent versions of Cygwin include a 64-bit version, installed under `c:\cygwin64` by default.

We should support this configuration, at least in two places:
* when compiling MEX files with `use_dll`; see http://www.dynare.org/DynareWiki/ConfigureMatlabWindowsForMexCompilation
* in `README.md`, for people compiling from source

**Comment by JohannesPfeifer** [comment]
@sebastien-villemot Since we do not support Cygwin building of Dynare anymore, I would suggest dropping its support completely and closing this issue. If someone wants dll-compiling on Windows, MSVC should be used as it is free as well.

**Comment by JohannesPfeifer** [comment]
@MichelJuillard I think this can be closed as well
