### ISSUE TITLE
Support new MEX compilation under Windows (MATLAB >= 8.3/R2014a)

### ISSUE THREAD

**Issue by sebastien-villemot** [DynareTeam/dynare#641]
In MATLAB 8.3/R2014a, the `mex` command has been rewritten. In particular, all the `mexopts.bat` logic is now obsolete (but still works, with a warning).

We should aim at supporting the new infrastructure.

See also http://www.dynare.org/DynareWiki/ConfigureMatlabWindowsForMexCompilation and issue #640.

**Comment by JohannesPfeifer** [comment]
We do not support Windows compilation anymore

**Comment by JohannesPfeifer** [comment]
@stepan-a Could you please reopen the issue. This is about the `use_dll` option, not building from source. It is related to #1226

**Comment by JohannesPfeifer** [comment]
With Matlab on Windows now supporting two free compilers that can be easily installed, there is no reason to rely on `Cygwin` anymore. For that reason, I would not spend time on supporting something I consider a legacy system. I would propose to close the issue.
