### ISSUE TITLE
produce & print original model (without auxiliary variable substitutions)

### ISSUE THREAD

**Issue by houtanb** [DynareTeam/dynare#657]
For inclusion in reports (or just general interest), produce the original model and be able to print it in latex.

Add option to include calibrated values in parentheses next to variables in the report.

**Comment by houtanb** [comment]
@JohannesPfeifer, #318 is not related to this change.

Opening another ticket to allow for printing of calibrated values for ```write_latex_*_model``` commands

**Comment by JohannesPfeifer** [comment]
@houtanb #318 is indirectly related. I thought that when adding capabilities for not replacing auxiliary variables it might be easiest to also add capabilities for writing the name of Latex names of substituted variables to ```M_.aux_vars```. But I don't know the code that well, so it can well be that it is unrelated.
