### ISSUE TITLE
Add unit test and example for differentiate_forward_vars

### ISSUE THREAD

**Issue by JohannesPfeifer** [DynareTeam/dynare#727]

**Comment by JohannesPfeifer** [comment]
@stepan-a Can we use https://bitbucket.org/stepan-a/differentiate-forward-variables/src/43b5bf4cd3257d194fd7fc3256f94ad9696f8dfc/mod/rbc.mod?at=master
?

**Comment by stepan-a** [comment]
@JohannesPfeifer But the macro variables PERIODS and AUX must be set (see the README file). I suppose it's easier to define them in the mod file. I moved this git repository to http://gitlab.ithaca.fr/Dynare/differentiate-forward-variables.
