### ISSUE TITLE
Investigate dseries bug under Octave

### ISSUE THREAD

**Issue by JohannesPfeifer** [DynareTeam/dynare#755]
See http://www.dynare.org/phpBB3/viewtopic.php?f=1&t=6105

**Comment by sebastien-villemot** [comment]
@houtanb My impression is that the documentation of `csv2cell` is wrong, and that it perfectly supports files with more than 4096 bytes per line. I could verify this by looking at the source code of `csv2cell`. Also, I could correctly open the CSV file given by the bug reported mentionned at the beginning of this thread. So I think that your workaround should be reverted and that the bug experienced by that user comes from a different source.

**Comment by sebastien-villemot** [comment]
Linking this bug to DynareTeam/dseries#2

**Comment by sebastien-villemot** [comment]
Ok it's actually more complicated than that. Reading files with lines > 4096 bytes was working in the io package until version 2.2.5, in which this ability was broken.
