### ISSUE TITLE
update default values for sensitivity options in doc

### ISSUE THREAD

**Issue by houtanb** [DynareTeam/dynare#789]
It seems as though some default values in the documentation do not accord with the default values in `dynare_sensitivity.m`. e.g. `alpha_rmse`, `ksstat_redform`. Please review the defaults and update the manual.

**Comment by stepan-a** [comment]
@houtanb and @rattoma Can we close this issue?

**Comment by JohannesPfeifer** [comment]
@stepan-a No, it still needs to be done and should be in 4.5. I may be able to do it this weekend.
