### ISSUE TITLE
Add flag if lyapunov_symm fails

### ISSUE THREAD

**Issue by JohannesPfeifer** [DynareTeam/dynare#821]
In models like the one at http://www.dynare.org/phpBB3/viewtopic.php?f=1&t=6291
`lyapunov_symm` fails to solve the Lyapunov equation and outputs NaN. This error is not flagged and no exception thrown out, leading to subsequent crashes. We should add a check whether the solver was successful and only continue if so.

**Comment by JohannesPfeifer** [comment]
Also, ```disclyap_fast.m``` has no iteration termination criterion, allowing for an infinite loop. We should add one and use and exitflag to check whether convergence was obtained.

**Comment by JohannesPfeifer** [comment]
Another example is http://www.dynare.org/phpBB3/posting.php?mode=reply&f=1&t=6934#pr20358

**Comment by JohannesPfeifer** [comment]
@MichelJuillard Should we only check in the initial estimation checks? Or does it make sense to check in every call to ```dsge_likelihood```? The former would reduce the computational burden, but I am afraid that accepting parameter regions with weird initial conditions for the covariance matrix of the states may lead to wrong results.

**Comment by MichelJuillard** [comment]
@JohannesPfeifer, what remains to be done for this issue?

**Comment by JohannesPfeifer** [comment]
@MichelJuillard We haven't even started with the issue. What is missing is 
1. A decision whether we want to add such a check and when we want to check
2. Adding the check and passing the respective output argument back from the function
3. Attaching a penalty and error code to this case

**Comment by stepan-a** [comment]
We all agreed that we should add a flag for iterative methods.

**Comment by stepan-a** [comment]
Also agreed to switch to Schur based method if iterative method fails.

**Comment by JohannesPfeifer** [comment]
Closed by manually merging #1354
