### ISSUE TITLE
Clear up unused or stale files

### ISSUE THREAD

**Issue by JohannesPfeifer** [DynareTeam/dynare#823]
1.	In Master we have a function ```PosteriorFilterSmootherAndForecast.m``` that seems not be called by any other function. Can it be deleted?
2.	In Master, we have both ```rndprior.m```, used only in ```forcst_unc```, and ```prior_draw.m``` to draw from the prior. I would suggest to switch to the latter and delete the first one, because ```rndprior.m``` does not check for violation of prior bounds.
3.	The ```forcst_unc.m``` also does not seem to be used. Can it be deleted?

**Comment by houtanb** [comment]
@stepan-a is it ok to delete ```PosteriorFilterSmootherAndForecast``` and ```forcst_unc```?

**Comment by stepan-a** [comment]
Done in commit 198a6ed7cfa2f6a7b713826299ac870ade9dbe1a.
