### ISSUE TITLE
fix parallel on os x

### ISSUE THREAD

**Issue by houtanb** [DynareTeam/dynare#838]
See: http://www.dynare.org/phpBB3/viewtopic.php?f=1&t=6373

respond there when fixed

**Comment by houtanb** [comment]
@rattoma please note the discussion in #1272 when you make changes to this ticket.

Until you update the code to work with OS X, if it's ok with @rattoma @MichelJuillard or @stepan-a , I will introduce an error at the top of `AnalyseComputationalEnvironment` if the current environment is OS X. 
```
if ismac
    error('Parallel on OS X is not yet supported.');
end
```

**Comment by rattoma** [comment]
I just pushed on my parallel branch a fix to Account for MAC in AnalyseComputationalEnvironment.m and GiveCPUnumber.m [see also #1272.

**Comment by JohannesPfeifer** [comment]
@rattoma @houtanb The problem seems to be still operative, see Joris's post at http://www.dynare.org/phpBB3/viewtopic.php?f=1&t=6373

**Comment by houtanb** [comment]
@JohannesPfeifer of course, the change was made in the master branch. Nothing has changed in 4.4.3

**Comment by JohannesPfeifer** [comment]
@houtanb As Joris was building from source in a different post, I assumed (maybe incorrectly) the he was using the unstable.

**Comment by houtanb** [comment]
@JohannesPfeifer Ah, this was not clear to me on this post. In this case, what you repsonded in the forum is correct. It would be helpful to @rattoma to have as much information as possible so he can recreate the problem locally. I guess he'd need the parallel configuration files, the mod file, data files, etc...

**Comment by JohannesPfeifer** [comment]
@houtanb It seems we can close the issue
