### ISSUE TITLE
Add option to print calibrated values in latex reports

### ISSUE THREAD

**Issue by houtanb** [DynareTeam/dynare#847]
for use in ```write_latex_*_model``` commands

**Comment by JohannesPfeifer** [comment]
@houtanb What exactly do you mean with this ticket? We have a function ```write_latex_parameter_table.m``` introduced in 52f9d164ace863414923fa4d61e141d47cf47969 that creates a table with parameters.

**Comment by houtanb** [comment]
When writing a report with ```write_latex_*_model``` have the calibrated values next to the parameters. @stepan-a wanted it.

**Comment by houtanb** [comment]
@stepan-a to add this feature requires a big hack in the preprocessor. Is that cost worth it?

**Comment by houtanb** [comment]
@stepan-a doesn't remember requesting this. Closing
