### ISSUE TITLE
Deal with forecast uncertainty due to measurement error

### ISSUE THREAD

**Issue by JohannesPfeifer** [DynareTeam/dynare#853]
Currently, Bayesian forecasts completely neglect the presence of measurement error. Theoretically, is is not clear whether we should display
1. the true value of the underlying variable
2. the observed value of the variable including measurement error
While the mean forecast should be unaffected, the presence of measurement error should widen the uncertainty associated with forecasts. But this is in no way reflected in our forecasts. Additionally, neglecting the effect of measurement error on forecasts breaks the equivalence of specifying measurement error as a "structural" shock vs. specifying it using the Dynare command. 

At a minimum, we should document the treatment.

**Comment by JohannesPfeifer** [comment]
Option 2 would be consistent with Christophel et al. (2010): Forecasting with DSGE models, ECB Working Paper 1185, www.ecb.europa.eu/pub/pdf/scpwps/ecbwp1185.pdf

**Comment by JohannesPfeifer** [comment]
@MichelJuillard Any thoughts on this? I would propose to go for option 2.

**Comment by MichelJuillard** [comment]
I think that we should provide an option for taking into account measurement errors or not when computing the confidence interval.
Option 2 provides a confidence interval for the observed variable, bu not the model variable.
In a forecasting context, I guess that one may want to use measurement errors to avoid that these errors interfer with the forecast

**Comment by JohannesPfeifer** [comment]
@MichelJuillard I presume your are not going to do this. Can you please assign the ticket to me? I will try to get it done for 4.5

**Comment by MichelJuillard** [comment]
@JohannesPfeifer done. Thanks

**Comment by JohannesPfeifer** [comment]
Closed by #1239
