### ISSUE TITLE
preprocessor and matlab command lines

### ISSUE THREAD

**Issue by rattoma** [DynareTeam/dynare#855]
I was trying to do tests on the current status of HEAD, but I am getting an error from the preprocessor, that does no longer allow to call matlab functions with multiple output arguments, like

`[out1, out2, out3] = function_name(bla1, bla2);`

the preprocessor complains with the following message

`ERROR: gemc.dyn: line 1686, col 15: syntax error, unexpected '[', expecting '.'`

is there a new way to properly call matlab functions, or this is a bug or a desired behavior of the pre-processor?

the call to matlab is outside of any model or other block.
thank you for your help

**Comment by JohannesPfeifer** [comment]
@rattoma You should use the ```verbatim``` block. Its contents are not interpreted by the preprocessor. On a more fundamental level, a less restrictive way would be appreciated as there is currently no way to call a function with several output arguments within the ```steady_state_model```-block.

**Comment by stepan-a** [comment]
I wonder if this is not a problem introduced by @houtanb's recent commit (30428aeb17162db8328d941491162fe3a6895041) where an interface to declare joint prior over a vector of parameters is defined. @houtanb can you check?

Also, because this issue was not detected by the test suite, it means that a test is needed for that. Could you make a PR in tests with a small example reproducing the issue?

The ```verbatim```block, as suggested by @JohannesPfeifer, should solve the issue, but this should works as before without encapsulating the code in a ```verbatim```block.

**Comment by JohannesPfeifer** [comment]
@stepan-a No. The commit was done in March, but I reported the same issue within the steady_state_model-block to @houtanb on February, 27

**Comment by houtanb** [comment]
@JohannesPfeifer I understood that @rattoma's problem is in a .mod file outside of a block.

@rattoma can you send me a .mod file that creates with the line that creates this error?

**Comment by rattoma** [comment]
@houtan. I just sent you the file by email (by the way, there is no way to attach files within this github discussion, right?). 
I just added a stupid call 

`[m, im] = min(rand(250,3));` 

 in the otherwise usual `ls2003.mod` test file.

**Comment by stepan-a** [comment]
@rattoma It is not possible to attach a file, but you can use a [Gist](https://gist.github.com) (a small github repository that is used to share small set of files editable online).

**Comment by houtanb** [comment]
Here's the file: https://gist.github.com/houtanb/08f2f5d08659416f603f

It works just fine in OS X and Linux. Marco's problem is with the Windows snapshot. Need to check on Windows....

**Comment by JohannesPfeifer** [comment]
@houtanb It works with the preprocessor of February 27, but fails with March 11 on windows.

**Comment by houtanb** [comment]
@JohannesPfeifer or @rattoma can you test this .mod file with the March 2 snapshot and again with the March 3 snapshot? If it breaks with the March 3 but works with the March 2 then it is most likely my commit.

**Comment by JohannesPfeifer** [comment]
@houtanb Done. It works before and stops after March 3.

**Comment by houtanb** [comment]
@JohannesPfeifer thanks. I'm going to install a virtual windows machine now......

**Comment by JohannesPfeifer** [comment]
@houtanb When you do this, could you also look #828?

**Comment by houtanb** [comment]
will do...

**Comment by houtanb** [comment]
I am unable to replicate this problem. I downloaded the 3-11 snapshot, ran the file from the gist above, and the preprocessor works fine (i.e., no error, and it recognizes the matlab code).

Running Windows 8.1, Matlab R2015a, though neither the Windows nor the Matlab versions should matter.

I will leave this open in case someone else wants to work on it.

**Comment by JohannesPfeifer** [comment]
I encouter the problem with yesterday's snapshot on Windows 7. I will try Windows 8.1 when I am back home.

**Comment by JohannesPfeifer** [comment]
I don't know why, but it works under Windows 8, but fails on any Windows 7 machine.
