### ISSUE TITLE
move creation of M_ to a separate file

### ISSUE THREAD

**Issue by houtanb** [DynareTeam/dynare#885]

**Comment by houtanb** [comment]
@MichelJuillard in testing the changes I made to separate the writing of ```M_``` I ran into a problem. I spoke with @stepan-a about it, and he told me to make a note about it here to see if you had an idea.

The changes are on the ```origin/separateM_ branch, 6d1142896dfaaf6dbdd237fb92ed3af37d6a171c.

Here, we are trying to pick out the definition of the ```M_``` structure, placing it in a separate file. The problem comes from native Matlab statements which are processed in a linear fashion. This is a problem because they can depend on what comes before them. Take ```tests/expectations/expectation.mod``` for example. Here, ```phi   = 0.1;``` is a native statement and is used in the shocks block, becoming an input to ```M_.Sigma_e```. When we move the creation of ```M_``` to a different file, ```phi``` is no longer accessible. However, if we write native statements to the separate file that creates ```M_```, we could run into a problem if the user entered the following lines at the end of the ```.mod``` file:
```
save('myoo_.mat','oo_');
clear all
load 'myoo_.mat'
```
If we write these native statements into the file that creates the ```M_``` structure, processing will halt because ```oo_``` is not known to that function. I thought about using a ```try/catch``` block in the file that creates the ```M_``` structure, but here we would encounter a problem if there were a native statement between two ```.mod``` file blocks that modify the ```M_``` structure.

I hop this has been clear. Please advise.

**Comment by MichelJuillard** [comment]
I think it kills the idea in general.  I think that statements like

parameters beta;
....
beta = 0.9;
stoch_simul;
beta = 0.95;
stoch_simul;

would create a problem  I also forgot what improvements a separate function for M_ would bring.

**Comment by stepan-a** [comment]
Okay. I have the impression that we will have to abandon this... 

The idea was to be able to do things with models without having to preprocess a mod file. This would make life much easier when we  want to play with different models. Also I need this for the Julia version, where the preprocessor would write a module with definitions of ```M_```, functions for the dynamic/static models and the steady state, I have posted an example [here](http://gitlab.ithaca.fr/Dynare/JuDynare/blob/master/examples/rbc/rbcmodel.jl). I wonder if the best solution is not to extract what I need from the preprocessor's code...

**Comment by houtanb** [comment]
closing because this change is no longer necessary or desired
