### ISSUE TITLE
An option (noprint?) should be available to disable output of solvers

### ISSUE THREAD

**Issue by tholden** [DynareTeam/dynare#894]
If I'm not misremembering, prior versions of dynare used to allow you to pass custom options to solvers.

While complete flexibility in solver options is probably unnecessary, it would be good if there was an option to disable output from solvers (e.g., to set 'display', 'off' in the fsolve optimset call). Otherwise, when optimising the parameters of a model in a loop over resol (e.g. in a partially global solution procedure), the screen is so full of junk that you cannot track the progress of the outer optimisation.

**Comment by JohannesPfeifer** [comment]
@houtanb This is not a preprocessor issue. I already have a working version that uses the options already present. You can assign me to this ticket.
