### ISSUE TITLE
Allow specifying output directory for estimation

### ISSUE THREAD

**Issue by JohannesPfeifer** [DynareTeam/dynare#910]
```dynare_estimation.m``` takes as an input ```dname```, but as far as I can see, there is no way to set this. ```ComputingTasks.cc``` in line 482 only writes ```var_list_``` as an argument.

**Comment by houtanb** [comment]
This is not a bug. The ```dname``` argument to ```dynare_estimation``` is intended to allow it to be called directly without using the rest of dynare. It is not necessary for dynare to pass the ```dname``` argument given the ```if``` statement on line 57.

**Comment by JohannesPfeifer** [comment]
@houtanb Unfortunately, that is not a solution. I would like to set ```dname``` from within a mod-file. But that is currently impossible as I would have to call ```dynare_estimation``` myself with the input arguments and manually set all options. The preprocessor will always call it without ```dname```. But because of the check whether ```dname``` is passed, I cannot even set ```options_.dname``` manually before an ```estimation```-command in my mod-file as it will always be overwritten.
While passing this argument is not necessary, I would like to have the option to set it.

**Comment by stepan-a** [comment]
Okay. Would ```dirname```be a good option name for you?
