### ISSUE TITLE
Investigate preprocessor crash with external function in model-local variable

### ISSUE THREAD

**Issue by JohannesPfeifer** [DynareTeam/dynare#916]
See ```use_local_variable_for_beta.mod``` at http://www.dynare.org/phpBB3/viewtopic.php?f=1&t=6772

**Comment by JohannesPfeifer** [comment]
@houtanb Does it make sense to add this file as a unit test?

**Comment by houtanb** [comment]
Perhaps.... though I think we need to rethink our testing strategy. Right now, the test suite takes several hours to complete and if we add a new test for every bug we encounter (as we have apparently been doing) it will become even more unwieldy. Perhaps @stepan-a or @MichelJuillard will have some input on this, but I think we should cut down and combine tests in the test suite where possible so as to diminish the amount of time it takes to run.

Also, in this particular case, the external function requires the symbolic toolbox which we do not have.

**Comment by MichelJuillard** [comment]
Do we have now timing for each of the test case?
