### ISSUE TITLE
Add preprocessor interface and documentation for dr_display_tol and huge_number

### ISSUE THREAD

**Issue by JohannesPfeifer** [DynareTeam/dynare#924]
See #906 and 6d0dfc2d3fe302333204bac446458b1dd3b62b49

**Comment by houtanb** [comment]
@JohannesPfeifer is this for ```estimation```?

**Comment by JohannesPfeifer** [comment]
```dr_display_tol``` is ```stoch_simul``` and ```huge_number``` is estimation and potentially ```osr```.

**Comment by houtanb** [comment]
so is it or is it not ```osr```?

**Comment by JohannesPfeifer** [comment]
Also ```osr``` please, although this will require some additional changes.

**Comment by houtanb** [comment]
@JohannesPfeifer I'll leave the documentation to you before closing this ticket
