### ISSUE TITLE
Add preprocessor interface for selecting proposal density

### ISSUE THREAD

**Issue by JohannesPfeifer** [DynareTeam/dynare#925]
In the MCMC, we seem to have everything in place for using a student t-distribution as the proposal density, but we have no interface. 
Modify the estimation command to accept the following new options:
* proposal_distribution, which takes two arguments: ```rand_multivariate_normal``` (default) or ```rand_multivariate_student``` and maps to ```options_.proposal_distribution```
* ```student_degrees_of_freedom```, which accepts an integer argument and maps to ```options_.student_degrees_of_freedom```

These options already exist in ```global_initialization.m```. 
 After doing this, we need to convert ```tests/estimation/t_proposal/fs2000_student.mod``` to use this interface.

**Comment by stepan-a** [comment]
I did not use the student as a proposal since years... We should test it first. With the matricvariate Student, there should be an additional hyperparameter (for the degrees of freedom), I do not remember how we set it...

**Comment by JohannesPfeifer** [comment]
I am already working with it and it seems fine. Of course, we also need an interface to set ```options_.student_degrees_of_freedom```.
