### ISSUE TITLE
Clarify notation of MS-SBVAR

### ISSUE THREAD

**Issue by JohannesPfeifer** [DynareTeam/dynare#934]
Section 4.18 of the manual refers to variables limke A^0, A^+ or Q. But they seem to come from a different paper than the cited Sims/Waggoner/Zha (2008). My guess is Sims/Zha (1998). See also 
http://www.dynare.org/phpBB3/viewtopic.php?f=1&t=6801&p=19671#p19671

**Comment by houtanb** [comment]
from Dan:
The 2008 paper with Chris and Tao does use Q for the transition matrix, but uses A for A0 and F for A+.  It is true that Sims and Zha, 1998, does use the A0, A+ notation, but that paper does not have Markov switching, so there is no transition matrix.
