### ISSUE TITLE
Add interface for TaRB algorithm

### ISSUE THREAD

**Issue by JohannesPfeifer** [DynareTeam/dynare#940]
In ```estimation``` we would need the following options:

1. ```use_TaRB``` which translates to ```options_.TaRB.use_TaRB=1```;
2. ```TaRB_mode_compute=integer``` resembling ```mode_compute``` and translating into ```options_.TaRB.mode_compute=4```
3. ```TaRB_new_block_probability=double``` translating into ```options_.TaRB.new_block_probability``` and checking whether it is between 0 and 1.
4. ```TaRB_optim``` resembling ```optim``` and translating into ```options_.TaRB.optim_opt```

**Comment by houtanb** [comment]
@JohannesPfeifer 
2. what is the default for TaRB.mode_compute?
3. what is the default? The check will be done by the matlab code

**Comment by JohannesPfeifer** [comment]
If you need to know this for ```global_initialization```, I already took care of that. The default for TaRB.mode_compute is 4. The default for ```TaRB_new_block_probability``` should be 0.25. Should I add the check to my Matlab code implementing it (that is after mode-finding)? Or do we check in ```initial_estimation_checks.m```?

**Comment by houtanb** [comment]
Yes, it was for ```global_initialization```.

That depends on when you want the user to know about it. I would put it in ```initial_estimation_checks```.

**Comment by houtanb** [comment]
@JohannesPfeifer can you do the doc?

**Comment by JohannesPfeifer** [comment]
Sure, I will add it together with the algorithm itself. Thanks a lot for the quick work.

**Comment by houtanb** [comment]
Ok, np
