### ISSUE TITLE
Potentially add interface to set parameter bounds for osr.

### ISSUE THREAD

**Issue by JohannesPfeifer** [DynareTeam/dynare#948]
In principle, there is everything in place to use constrained optimizers with osr. An example on how to use this with a user-defined optimizer wrapper is at http://www.dynare.org/phpBB3/viewtopic.php?f=1&t=6835
However, we do not provide an interface to set such bounds. We should discuss if we should leave it at that (more work for users) or whether we provide functionality to automatically set the bounds (including their correct ordering in the parameter vector).

**Comment by JohannesPfeifer** [comment]
I guess this supersedes #58

**Comment by MichelJuillard** [comment]
Yes it does

**Comment by JohannesPfeifer** [comment]
Then we should close #58

**Comment by stepan-a** [comment]
@houtan Can you add a new block named ```osr_parameter_bounds``` for that purpose. The preprocessor should output a new subfield in 

```M_.osr.param_names```, n*1 cell of strings
```M_.osr.param_indices``` n*1 vector
```M_.osr.bounds```,  n*2 array

I suppose that it's not too much work because it looks very close to what we do with ```estimated_param_bounds```.

**Comment by houtanb** [comment]
@stepan-a please tell me the syntax you want for this block. It does not seem to coincide much with `estimated_params_bounds`

**Comment by MichelJuillard** [comment]
We need to think about this syntax also in relation with occasionaly
binding constraints.

We have the following contexts:

1) occasionaly binding constraints associated (replacing) a model
equation (LMMCP or OCCBIN) -> use equation tag
2) occasionaly binding constraints associated with a first order
condition of optimal policy (Ramsey problem) (LMMCP or OCCBIN)
3) occasionaly binding constraints without association with a particular
equation (PATH). One can use equation tags, but this is not required as
the algorithm builds the mixed complementarity problem behind the scene.
4) estimated parameters bounds
5) parameters bounds for OSR

Best

Michel


Houtan Bastani writes:

> @stepan-a please tell me the syntax you want for this block. It does not seem to coincide much with `estimated_params_bounds`
>
> ---
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/DynareTeam/dynare/issues/948#issuecomment-217890624


-- 
Michel Juillard

**Comment by JohannesPfeifer** [comment]
@houtanb Why do you think it does not coincide much with ```estimated_params_bounds```?

**Comment by houtanb** [comment]
In @stepan-a's description, there was no mention of the bounds for the standard error and correlation, as we have for `estimated_params_bounds`. Furthermore, the output fields differ.

**Comment by JohannesPfeifer** [comment]
@houtanb I see. The idea is to have a block
```
osr_param_bounds;
alpha,0,10;
beta, -1,10;
end;
```
that allows for structural parameter names, but not correlations, standard errors, measurement error, etc. The content of the pairs 
```param_name, lower_bound, upper_bound;```
should map into 
```M_.osr.param_names```, which is a n by 1 cell of strings
```M_.osr.param_indices```, which is a n by 1 vector storing the index of the parameter in ```M_.params```
```M_.osr.bounds```, which is a n by 2 array

So in terms of the basic syntax it mirrors the ```estimated_param_bounds``` for structural parameters (@MichelJuillard so 4) and 5) on your list work the same way), but of couse the mapping to ```M_``` is different as @houtanb pointed out

**Comment by houtanb** [comment]
@JohannesPfeifer done. Can you add the documentation?

**Comment by JohannesPfeifer** [comment]
@houtanb Yes, I will work on the documentation and the final implementation steps

**Comment by JohannesPfeifer** [comment]
@MichelJuillard @houtanb There is a fundamental design choice showing up here. Currently we set the above fields only for parameters in the ```osr_params_bounds;``` block. So the name vector for example only exists for the parameters where bounds have been specified. 
I would prefer to use this opportunity to move preprocessor objects like ```osr_params_``` to the ```M_.osr``` structure and make all subfields have ```n_osr_params``` rows. This would also allow us to get rid of the cumbersome ```i_params``` selection and passing as a function argument in ```osr.m``` and friends (and similar cases).

**Comment by JohannesPfeifer** [comment]
@houtanb I talked to @MichelJuillard We will go for the  ```M_.osr``` structure with ```n_osr_params``` rows and provide backward compatibility via a conversion utility. Could you please do the preprocessor changes? I will do the Matlab part including the conversion tool. The plan is to have ```M_.osr``` with ```n_osr_params``` row subfields
```param_names```, ```param_bounds```, ```param_indices``` as well as subfields ```variable_indices``` (storing the current content of ```i_var```) and ````variable_weights``` (storing the current content of ```W```)

**Comment by houtanb** [comment]
@JohannesPfeifer I'm a bit confused by your previous message. Do you mean that `M_.osr.param_names` and `M_.osr.param_indices` should be `n_osr_params` by 1? And `M_.osr.param_bounds` should be `n_osr_params` by 2? Where do `i_var` and `W` come from?

**Comment by JohannesPfeifer** [comment]
@houtanb Yes. The fields related to parameters should have the size of the parameter vector to be optimized, not just the parameter that have bounds set. Parameters not declared with bounds should have default bounds of [-Inf, Inf].
```i_var``` and ```W``` are the inputs to ```osr.m``` already set by the preprocessor. As far as I can see they are called ```obj_var_``` and ```optim_weights_``` in the preprocessor.

**Comment by houtanb** [comment]
@JohannesPfeifer in its current form, if there are multiple `osr_params` statements, only the last one counts as far as the declaration of osr parameters. Is this correct or is this a bug? Should an error be produced in the `.mod` file if there are more than one `osr_params` statements?

**Comment by houtanb** [comment]
@JohannesPfeifer is there are reason `osr_params_` is set as a `char` as opposed to a cell array of strings?

**Comment by JohannesPfeifer** [comment]
@houtanb I would provide a warning in the preprocessor and always only save the value of the last block.
Regarding your other question: we always go for cell arrays instead of character arrays. If I said anything else, please ignore it

**Comment by houtanb** [comment]
@JohannesPfeifer no, you didn't. It's just that that's what's currently being printed for `osr_params_`. I just converted it using `cellstr`

**Comment by houtanb** [comment]
@JohannesPfeifer now that `M_.osr.param_indices` will be the same size as the number of parameters, I am printing it when the `osr_params` statement is encountered. I hope this is ok.

**Comment by JohannesPfeifer** [comment]
It should have the same size as ```osr_params``` not as ```M_.params```. Writing it when ```osr_params``` is encountered is fine

**Comment by JohannesPfeifer** [comment]
Close in #1196
