### ISSUE TITLE
Make M_.dname more consistent

### ISSUE THREAD

**Issue by MichelJuillard** [DynareTeam/dynare#979]
M_.dname is used more as an option than as a characteristic of the model file. By default, the directory name of saving output is M_.fname. When the user wants to change the name, this should be setting options_.dname, not M_.dname

**Comment by JohannesPfeifer** [comment]
I think we need to separate two functions here. ```options_.dname``` is for user-specified names. ```M_.dname``` rather is our hack to allow recursive estimation/forecasting to change the output folder.

**Comment by MichelJuillard** [comment]
Good point. I had forgotten.

**Comment by JohannesPfeifer** [comment]
With recursive estimation, ```M_.fname``` is ```options_.dname``` plus underscore observation number. Thus, ``` M_.fname``` needs to be given precedence whenever it is set. Otherwise ```options_.dname``` must be used.
